### ISSUE TITLE
v2.1 lacks support for operationModes leavingWaterTemperature

### ISSUE THREAD

**Issue by Deldion** [speleolontra/daikin_residential_altherma#102]
After upgrading to the current version 2.1, only the controls for the water tank are available.
The wifi module is BRP069A78.
What information would you like me to collect in order to help?

**Comment by jwillemsen** [comment]
Can you attach the device diagnostics (clear the confidential data), the list of altherma entities, and the full HA log

**Comment by Deldion** [comment]
Clearing confidential data proves challenging, not sure if I made it successfully.. 
## Diagnostic 
* [daikin_residential_altherma-3e79da7e9e1c67eb057bbe0f487da5e7-None-bcab02aa773437b1101e89cc748ca3d2.json.txt](https://github.com/speleolontra/daikin_residential_altherma/files/10909531/daikin_residential_altherma-3e79da7e9e1c67eb057bbe0f487da5e7-None-bcab02aa773437b1101e89cc748ca3d2.json.txt)

## HA Log
Below are the daikin related errors. 
```
Logger: homeassistant.components.climate
Source: custom_components/daikin_residential_altherma/climate.py:219
Integration: Climate (documentation, issues)
First occurred: 2:35:28 PM (2 occurrences)
Last logged: 2:35:28 PM

Error adding entities for domain climate with platform daikin_residential_altherma
Error while setting up daikin_residential_altherma platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 629, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 264, in capability_attributes
    self.hass, self.min_temp, self.temperature_unit, self.precision
  File "/config/custom_components/daikin_residential_altherma/climate.py", line 219, in min_temp
    return float(self._device.getData(ATTR_TARGET_LEAVINGWATER_OFFSET)["minValue"])
TypeError: 'NoneType' object is not subscriptable
```
```
Logger: homeassistant.loader
Source: loader.py:810
First occurred: 2:34:38 PM (6 occurrences)
Last logged: 2:34:38 PM

We found a custom integration daikin_residential_altherma which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
We found a custom integration wyzeapi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
We found a custom integration truenas which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

**Comment by jwillemsen** [comment]
Interesting, your device has `leavingWaterTemperature` as `controlMode`, but uses `leavingWaterTemperature` as `operationModes`, where until now I only did see the `operationModes` with value `leavingWaterOffset`. 

Looks we need some more code, when `controlMode` is 'leavingWaterTemperature` we can have `operationModes` with value `leavingWaterOffset` or `leavingWaterTemperature`.

**Comment by jwillemsen** [comment]
Could you try a branch with some quick fixes, see https://github.com/jwillemsen/daikin_residential_altherma/tree/jwi-targetleavingwatertemperature

**Comment by jwillemsen** [comment]
Let me know whether the branch works, when it works I can merge it and release v2.2

**Comment by Deldion** [comment]
Thank you for your swift reply. Will test once possible and let you know

**Comment by jonasdiemer** [comment]
Hi,

looks like I am having the same issue (basically the controls for the water tank disappeared after the update). Looking forward to testing a release.

Regards

**Comment by jwillemsen** [comment]
Can you test my branch and let me know if it fixes the issue, if not, please attach the log

**Comment by jonasdiemer** [comment]
I can try - could you point me to how to do it? I've installed the extension via HACS...

**Comment by jwillemsen** [comment]
How water tank is now separate, check the altherma entities, should be a water_heater. I use git directly, so don’t know how easily you can test my branch

**Comment by jwillemsen** [comment]
Check under Settings the Altherma device, what do you see, mine gives the following 
![Screenshot_20230307_184822](https://user-images.githubusercontent.com/47353/223506462-40bcb16f-96f9-4b04-9737-ac86e4e247a3.png)

**Comment by colseven** [comment]
not working, tank and boost also not avalible.
![bild 2023-03-07 um 19 29 34](https://user-images.githubusercontent.com/63189272/223516546-36fb7198-62f2-496d-a758-31c2c8095653.jpg)

**Comment by jonasdiemer** [comment]
Looks pretty much the same (haven't tried your branch, still on the latest release). So probably all is OK, I just need to "remap", as now the heating part is "Heat", which on my side has a "offset" (difference to the temperature governed by the heat curve; and there is now the "Heat Pump" part, which is the water tank.

When reading "Altherma Tank as separate device" in the release note I kind of expected a separate Home Assistant "device", but I guess you meant it's another "thing" (entity group?) inside the device.

<img width="665" alt="image" src="https://user-images.githubusercontent.com/1502748/223516538-a21dccfd-df52-4b75-964d-cae8a4eaa6e8.png">

**Comment by jonasdiemer** [comment]
I noticed the warm water temperature is now adjustable, however it doesn't seem to update on the Altherma. Any idea why (e.g. it collides with a time schedule?)

**Comment by Deldion** [comment]
I've experienced a time delay always when issuing commands from HA.
Like a time interval thing.
Sometimes it takes a minute to send the command and sometimes it is instant.

**Comment by Deldion** [comment]
@jwillemsen If you could create the branch to this repo, then we could try more easily from within hacs, since there is the option to change branch from inside HACS.
Still not home to test, only have access on phone

**Comment by jwillemsen** [comment]
> not working, tank and boost also not avalible.
> ![bild 2023-03-07 um 19 29 34](https://user-images.githubusercontent.com/63189272/223516546-36fb7198-62f2-496d-a758-31c2c8095653.jpg)

Boost/tank are now modes of the separate water heater entity, no switches anymore

**Comment by jwillemsen** [comment]
> @jwillemsen If you could create the branch to this repo, then we could try more easily from within hacs, since there is the option to change branch from inside HACS.
> Still not home to test, only have access on phone

Created leavingWaterTemperature branch

**Comment by jonasdiemer** [comment]
> I noticed the warm water temperature is now adjustable, however it doesn't seem to update on the Altherma. Any idea why (e.g. it collides with a time schedule?)

Deactivated the program (via installer menu, set to "keep warm only" (translated from German, not sure about the exact English term)), now I can set the water temperature from Home Assistant.

**Comment by jwillemsen** [comment]
> I noticed the warm water temperature is now adjustable, however it doesn't seem to update on the Altherma. Any idea why (e.g. it collides with a time schedule?)

See if there is an error in the log.

**Comment by colseven** [comment]
I've re-recorded everything, that's all I get. Do you need the diagnostic files?
![bild 2023-03-07 um 19 50 53](https://user-images.githubusercontent.com/63189272/223522153-7e65bc7c-54cc-4c83-b607-9cad01c935bb.jpg)

**Comment by jwillemsen** [comment]
Is that with the latest fixes @colseven? If yes, check the log and add it here with the diagnostics

**Comment by colseven** [comment]
@jwillemsen Yes, it is the latest version from you. Attached is the diagnostic file. Since I have integrated 3 Althermas via my account, there may be a little more in it, but I have always had them in and so far everything has worked well.
[config_entry-daikin_residential_altherma-fc259d3f2030755f1407bf928854ae98.json.txt](https://github.com/speleolontra/daikin_residential_altherma/files/10913095/config_entry-daikin_residential_altherma-fc259d3f2030755f1407bf928854ae98.json.txt)

**Comment by colseven** [comment]
@jwillemsen Boost and temperature adjustment from the hot water tank work, also switching off :) The only thing missing for me is the offset for heating, which was still there before the update. Function heating, cooling and function off!

**Comment by jwillemsen** [comment]
@colseven looks you have a different issue, you use externalRoomTemperature, is it correct that in the onecta app you can set an offset?

**Comment by colseven** [comment]
@jwillemsen No external Room Temperature, see App screen.
![bild 2023-03-07 um 20 13 29](https://user-images.githubusercontent.com/63189272/223526861-2ab4c2bd-8106-434a-81f4-4065c0ed9ff9.jpg)

And, I can only set the hot water temperature to 54°C, but 55°C is possible in the app ... it would be great if that could also be set to 55°C via HACS

**Comment by colseven** [comment]
@jwillemsen In the old version I had an offset and I always used it actively via HA, since the update it's gone.

**Comment by jwillemsen** [comment]
@colseven, can you create a separate issue with your diagnostics, I think I know what I need to add, will prepare a test branch tomorrow

**Comment by jwillemsen** [comment]
@colseven for domesticHotWaterTank your json shows 54 as maxtemp, no idea why onecta shows 55, that looks incorrect to me

**Comment by jwillemsen** [comment]
Try again @Deldion , fixed some issues

**Comment by Deldion** [comment]
Yup, seems to do the trick!
![image](https://user-images.githubusercontent.com/55108743/223546265-06a5f0b6-53df-4154-bded-7b03ccfa3dba.png)

**Comment by jwillemsen** [comment]
Great, I will merge the pr, everything else tomorrow

**Comment by jwillemsen** [comment]
@colseven Can you test the externalRoomTemperature branch? That should fix your use case
