### ISSUE TITLE
Not able to connect to Daikin BRP069A78 WLAN card (configuration menu options greyed out except AP mode) continued

### ISSUE THREAD

**Issue by FredG2** [speleolontra/daikin_residential_altherma#104]
Not sure which restrictions the wifi adapter has, please contact your installer to have it setup

_Originally posted by @jwillemsen in https://github.com/speleolontra/daikin_residential_altherma/issues/83#issuecomment-1440682964_
            
Hello John and all,
I have now called Daikin's technical end customer support again.

They asked me the already known points:
- The SSID of the home network must not contain any special characters
- Home network can only be 2.4 Ghz
- Only WPA2 encryption

I had already checked all that.

Then they told me to have my dealer send me a new SD card to make sure it's not broken before Daikin support can come to my house.

My dealer has then sent me a new card, but unfortunately the connection cannot be established even with the new card.

As a next step, my dealer told me that before he sends me the Daikin technical support and they will only blame it on the router configuration for a lot of money, he wants to study my router documentation and send me a recommendation regarding my router port configuration for "Digitalisierungsbox Premium" (main router from Telekom, really a Bintec router product) and AVM Fritzbox 4040 (floor router) . He had a similar problem with Mitsubishi and that was due to the fact that you first have to open ports on the router which the SD card needs.

Question to all of you is did you need to do that with your home network router as well in this situation? And if yes, which ports where opened and how. My router is only distributing dynamic DHCP-IP addresses to all WLAN devices.

Many thanks in advance!

FredG2

**Comment by jwillemsen** [comment]
As far as I remember I used the Daikin onecta app to configure the altherma correctly to connect to the wifi network of my home. What does the onecta app show?

**Comment by jwillemsen** [comment]
Maybe https://www.daikin.eu/en_us/faq/the-onecta-application-is-not-successful-in-connecting.html helps?

**Comment by FredG2** [comment]
> Same here. Enabled AP mode on unit, it emits ap-Daikin as access point, connect to it. Via app submit wifi details, it stores them on device. Disconnect and connect to home wifi - should work out of the box. Huawei router. Neighbour has same unit and when trying to store wifi details via app it just freezes. Reset didn't help. Local service told that router is too far, which I don't believe. He doesn't use apps in general so he didn't pursue fixing this

Hello jwillemsen und arn1s-m,

I have AVM Fritzbox 4040 floor routers (ground floor, upper floor, top floor) which are connected to the Telekom "Digitization Box Premium" (main router) via a LAN cable and corresponding floor LAN switches. The Telekom "Digitization Box Premium" emits a home WLAN with the same SSID as the WLAN that every floor router emits. 

I connected my iPhone to the WLAN of the Telekom "Digitization Box Premium" for my Daikin Onecta app connection tests because it is in the basement near the Daikin hot water tank. When not successful, I also got an AVM floor router down to the basement and connected my iPhone to it. Unfortunately, still not successful. In addition, I also tested the iPhone and the Onecta-Ap connection only with the Telekom mobile data network enabled and Home WLAN switched off, although the Telekom mobile phone reception in the basement is not very good. Still not successful. I also tested with the Telekom mobile data network switched off (the latter as recommended in the Onecta app for iPhone connection problems) and only Home WLAN enabled. Unfortunately so far all without success.

All WLAN client devices get an IP address from the main router via DHCP, including my iPhone. So there are no fixed IP addresses. I also have many client WLAN devices and all are connecting well to my home WLAN, including my Iphone. Iphone Internet access is good in my basement where the tank is located over my home WLAN.


Many thanks in advance,

FredG2

**Comment by jwillemsen** [comment]
Have you tried to remove and reinstall the onecta app? As far as I remember the first step is to let your onecta app connect with the altherma itself (make sure it emits itself as access point, see the daikin link), the onecta app will transfer the wifi settings from the phone to the altherma, when that is successful the altherma will connect to the wifi itself.

**Comment by FredG2** [comment]
> Have you tried to remove and reinstall the onecta app? As far as I remember the first step is to let your onecta app connect with the altherma itself (make sure it emits itself as access point, see the daikin link), the onecta app will transfer the wifi settings from the phone to the altherma, when that is successful the altherma will connect to the wifi itself.

Hello jwillemsen,
I can try to remove the Onecta app from my Iphone and reinstall it but I doubt that this will resolve the issue. I will let you know.

I already wrote in previous posts that I follow all connection steps explained in the Onecta App correctly, meaning I activate the "AP modus" in the "wireless gateway" menu option in the display of my Daikin hotwater tank and then in the Onecta App I am trying to add my hotwater tank device by connecting to it via access point. I am then getting a pop-up asking me if I want to connect to the "Daikin-Ap" WLAN Ap network (meaning the card at this point is indeed emitting a WLAN). However afterwards nothing is happening. The connection wheel is just spinning forever. When I look in the WLAN settings of my Iphone after a while also the WLAN "Daikin-Ap" which was previously visible has disappeared.

Latest recommendation of my DAIKIN dealer which I received this morning ist that I should call the technical support of Telekom since my main router is a "Digitization box premium from Telekom (rellay originally a BinTec product) and ask them if an how following ports can be enabled:

- 80 HTTP
- 443 HTTPS
- 8883 MQQT

Does this mean that I need to enable those points for external access over the Internet? If yes I am not sure if I would like to do this.

Right now my impression is that the Daikin BRP069A78 WLAN card is only working out of the box or at all with certain router products. It is not working with all router products. In the following thread people are reporting that they can not have it connecting to TP-Link routers but connection to other router products is working.
https://community.tp-link.com/en/home/forum/topic/594558

If true I do not understand why Daikin is selling this BRP069A78 WLAN card to customers. My router "Telekom Digitization Box Premium" and "AVM Fritzbox 4040" are used by millions of people in my country.

Many thanks in advance!

Regards,

FredG2

**Comment by jwillemsen** [comment]
Personally I don't understand why they are only using wifi, why not provide an ethernet port so that a cable can be used. Also they export a small subset of data, using the esp they have much more data available, I want all that data in HA also.

**Comment by jwillemsen** [comment]
We can't really do anything about this in this integration, when the onecta app doesn't work we can't solve it. 

It is good that you report this here, support for daikin is hard to find, maybe this issue helps others.

**Comment by FredG2** [comment]
> We can't really do anything about this in this integration, when the onecta app doesn't work we can't solve it.
> 
> It is good that you report this here, support for daikin is hard to find, maybe this issue helps others.

Hello JWillemsen,
I've finally managed to establish an initial connection via my home WiFi from my Iphone 12 Pro Max to the WiFi "Daikin-AP" of the Daikin WiFi SD card via the Onecta-Ap. After the initial connection, the Daikin WiFi SD card firmware was updated and the previously greyed out menu options in the Wireless Gateway menu on the hot water tank display became visible. After that, the Onecta Ap asked me to re-enable the “AP Mode” in the “Wireless Gateway” menu on the hot water tank. Then the Onecta app found my home WiFi automatically and after entering my home WiFi password, my hot water tank was added as a unit in the Onecta app. I no longer needed to use the other activated menu options in the "Wireless Gateway" menu on the hot water tank to establish a permanent connection to my home WLAN.


The hot water tank remote control options in the Onecta Ap are pretty sparse:
- The current tank temperature is displayed. However, my impression is that the tank temperature measurement from Daikin in the tank only imprecisely reflects the temperature in the tank. For example, the temp sensor seems to be placed quite far down in the tank, near the cold water inlet. At the top, where the water is taken off, the water is even warmer. In any case, the water still feels warmer when it comes out of the tap, although a colder tank temperature is displayed. But I still have to confirm this with a thermometer measurement when I take the water tap
- You can set the daily program remotely, which is really useful
- The firmware of the hot water tank can be updated, which I was able to do (from version 6.7.0 to version 6.9.0)

The initial connection finally worked after I:
- Completely deleted and reinstalled the Onecta app on my Iphone 12 Pro Max
- I had deactivated the mobile data network on my Iphone 12 Pro Max
- The connection finally succeeded over my home WiFi. My Iphone 12 Pro Max was connected via the home WiFi of my Digitization Box Premium 1 (2.4 GHz wireless network, no special characters in the home WiFi name, WPA mode: "WPA 2", the home WiFi password can contain special characters). .
- The crucial point in my opinion, however, was that after activating the "AP mode" on the hot water tank, I first manually established a connection to the "DAIKIN-Ap" WLAN of my water tank in the WLAN settings of my iPhone 12 Pro Max , and only then established an "AP mode" connection in the Onecta-Ap. In the end, my impression was that if you just confirm the pop-up in the Onecta app that prompts you to "AP mode" to establish a connection with the "Daikin AP" WLAN, the Iphone 12 Pro Max can do this Connection setup fails. Otherwise, the iPhone is first connected to my home WiFi and the Onecta Ap cannot switch from the home WiFi to the "Daikin AP" WiFi and then back to the home WiFi. At least on the first switch, the Onecta ap seemed endlessly stuck.
- It was not necessary to activate router ports, as recommended by my Daikin dealer
- As I said, the connection finally worked via my Iphone 12 Pro Max with the latest Apple OS version (16.3.1). I didn't need to test another older iPhone


I will now send back the second WiFi SD card (BRP069A78) that my Daikin dealer sent me as a replacement card in the next few days. The Daikin support wanted to rule out that the card is broken.


I have asked my dealer to complain to Daikin on my behalf that the connection to the Onecta-Ap is too cumbersome and error-prone. In my opinion, there is a software architecture problem here. You probably want to save money by initializing the SD WLAN card from the cloud so that you don't have to constantly provide the customer with software updates for direct updates to the hardware of the WLAN SD card. However, this is all at the expense of error susceptibility and usability for the customer. I spent three days of my precious time trying and testing all kinds of things, especially at night, and I was constantly annoyed.


Thanks very much!



Best regards,



Fred121
