### ISSUE TITLE
Offset when heating is no longer displayed/cannot be changed

### ISSUE THREAD

**Issue by colseven** [speleolontra/daikin_residential_altherma#108]
@jwillemsen
externalRoomTemperature was indeed enabled. I deactivated it and can now also see the current heating flow temperature - unfortunately I can't adjust it yet. I've already reinstalled the addon and restarted it, so far it has always stayed there.

The rest works flawlessly.
![bild 2023-03-08 um 11 26 14](https://user-images.githubusercontent.com/63189272/223688575-1320289c-2620-46d2-9ac4-6e591babbe5d.jpg)
![bild 2023-03-08 um 11 26 22](https://user-images.githubusercontent.com/63189272/223688587-7b0475be-f88b-436e-bd84-6f4655353f7f.jpg)
![bild 2023-03-08 um 11 26 33](https://user-images.githubusercontent.com/63189272/223688600-e12e4ba4-204b-4ff5-b3c9-6c5f6cdc4222.jpg)

Error Log:

Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/service.py:663 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 11:22:04 (1 occurrences) 
Last logged: 11:22:04

[548184878352] Entity climate.altherma does not support this service.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 198, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity climate.altherma does not support this service.

**Comment by jwillemsen** [comment]
Is this with my test branch or v2.2?

**Comment by jwillemsen** [comment]
Can you attach your json, what action does fail, setting the mode (cool/heat)?

**Comment by colseven** [comment]
@jwillemsen yes it is v2.2. the error occurs when i want to change the offset.

**Comment by jwillemsen** [comment]
Can you test my branch?

**Comment by colseven** [comment]
Yes, this one?
https://github.com/jwillemsen/daikin_residential_altherma/tree/jwi-targetleavingwatertemperature

**Comment by jwillemsen** [comment]
You can use https://github.com/speleolontra/daikin_residential_altherma/tree/externalRoomTemperature, just pushed another extension for externalRoomTemperature

**Comment by colseven** [comment]
Yes, I test directly. Should I activate my external thermostat again?

**Comment by jwillemsen** [comment]
Yes, please go back to externalThermostat again

**Comment by colseven** [comment]
So after the update, I can also see the heating temperature with the external thermostat, but I can't enter an offset yet. What can I do?
![bild 2023-03-08 um 11 50 27](https://user-images.githubusercontent.com/63189272/223693868-b6fedf06-6227-4e3c-ad09-3ad325484e7e.jpg)

**Comment by jwillemsen** [comment]
Send me the log when you change the offset and your device diagnostics, first I will merge my PR and make a v2.3 release

**Comment by jwillemsen** [comment]
Please enable debug logging of the daikin_alterma_integration

**Comment by colseven** [comment]
I can only set an offset with Climate, but then the attached error appears. I only get the target value window for service water, see attachments.
![bild 2023-03-08 um 11 55 35](https://user-images.githubusercontent.com/63189272/223695161-2af52d59-7581-4f78-a248-6b2ce6ec890e.jpg)
![bild 2023-03-08 um 11 54 30](https://user-images.githubusercontent.com/63189272/223695171-2bd636f0-f40e-49ba-8c82-3c2d963fdf58.jpg)
![bild 2023-03-08 um 11 55 43](https://user-images.githubusercontent.com/63189272/223695178-7992f5d0-26bc-4093-b65d-17cce8e65b56.jpg)
[config_entry-daikin_residential_altherma-4db054fc09c8cb180a0125196e88f37e.json.txt](https://github.com/speleolontra/daikin_residential_altherma/files/10919902/config_entry-daikin_residential_altherma-4db054fc09c8cb180a0125196e88f37e.json.txt)

Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/service.py:663 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 11:57:20 (2 occurrences) 
Last logged: 11:57:22

[546938956496] Entity climate.altherma does not support this service.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 198, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity climate.altherma does not support this service.

**Comment by colseven** [comment]
@jwillemsen 
[home-assistant_daikin_residential_altherma_2023-03-08T10-59-36.430Z.log](https://github.com/speleolontra/daikin_residential_altherma/files/10919916/home-assistant_daikin_residential_altherma_2023-03-08T10-59-36.430Z.log)

**Comment by jwillemsen** [comment]
Can you enable debug logging, the log currently doesn't say what fails, it looks to be when we try to set the value back to the altherma

**Comment by jwillemsen** [comment]
Ok, found something that could be missing, can you try the https://github.com/speleolontra/daikin_residential_altherma/tree/haattr branch?

**Comment by colseven** [comment]
@jwillemsen I recorded it.
An offset is still not displayed in climate.altherma :( It works perfectly with hot water.

[home-assistant_daikin_residential_altherma_2023-03-08T11-30-35.217Z.log](https://github.com/speleolontra/daikin_residential_altherma/files/10920114/home-assistant_daikin_residential_altherma_2023-03-08T11-30-35.217Z.log)

![bild 2023-03-08 um 12 29 22](https://user-images.githubusercontent.com/63189272/223702638-8c8c4656-d486-475d-b7c8-ff2ff600b5e4.jpg)

**Comment by jwillemsen** [comment]
Did you use my branch? I think you need a thermostat card to change the value, not sure. I don't see debug logging, did you enable that?

**Comment by jwillemsen** [comment]
Ok, did search more and more through the code, maybe the `_set` was the issue, can you pull the updated `haattr` branch, and retest, make sure debug logging is enabled, see https://github.com/speleolontra/daikin_residential_altherma#setting-the-log-level for how to do that persistent for the moment

**Comment by colseven** [comment]
@jwillemsen 
https://user-images.githubusercontent.com/63189272/223720610-489fcd32-5fd9-4833-a920-901a20299212.mov

**Comment by jwillemsen** [comment]
Ok, I think this has to do with the capabilities, can you pull the `haattr` again and restart HA with logging enabled for this integration?

**Comment by colseven** [comment]
That's it, perfect! Now it's working.
Big thanks to you.

**Comment by jwillemsen** [comment]
Great, all different versions of the altherma with differerent ways to control it require the code to be consistent everywhere, takes each time more hours than I think :-(. 

It is getting better and better with each release, a new v2.4.0 is now available, thanks for your testing!
