### ISSUE TITLE
Switch tank and boost?

### ISSUE THREAD

**Issue by Voodoomoped** [speleolontra/daikin_residential_altherma#115]
Hi,

both entities don’t work anymore:

switch.altherma_tank
switch.altherma_boost

Any chance to get them running again?
(Could be my fault)

Thanks, 
Daniel

**Comment by jwillemsen** [comment]
These moved to the water_heater entity, see the operation mode of that entity, can be on, off, and performance (which is boost)

**Comment by jaanek** [comment]
When setting water_heater to "performance" mode I am getting back `FAILED to validate set_data params: Data point powerfulMode is not writable`. Although when the switch-es were present then the boost mode worked.

DEBUG logs:
Trying to validate `on` for powerfulMode with description: {'settable': False, 'requiresReboot': False, 'value': 'off', 'values': ['off', 'on']}

**Comment by jwillemsen** [comment]
Please attach the device diagnostics

**Comment by jaanek** [comment]
Do you mean this:
![image](https://user-images.githubusercontent.com/616700/224730521-86acf6e8-91b1-4afa-80c0-5e78fb98c264.png)
Not sure this is info you asked. Or please let me know how to get those.

**Comment by jwillemsen** [comment]
see Settings/Device&Services/Daikin Residential Controller for Altherma/Download diagnostics

**Comment by pwwukpw** [comment]
Is this tge correct usage ? 
![Screenshot_20230316_202631_Home Assistant](https://user-images.githubusercontent.com/88422402/225744718-e53178dc-1743-4d53-8cf5-1cc40d3686d3.jpg)
