### ISSUE TITLE
New error with Daikin Climate after update

### ISSUE THREAD

**Issue by tgiorgio** [speleolontra/daikin_residential_altherma#117]
Before the update the integration could read the climate temperature but it can't now. Below is the error I'm getting after the update.

>Logger: homeassistant.components.climate
Source: custom_components/daikin_residential_altherma/climate.py:108
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 13:27:43 (1 occurrences)
Last logged: 13:27:43

>Error while setting up daikin_residential_altherma platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/daikin_residential_altherma/climate.py", line 83, in async_setup_entry
    async_add_entities([DaikinClimate(device)], update_before_add=True)
  File "/config/custom_components/daikin_residential_altherma/climate.py", line 108, in __init__
    tempSettable = device.getData(ATTR_TARGET_LEAVINGWATER_OFFSET)["settable"]
TypeError: 'NoneType' object is not subscriptable

**Comment by jwillemsen** [comment]
Can you attach the integration diagnostics?

**Comment by tgiorgio** [comment]
[config_entry-daikin_residential_altherma-553984f67fe520429d1c2a9bb793042a.json (1).txt](https://github.com/speleolontra/daikin_residential_altherma/files/10958185/config_entry-daikin_residential_altherma-553984f67fe520429d1c2a9bb793042a.json.1.txt)

**Comment by jwillemsen** [comment]
Can you test my branch from #119 @tgiorgio? You have a combination I haven't seen before, you have `controlMode` `externalRoomTemperature` but as `temperatureControl` only `leavingWaterTemperature` is available, but that is read only

**Comment by tgiorgio** [comment]
How do I use the branch in HA? Never had to use one.

**Comment by jwillemsen** [comment]
Do you see in hacs the externalroomtemp branch?

**Comment by tgiorgio** [comment]
Ok, I think I figured out. I replaced the files you updated in this branch and reloaded the integration and restarted HA. Now no information is being pulled as you can see in the attached image. I have downloaded the log again.

@jwillemsen 
[config_entry-daikin_residential_altherma-29a0a7976454e1aeb36c3cf3190d3430.json (1).txt](https://github.com/speleolontra/daikin_residential_altherma/files/10959212/config_entry-daikin_residential_altherma-29a0a7976454e1aeb36c3cf3190d3430.json.1.txt)
![daikin error](https://user-images.githubusercontent.com/46281112/224756236-16f47508-1fcf-48b5-84fc-4184a378d089.png)

**Comment by tgiorgio** [comment]
These are the versions I can see in HACS.
![image](https://user-images.githubusercontent.com/46281112/224756553-0d46b062-8288-44e6-9fac-d78f8c12f059.png)

**Comment by jwillemsen** [comment]
Do you have any errors in the HA log?

**Comment by tgiorgio** [comment]
I have found my unit is offline. I will get that sorted and get back to you.

**Comment by jwillemsen** [comment]
Should be fixed by v2.5.0
