### ISSUE TITLE
[Issue]: `climate.altherma` not anymore available

### ISSUE THREAD

**Issue by davidino** [speleolontra/daikin_residential_altherma#122]
Hi, 
i've recently upgrade to the latest version ( Firmware: 3.2.4 ) and since that the entity `climate.altherma` is not anymore availabe as well as the `switch.altherma_boost` and the `switch.altherma_tank`. As you can see from the picture below. 

That's the hardware i've home `BRP069A78`

![Screen Shot 2023-03-13 at 18 32 12](https://user-images.githubusercontent.com/265253/224797295-39aa87af-5251-4be7-afef-8d927ef04986.png)

I'm not sure if the issue is on my side or is that expected with the upgrade.

[config_entry-daikin_residential_altherma-697f5e725204ab33f32a71fca9d42337.json.txt](https://github.com/speleolontra/daikin_residential_altherma/files/10960716/config_entry-daikin_residential_altherma-697f5e725204ab33f32a71fca9d42337.json.txt)

**Comment by jwillemsen** [comment]
Looks same as #117 , can you test the branch?

**Comment by jwillemsen** [comment]
And #115

**Comment by davidino** [comment]
Thanks for getting back to me so quickly.
Yes i've seen #115 as i could not find `switch.altherma_boost` in the code.

For the climate should i try the other branch instead ?

**Comment by jwillemsen** [comment]
Yes, for climate please test my branch with the additional support. Boost is performance on the heater entity

**Comment by jwillemsen** [comment]
For boost/performance, click the `Heat Pump` text as shown on your image, should open a window where you can select `Operation`

**Comment by davidino** [comment]
Yeah, i've seen that.

But this change broken my automation. it would have been useful in the change_log to get a warning with `breaking changes`.

I've seems now there to automate it I have to use `Water Heater: Set operation mode` and set it to `Performance`.

```yaml
service: water_heater.set_operation_mode
data:
  operation_mode: "Performance"
target:
  entity_id: water_heater.altherma
```

correct ?

**Comment by jwillemsen** [comment]
Yes, see https://github.com/speleolontra/daikin_residential_altherma/issues/82#issuecomment-1443701072.

Sorry for breaking your automation, added a warning to the release notes. Have you been able to test the fix as proposed with #117

**Comment by davidino** [comment]
Thanks @jwillemsen 

What's the easiest way to test the different branch? 
Is there a way to download this version or do i need to copy manually the files ?

let me know thanks.

**Comment by jwillemsen** [comment]
Don't you see the test branch? I use git directly for my environment, are you using HACS?

**Comment by jwillemsen** [comment]
I created a beta v2.5.0, do you see that in HACS when you enable beta?

**Comment by davidino** [comment]
Perfect thanks.
I was able to re-download the package in the beta version ( via HACS easily).
![Screen Shot 2023-03-14 at 10 33 39](https://user-images.githubusercontent.com/265253/224974039-a7328fa6-5a40-45ff-8ae3-fc6f32bd803d.png)

Now both are working, thanks.

Is it up to me to delete the boost and the tank  ( 2nd and 3rd entity ) ?

**Comment by jwillemsen** [comment]
Ok, will create a formal v2.5.0 release, thanks for testing. I think HA keeps removed entities by default, but I am not a HA expert, just trying to get my Altherma 3 to work with HA ;-)
