### ISSUE TITLE
Tank control switches not present after update 

### ISSUE THREAD

**Issue by pwwukpw** [speleolontra/daikin_residential_altherma#128]
![Screenshot_20230316_173742_Home Assistant](https://user-images.githubusercontent.com/88422402/225706115-86281d0c-b96e-444b-b89b-fb75cc436e34.jpg)
![Screenshot_20230316_173734_Home Assistant](https://user-images.githubusercontent.com/88422402/225706122-28053ea7-c18d-423e-83a1-b8d5e95c09b9.jpg)

Any solution? 

My routine to heat off peak is failing.. 

Many thanks Peter

**Comment by jwillemsen** [comment]
They are now part of the water_heater entity

**Comment by pwwukpw** [comment]
Johnny,

Many thanks . sorry I missed the breaking change.

I've added a comment to #115 as not sure I've got the new entity control
correct.

If there is a doc I should be looking at please do let me know.

Many thanks,

Peter
