### ISSUE TITLE
sensor.altherma_leaving_water_offset not available anymore

### ISSUE THREAD

**Issue by edautz** [speleolontra/daikin_residential_altherma#129]
After upgrading from version 1.0 to 2.5.2 the sensor.altherma_leaving_water_offset is not available anymore.

Is it possible to bring it back?

**Comment by ajutine1999** [comment]
Hi! Also missing altherma_leaving_water_offset !

**Comment by jwillemsen** [comment]
Can you attach the device diagnostics and also screenshots of what you see now in the onecta app and what in HA? Until now I haven't seen a device with a leaving water offset sensoryData, some devices have a setpoint for leaving water offset, that should be controlled using the altherma thermostat itself

**Comment by edautz** [comment]
![BD51AF58-8188-4509-8D44-61C9D1CCCE79](https://user-images.githubusercontent.com/11003867/226330257-b7007779-c6e2-4b9f-90a8-07eb3cc7ed79.png)

Screenshot from HA. As you can see the Leaving Water Temperature Offset is unavailable. This since the upgrade from 1.0. 
In the ONECTA app the offset was only visible when the control mode wasn’t RoomTemperature. My standard control mode is RoomTemperature so it isn’t visible.

**Comment by jwillemsen** [comment]
As leaving water temperature offset is a way to control the target temperature this is only used when you use it as control mode for your altherma. It is a setting, not a sensor, so as you don't use the setting it is not there anymore, a cleanup compared to v1.0, in that version the sensors and settings where completely mixed and not clear, making it impossible to support the various way to control the target temperature. When you check the device diagnostics you will not find a sensor for the offset (as far as I know)

**Comment by edautz** [comment]
Ok. That explain the given situation. I will remove this bogous sensor.

**Comment by ajutine1999** [comment]
I have Control Mode = leavingWaterTemperature. I can adjust offset with up/down controls in graphical UI. 
But I can't  "Add Action" under Automations. I can choose between hvac_mode=off/heat/cool/heat_cool. 
Is it possible to add altherma_leaving_water_offset to the actions?
![Daikin_Controls](https://user-images.githubusercontent.com/128184266/226433319-6672f0cb-56ef-4936-a70d-9a6a07799224.png)
![Action_list](https://user-images.githubusercontent.com/128184266/226433434-a6d40270-ea83-437e-96a8-c86131f9cbd4.png)

**Comment by jwillemsen** [comment]
You should be able to set the leavign water offset as target temperature, the hvac modes are all defined by HA, see https://www.home-assistant.io/integrations/generic_thermostat/

**Comment by Ville-VeikkoH** [comment]
I can confirm that offset can be set by automation. I made "Smart" sensor for offset value and feed it to Altherma via automation when value changes. 

`alias: VILP SmartOffset
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.smartsaataja
condition: []
action:
  - service: climate.set_temperature
    data:
      temperature: "{{states('sensor.smartsaataja') | int }}"
    target:
      entity_id: climate.altherma
mode: single`

**Comment by ajutine1999** [comment]
Thanks! It works this way.
