### ISSUE TITLE
Detect missing energy consumption support correctly

### ISSUE THREAD

**Issue by BigFoot2020** [speleolontra/daikin_residential_altherma#135]
Currently energy consumption support is based on existanse of outdoorTemperature sensor (in daikin_api.py line 222):

`return self.getData(ATTR_OUTSIDE_TEMPERATURE) is not None`

This does not garantee correct result as device may have outdoorTemperature present, but no energy consumption data (like in my case). Instead this hsould be based on existance of "consumptionData" dataPoint. Possibly like this (as I cannot fully verify this):

`return self.getData(ATTR_ENERGY_CONSUMPTION) is not None`

**Comment by jwillemsen** [comment]
Thanks for opening this issue, will fix that tomorrow

**Comment by jwillemsen** [comment]
@BigFoot2020, this should be fixed on master, can you test that with your device? Also simplified a lot of logging so that the code is easier to maintain but also it tells in the log what device it is

**Comment by BigFoot2020** [comment]
I can confirm that this is working as expected on my device, so I will move to this integration on my "prod" HA also later today.

**Comment by jwillemsen** [comment]
Thanks, I created a v2.6.0 release, see https://github.com/speleolontra/daikin_residential_altherma/releases/tag/v2.6.0 which contains the latest changes
