### ISSUE TITLE
Update About/Description of this repository to reflect support for BRP069A62

### ISSUE THREAD

**Issue by BigFoot2020** [speleolontra/daikin_residential_altherma#137]
Current description: Home Assistant Integration specific for BRP069A78 Heat Pump Model, via Daikin App Onecta.
This is not correct anymore as BRP069A62 (and most likely also BRP069A61 as this is almost same device type) is also working.

**Comment by jwillemsen** [comment]
@speleolontra Can you update the description as shown by github for this project, it seems I can't update it.

**Comment by sraka1** [comment]
@jwillemsen do you not have permissions to do it yourself? Given that @speleolontra seems to be inactive, could/should you fork the project to become the owner (given that it seems like you're the active maintainer)? 

Also, great job and thanks for this.

**Comment by speleolontra** [comment]
Now readme seems to be updated without any reference of heat pump model. I can't check if this run correctly also for other models than mine.
@jwillemsen  have you all permission that you need?
Thanks for your job.

**Comment by BigFoot2020** [comment]
Issue is not about readme (although it is good to keep that also updated, but about the descriptions of repo:
![image](https://github.com/speleolontra/daikin_residential_altherma/assets/83656126/3892d85b-94f6-44ab-b3c6-7622c74e727e)
You should have a little cogwheel next to "About" where it can be changed:
![image](https://github.com/speleolontra/daikin_residential_altherma/assets/83656126/91e75a2a-6158-4b95-b9c6-2f724a5fa03e)

**Comment by speleolontra** [comment]
Updated both.

**Comment by jwillemsen** [comment]
I don't have the cogwheel next to "About", so I can't change the description. @sraka1 I am personally not in favor of forking projects in order to create a new version. @speleolontra has given me several permissions, so I can do a lot of things in this repo.

**Comment by jwillemsen** [comment]
Thanks for updating them @speleolontra
