### ISSUE TITLE
Values for generated heat (heating and warm water)

### ISSUE THREAD

**Issue by madmas** [speleolontra/daikin_residential_altherma#140]
Hi @speleolontra and @jwillemsen,
thanks a lot for this project and all the effort you put into it!

I got it working on a Daikin Altherma EHSXB08P50EF with an BRP069A78.

I can see the current temperature states as well as the consuption values (Today, Weekly, Yearly).

What I do miss tho are the values für the energy created. Do you know if it is possible to get them? (As i can see them on the Altherma display itself) and I´d love to use them to caluclate the operation efficiency.

And one question out of curiosity: Do you fetch the values via cloud or to you need just the token from the cloud to use it on the internal API of the Alterma?

thanks a  lot 
 Markus

**Comment by jwillemsen** [comment]
As far as I know these values are not exported by daikin to the cloud (values are fetched from the cloud), see the integration diagnostics (see settings/devices&services/3 dots under the integration) for the export of all data. Only data you find in the json you can download there can be shown.

**Comment by madmas** [comment]
Okay, thanks a lot! I think I will contact Daikin and ask why now all data the Alterma has available is shown in the app...

**Comment by jwillemsen** [comment]
When the data is shown in the onecta app it should also be in the json, maybe attach your json here (after removing all keys)

**Comment by madmas** [comment]
checked and didnt find the data in the json, will update here if i get some useful reply from Daikin
