### ISSUE TITLE
Altherma Tank Temperature refresh interval

### ISSUE THREAD

**Issue by razorsec-art** [speleolontra/daikin_residential_altherma#141]
First of all thank you for your excellent work! Would it be possible to have a configuration parameter for the Altherma Tank Temperature update interval? Currently it seems that it is 15min. Thank you 🙏

**Comment by jwillemsen** [comment]
The integration just polls the daikin cloud, limited to 2 seconds (see https://github.com/speleolontra/daikin_residential_altherma/blob/04f39a50a3484e1a64a6a24f46b6e437ca93b5f2/custom_components/daikin_residential_altherma/__init__.py#L29). Please check the device diagnostics, at the bottom of the json you can find `lastUpdateReceived`, that is the time we got the data from daikin.

Please compare the data with the onecta app, very likely your altherma only sends the data to the cloud each 15 minutes, we can't do anything about that, contact daikin to let them publish more often.

**Comment by jwillemsen** [comment]
As far as I know there is nothing we can change at our side

**Comment by razorsec-art** [comment]
Sorry for the late reply. Thank you very much. It seems indeed a daikin limitation because the lastUpdateReceived is always presented in 15min intervals. I think it is true for all other device entities. I will ask daikin to change then. Maybe the “2s” interval is an overkill?  :) thank you very very much and congratulations for your excelent project!

**Comment by razorsec-art** [comment]
Understood 👌🏻👌🏻👌🏻
