### ISSUE TITLE
[Help Request]: Create a telegraf plugin to export data

### ISSUE THREAD

**Issue by sammort** [speleolontra/daikin_residential_altherma#143]
Hi there, 

This is not at all an issue with your plugin and is more a request for some guidance. I have recently had an Altherma 3 heat pump (EDLA06E2V3) installed with the BRP069A78 gateway. I've been looking at how I might be able to export the data from Daikin and was obviously disappointed to find the closed API 😞. So after some hunting around I was happy to see this HA implementation which connects with the API and is able to access the data I can see in the Onecta app.

I'm hoping to put together a plugin for telegraf so that I'll be able to visualise the data in Grafana, similar to this [plugin that gets data from the Philips Hue Bridge](https://github.com/hdecarne-github/huebridge-telegraf-plugin). My request is this; I've had a look throught the codebase and finding it hard to understand where to start. I imagine all I need to 'borrow' from this repo is:
- authentication flow
- export data

Add I can remove any parts that are related to HA. I'd really appreciate if it would be possible to point to the parts of the codebase that handle the authentication, data export from Daikin's API and potentially any pointers/tips on dev-ing locally against the Daikin API.

Cheers and here's hoping the rumours of a Daikin EU open API do come to fruition.

**Comment by jwillemsen** [comment]
I am not the original author, but I think you should check https://github.com/speleolontra/daikin_residential_altherma/blob/master/custom_components/daikin_residential_altherma/daikin_api.py first. Look at authentication and the ability to retrieve the json with all data, when you have that, see the other classes how that data is used.
