### ISSUE TITLE
[Issue]: Consumption data missing

### ISSUE THREAD

**Issue by riksarchen** [speleolontra/daikin_residential_altherma#150]
For me, consumption data is missing. Tried to reload and restart HA without any progress. 

As I understand this data should be available? 

I have Altherma 3 Geo wired with Ethernetcable. (A61)

**Comment by jwillemsen** [comment]
Please attach the device diagnostics and the HA logs

**Comment by jwillemsen** [comment]
Closing, without the requested diagnostics and screenshots we can't determine what exactly is happening
