### ISSUE TITLE
Altherma Leaving Water Offset entity

### ISSUE THREAD

**Issue by arnohulle** [speleolontra/daikin_residential_altherma#151]
Hi,

since the Update, the entity Altherma Leaving Water Offset is missing. Is there another way to edit the Offset-Value ?

thx for respond

Arno
![Altherma offset](https://github.com/speleolontra/daikin_residential_altherma/assets/97704470/e86f374f-002c-4bfc-9f28-7f298e2a8b61)

**Comment by jwillemsen** [comment]
Please attach the device diagnostics (see Settings/Device&Services/Daikin Residential Controller for Altherma/Download diagnostics). Remove all tokens and passwords from the device diagnostics before attaching it to this issue.

When you have an issue about missing or incorrect data compared to the Onecta app please attach also some screenshots of the Onecta app. Please enable the debug log as described in the readme.md and attach the log also to this issue.

**Comment by jwillemsen** [comment]
See also #129

**Comment by arnohulle** [comment]
Thx Von: Johnny WillemsenGesendet: Freitag, 19. Mai 2023 09:59An: speleolontra/daikin_residential_althermaCc: arnohulle; AuthorBetreff: Re: [speleolontra/daikin_residential_altherma] Altherma Leaving Water Offset entity (Issue #151) See also #129—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
