### ISSUE TITLE
[Question]: Slider for adjustment of hot water tank temperature

### ISSUE THREAD

**Issue by heikone** [speleolontra/daikin_residential_altherma#158]
Good Morning,

I've got a question concerning dashboard presentation of the water tank temperature setting.
At the moment, I'm using an entity card to show the hot water tank on my dashboard like this:

<img width="327" alt="Bildschirmfoto 2023-06-17 um 06 42 50" src="https://github.com/speleolontra/daikin_residential_altherma/assets/42500448/c55469c3-75db-48f5-9388-2ca3dfa4c7f7">

To change the temperature, you need to click on this and the adjust by the higher/lower button:

<img width="592" alt="Bildschirmfoto 2023-06-17 um 06 46 15" src="https://github.com/speleolontra/daikin_residential_altherma/assets/42500448/a76d1f5f-763d-49c9-ac4b-fbf32adbb0a3">

If tried, but I was not able to bring this temperature setting directly to dashboard by showing a slider like this:

<img width="336" alt="Bildschirmfoto 2023-06-17 um 06 48 47" src="https://github.com/speleolontra/daikin_residential_altherma/assets/42500448/23e488b6-d054-4d3e-af93-53b174c09b78">

**Could anybody advice, how to get the attribute "temperature" from entity "water_heater.altherma" to a an entity card with slider?**

Greetings,
Heiko

**Comment by jwillemsen** [comment]
I have no idea, don't really use the UI much. Maybe there is a HA forum for the cards where you can ask?

**Comment by habitoti** [comment]
This is not the water tank temperature at all. It‘s the heating offset temperature. I don‘t think that you can control the water tank target temperature via this plugin (nor with Onecta app). Would be great, though, if you coild. Or at least switch to Eco or Comfort to force water heating.

**Comment by jwillemsen** [comment]
Home assistant 2023.9.0 has new cards for the water heater entity, see https://www.home-assistant.io/blog/2023/09/06/release-20239/#new-climate-humidifier-and-water-heater-entity-dialogs

**Comment by heikone** [comment]
Great looking card.
But does anybody know how to update the card?
HA did the upgrade to 2023.9.0 this morning.
The card still stays the same (left part of picture), but when I click on it, the new design appears (right part of picture).
![Bildschirmfoto 2023-09-07 um 08 19 51](https://github.com/speleolontra/daikin_residential_altherma/assets/42500448/e324ca0b-33ab-4e1c-9e72-24899e271784)

The current code definition of the card looks simply like this:
`type: thermostat`
`entity: climate.altherma`
`name: Mandoka Wohnzimmer`

Any advice would be helpful.
Heiko
