### ISSUE TITLE
[Issue]: Integration no longer works after upgrading HA Core to 2023.7.1 / OS10.3

### ISSUE THREAD

**Issue by SolarEdgeUser** [speleolontra/daikin_residential_altherma#159]
After updating to Core 2023.7.1 / OS 10.3, this integration no longer works. I was able to download some form of log, which I have attached to this issue. 

The Altherma itself IS online. I can see it via the Onecta app, so the Altherma itself is online. 

First time logging an issue, so I don't know what else is relevant. If you have any questions, please ask. 

[home-assistant_daikin_residential_altherma_2023-07-09T09-46-29.509Z.log](https://github.com/speleolontra/daikin_residential_altherma/files/11994879/home-assistant_daikin_residential_altherma_2023-07-09T09-46-29.509Z.log)

**Comment by jwillemsen** [comment]
Have you upgrades to the latest version of this integration?

**Comment by SolarEdgeUser** [comment]
> Have you upgraded to the latest version of this integration?

No, I had not. Thank you for pointing out the (very) obvious. I have just upgraded, and it works fine now.
