### ISSUE TITLE
Sensors not updating

### ISSUE THREAD

**Issue by MRazgunas** [speleolontra/daikin_residential_altherma#16]
Hello,

Few days I got Daikin installed and I have manage to add integration to HA, but it looks like all sensor values are not updated, unless I restart HA, after restart value updates for one time, but it stays constant. All values in climate integration are updated.

![image](https://user-images.githubusercontent.com/5657918/151229092-38c66322-59b6-4dd2-ad5b-52f353635da6.png)

From graph you can see that Altherma Leaving Water Temperature is staying constant, but Altherma current temperature is changing. 

I tried to debugging and what I was able to find out is that all parameters from climate.py are updating, and from sensor.py are not updating. Sensor are initialized during startup, but sensor.py async_update() is never called.

I'm new to HA development, so maybe someone could suggest some places which I could look into.

**Comment by jwillemsen** [comment]
I am also new to HA development, does the log say anything? I have made some more changes and cleanup to the code, does all seem to work correctly on my side.

**Comment by MRazgunas** [comment]
Ok, I have made breakthrough, look like issue is that my hot water tank is not configured yet (waiting for installers to come and finish it), and it causes sensors to not update:
```
2022-01-27 11:00:22 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform daikin_residential_altherma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 613, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 748, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 511, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/daikin_residential_altherma/sensor.py", line 194, in state
    return round(self._device.energy_consumption_tank("heating", self._period), 3)
  File "/config/custom_components/daikin_residential_altherma/daikin_base.py", line 412, in energy_consumption_tank
    energy_data = [
TypeError: 'NoneType' object is not iterable
```

I have commented out Tank energy sensor from async_setup_entry() in sensor.py and it seems to have started working.

Will create MR after work to fix this issue by checking if tank energy is available before creating Tank Energy sensor.

**Comment by jwillemsen** [comment]
Ok, sounds logical, without a tank the sensor should not be there. Be aware of PR #17, makes some changes to the sensors, not that we have a lot of merge conflicts later

**Comment by jwillemsen** [comment]
At some point I want to revisit the hot water tank support, see https://github.com/speleolontra/daikin_residential_altherma/issues/14

**Comment by jwillemsen** [comment]
@MRazgunas could you maybe attach your daikin_data.json to this issue, would be useful for the future to have that file to check for the returned JSON in case there is no tank

**Comment by MRazgunas** [comment]
[daikin_data.json.txt](https://github.com/speleolontra/daikin_residential_altherma/files/7950408/daikin_data.json.txt)

Attaching json where no hot water tank is available

**Comment by jwillemsen** [comment]
Thanks! I am making some quick changes for you to test, do I see correctly you also don't have cooling?

**Comment by jwillemsen** [comment]
Can you try a branch from my fork, see https://github.com/jwillemsen/daikin_residential_altherma/tree/jwi-nocoolingtemp

**Comment by jwillemsen** [comment]
Can you retest with master?

**Comment by MRazgunas** [comment]
Tested with master, seems to be working. I got hot water tank configured since then, and it seems to be working fine
