### ISSUE TITLE
[Issue]: no sensor data

### ISSUE THREAD

**Issue by cleversmart** [speleolontra/daikin_residential_altherma#162]
Home Assistant 2023.6.3
Logger: homeassistant.helpers.entity
Source: custom_components/daikin_residential_altherma/daikin_api.py:518
Integration: Daikin Residential Controller for Altherma (documentation, issues)
First occurred: 10. Juli 2023 um 19:12:53 (4 occurrences)
Last logged: 10. Juli 2023 um 21:14:53

```
Update for water_heater.altherma fails
Update for sensor.altherma_leaving_water_temperature fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
    await self.async_update()
  File "/config/custom_components/daikin_residential_altherma/water_heater.py", line 199, in async_update
    await self._device.api.async_update()
  File "/config/custom_components/daikin_residential_altherma/daikin_api.py", line 518, in async_update
    if dev_data["id"] in self.hass.data[DOMAIN][DAIKIN_DEVICES]:
       ~~~~~~~~^^^^^^
TypeError: string indices must be integers, not 'str'
```

**Comment by jwillemsen** [comment]
I haven't seen this error before, did it work before, did you change anything? Can you attach the device diagnostics as explained when you create a new issue?

**Comment by cleversmart** [comment]
{
  "home_assistant": {
    "installation_type": "Home Assistant Container",
    "version": "2023.6.3",
    "dev": false,
    "hassio": false,
    "virtualenv": false,
    "python_version": "3.11.4",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Vienna",
    "os_name": "Linux",
    "os_version": "5.19.0-46-generic",
    "run_as_root": true
  },
  "custom_components": {
    "daikin_residential_altherma": {
      "version": "2.8.0",
      "requirements": [
        "oic==1.6.0"
      ]
    }
  },
  "integration_manifest": {
    "domain": "daikin_residential_altherma",
    "name": "Daikin Residential Controller for Altherma",
    "codeowners": [
      "@speleolontra",
      "@jwillemsen"
    ],
    "config_flow": true,
    "dependencies": [],
    "documentation": "https://github.com/speleolontra/daikin_residential_altherma",
    "iot_class": "cloud_polling",
    "issue_tracker": "https://github.com/speleolontra/daikin_residential_altherma/issues",
    "requirements": [
      "oic==1.6.0"
    ],
    "version": "2.8.0",
    "is_built_in": false
  },
  "data": {
    "device": {
      "__type": "<class 'homeassistant.helpers.device_registry.DeviceEntry'>",
      "repr": "DeviceEntry(area_id='system', config_entries={'4c554cfb5a662f4f3af52bfea6b91599'}, configuration_url=None, connections={('mac', 'x:x:x:x:x:x:x')}, disabled_by=None, entry_type=None, hw_version=None, id='9b6d9a199080e9b45884844b772b69e2', identifiers={('daikin_residential_altherma', '9f8c0116-8de3-414d-a048-57cf4cc75c20')}, manufacturer='Daikin', model='BRP069A78', name_by_user=None, name='', suggested_area=None, sw_version='3.2.5', via_device_id=None, is_new=False)"
    },
    "device_json_data": {
      "_id": "9f8c0116-8de3-414d-a048-57cf4cc75c20",
      "deviceModel": "Altherma",
      "type": "heating-wlan",
      "isCloudConnectionUp": {
        "settable": false,
        "value": true
      },
      "managementPoints": [
        {
          "embeddedId": "gateway",
          "managementPointType": "gateway",
          "managementPointCategory": "secondary",
          "firmwareVersion": {
            "settable": false,
            "value": "3.2.5",
            "maxLength": 8
          },
          "ipAddress": {
            "settable": false,
            "value": "x.x.x.x",
            "maxLength": 15
          },
          "iconId": {
            "settable": true,
            "requiresReboot": false,
            "value": 3
          },
          "isFirmwareUpdateSupported": {
            "settable": false,
            "requiresReboot": false,
            "value": true
          },
          "macAddress": {
            "settable": false,
            "value": "2c:3b:70:b9:dc:99",
            "maxLength": 17
          },
          "modelInfo": {
            "settable": false,
            "value": "BRP069A78",
            "maxLength": 9
          },
          "name": {
            "settable": true,
            "requiresReboot": false,
            "value": "Gateway",
            "maxLength": 63
          },
          "ssid": {
            "settable": false,
            "requiresReboot": false,
            "value": "daikin-ap",
            "maxLength": 9
          },
          "serialNumber": {
            "settable": false,
            "value": "0213708",
            "maxLength": 16
          },
          "wifiConnectionSSID": {
            "settable": false,
            "requiresReboot": false,
            "value": "xxxx",
            "maxLength": 32
          },
          "wifiConnectionStrength": {
            "settable": false,
            "requiresReboot": false,
            "value": -69,
            "maxValue": 0,
            "minValue": -90,
            "stepValue": 1
          }
        },
        {
          "embeddedId": "climateControlMainZone",
          "managementPointType": "climateControl",
          "managementPointCategory": "primary",
          "managementPointSubType": "mainZone",
          "consumptionData": {
            "settable": false,
            "requiresReboot": false,
            "ref": "#consumptionData",
            "value": {
              "electrical": {
                "heating": {
                  "d": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                  ],
                  "w": [
                    null,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null
                  ],
                  "m": [
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null
                  ]
                }
              }
            }
          },
          "controlMode": {
            "settable": false,
            "requiresReboot": false,
            "value": "roomTemperature",
            "values": [
              "leavingWaterTemperature",
              "externalRoomTemperature",
              "roomTemperature"
            ]
          },
          "errorCode": {
            "settable": false,
            "requiresReboot": false,
            "value": "",
            "maxLength": 16
          },
          "holidayMode": {
            "settable": true,
            "requiresReboot": false,
            "ref": "#holidayMode",
            "value": {
              "enabled": false,
              "startDate": "2017-01-01",
              "endDate": "2017-01-01"
            }
          },
          "iconId": {
            "settable": true,
            "requiresReboot": false,
            "value": 8
          },
          "isHolidayModeActive": {
            "settable": false,
            "requiresReboot": false,
            "value": false
          },
          "isInEmergencyState": {
            "settable": false,
            "requiresReboot": false,
            "value": false
          },
          "isInErrorState": {
            "settable": false,
            "requiresReboot": false,
            "value": false
          },
          "isInInstallerState": {
            "settable": false,
            "requiresReboot": false,
            "value": false
          },
          "isInWarningState": {
            "settable": false,
            "requiresReboot": false,
            "value": false
          },
          "name": {
            "settable": true,
            "requiresReboot": false,
            "value": "",
            "maxLength": 63
          },
          "onOffMode": {
            "settable": true,
            "requiresReboot": false,
            "value": "on",
            "values": [
              "off",
              "on"
            ]
          },
          "operationMode": {
            "settable": false,
            "requiresReboot": false,
            "value": "heating",
            "values": [
              "heating"
            ]
          },
          "schedule": {
            "settable": true,
            "ref": "#schedule",
            "value": {
              "currentMode": {
                "settable": false,
                "value": "heating",
                "values": [
                  "heating"
                ]
              },
              "modes": {
                "heating": {
                  "enabled": {
                    "settable": true,
                    "requiresReboot": false,
                    "value": true
                  },
                  "currentSchedule": {
                    "settable": true,
                    "requiresReboot": false,
                    "value": "scheduleHeatingRT1",
                    "values": [
                      "scheduleHeatingRT1",
                      "scheduleHeatingRT2",
                      "scheduleHeatingRT3"
                    ]
                  },
                  "meta": {
                    "minIntervalBetweenActions": "00:10:00",
                    "maxSchedules": 3,
                    "maxActionsPerActionPeriod": 6,
                    "consecutiveActionsAllowed": true,
                    "actionTypes": {
                      "roomTemperature": {
                        "settable": false,
                        "maxValue": 30,
                        "minValue": 12,
                        "stepValue": 1
                      }
                    }
                  },
                  "schedules": {
                    "scheduleHeatingRT1": {
                      "settable": true,
                      "name": {
                        "settable": true,
                        "requiresReboot": false,
                        "value": "User defined 1"
                      },
                      "meta": {
                        "isReadOnly": false,
                        "actionPeriods": [
                          "monday",
                          "tuesday",
                          "wednesday",
                          "thursday",
                          "friday",
                          "saturday",
                          "sunday"
                        ]
                      },
                      "actions": {}
                    },
                    "scheduleHeatingRT2": {
                      "settable": true,
                      "name": {
                        "settable": true,
                        "requiresReboot": false,
                        "value": "User defined 2"
                      },
                      "meta": {
                        "isReadOnly": false,
                        "actionPeriods": [
                          "monday",
                          "tuesday",
                          "wednesday",
                          "thursday",
                          "friday",
                          "saturday",
                          "sunday"
                        ]
                      },
                      "actions": {}
                    },
                    "scheduleHeatingRT3": {
                      "settable": true,
                      "name": {
                        "settable": true,
                        "requiresReboot": false,
                        "value": "User defined 3"
                      },
                      "meta": {
                        "isReadOnly": false,
                        "actionPeriods": [
                          "monday",
                          "tuesday",
                          "wednesday",
                          "thursday",
                          "friday",
                          "saturday",
                          "sunday"
                        ]
                      },
                      "actions": {}
                    }
                  }
                }
              }
            }
          },
          "sensoryData": {
            "settable": false,
            "ref": "#sensoryData",
            "value": {
              "roomTemperature": {
                "settable": false,
                "requiresReboot": false,
                "value": 27.2,
                "maxValue": 127,
                "minValue": -127,
                "stepValue": 0.1
              },
              "outdoorTemperature": {
                "settable": false,
                "requiresReboot": false,
                "value": 25,
                "maxValue": 127,
                "minValue": -127,
                "stepValue": 1
              },
              "leavingWaterTemperature": {
                "settable": false,
                "requiresReboot": false,
                "value": 26,
                "maxValue": 127,
                "minValue": -127,
                "stepValue": 1
              }
            }
          },
          "setpointMode": {
            "settable": false,
            "requiresReboot": true,
            "value": "weatherDependent",
            "values": [
              "fixed",
              "weatherDependent"
            ]
          },
          "temperatureControl": {
            "settable": true,
            "ref": "#temperatureControl",
            "value": {
              "operationModes": {
                "auto": {
                  "setpoints": {
                    "roomTemperature": {
                      "settable": true,
                      "requiresReboot": false,
                      "value": 20,
                      "maxValue": 30,
                      "minValue": 12,
                      "stepValue": 0.5
                    },
                    "leavingWaterOffset": {
                      "settable": true,
                      "requiresReboot": false,
                      "value": 0,
                      "maxValue": 10,
                      "minValue": -10,
                      "stepValue": 1
                    }
                  }
                },
                "heating": {
                  "setpoints": {
                    "roomTemperature": {
                      "settable": true,
                      "requiresReboot": false,
                      "value": 20,
                      "maxValue": 30,
                      "minValue": 12,
                      "stepValue": 0.5
                    },
                    "leavingWaterOffset": {
                      "settable": true,
                      "requiresReboot": false,
                      "value": 0,
                      "maxValue": 10,
                      "minValue": -10,
                      "stepValue": 1
                    }
                  }
                },
                "cooling": {
                  "setpoints": {}
                }
              }
            }
          }
        },
        {
          "embeddedId": "domesticHotWaterTank",
          "managementPointType": "domesticHotWaterTank",
          "managementPointCategory": "primary",
          "consumptionData": {
            "settable": false,
            "requiresReboot": false,
            "ref": "#consumptionData",
            "value": {
              "electrical": {
                "heating": {
                  "d": [
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    2,
                    0,
                    0,
                    0,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null
                  ],
                  "w": [
                    null,
                    3,
                    3,
                    1,
                    3,
                    2,
                    1,
                    3,
                    0,
                    null,
                    null,
                    null,
                    null,
                    null
                  ],
                  "m": [
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    16,
                    null,
                    null,
                    null,
                    null,
                    null
                  ]
                }
              }
            }
          },
          "errorCode": {
            "settable": false,
            "requiresReboot": false,
            "value": "",
            "maxLength": 16
          },
          "heatupMode": {
            "settable": false,
            "requiresReboot": true,
            "value": "reheatOnly",
            "values": [
              "reheatOnly",
              "reheatSchedule",
              "scheduleOnly"
            ]
          },
          "iconId": {
            "settable": true,
            "requiresReboot": false,
            "value": 9
          },
          "isHolidayModeActive": {
            "settable": false,
            "requiresReboot": false,
            "value": false
          },
          "isInEmergencyState": {
            "settable": false,
            "requiresReboot": false,
            "value": false
          },
          "isInErrorState": {
            "settable": false,
            "requiresReboot": false,
            "value": false
          },
          "isInInstallerState": {
            "settable": false,
            "requiresReboot": false,
            "value": false
          },
          "isInWarningState": {
            "settable": false,
            "requiresReboot": false,
            "value": false
          },
          "isPowerfulModeActive": {
            "settable": false,
            "requiresReboot": false,
            "value": false
          },
          "name": {
            "settable": true,
            "requiresReboot": false,
            "value": "",
            "maxLength": 63
          },
          "onOffMode": {
            "settable": true,
            "requiresReboot": false,
            "value": "on",
            "values": [
              "off",
              "on"
            ]
          },
          "operationMode": {
            "settable": false,
            "value": "heating",
            "values": [
              "heating"
            ]
          },
          "powerfulMode": {
            "settable": true,
            "requiresReboot": false,
            "value": "off",
            "values": [
              "off",
              "on"
            ]
          },
          "sensoryData": {
            "settable": false,
            "ref": "#sensoryData",
            "value": {
              "tankTemperature": {
                "settable": false,
                "requiresReboot": false,
                "value": 46,
                "maxValue": 127,
                "minValue": -127,
                "stepValue": 1
              }
            }
          },
          "setpointMode": {
            "settable": false,
            "requiresReboot": false,
            "value": "fixed",
            "values": [
              "fixed",
              "weatherDependent"
            ]
          },
          "temperatureControl": {
            "settable": true,
            "ref": "#temperatureControl",
            "value": {
              "operationModes": {
                "heating": {
                  "setpoints": {
                    "domesticHotWaterTemperature": {
                      "settable": true,
                      "requiresReboot": false,
                      "value": 48,
                      "maxValue": 60,
                      "minValue": 30,
                      "stepValue": 1
                    }
                  }
                }
              }
            }
          }
        },
        {
          "embeddedId": "indoorUnitHydro",
          "managementPointType": "indoorUnitHydro",
          "managementPointCategory": "secondary",
          "eepromVersion": {
            "settable": false,
            "requiresReboot": false,
            "value": "3608726-66D",
            "maxLength": 16
          },
          "iconId": {
            "settable": true,
            "requiresReboot": false,
            "value": 4
          },
          "modelInfo": {
            "settable": false,
            "requiresReboot": false,
            "value": "EHVH08S23EJ9W",
            "maxLength": 16
          },
          "name": {
            "settable": true,
            "requiresReboot": false,
            "value": "Indoor Hydro Unit",
            "maxLength": 63
          },
          "softwareVersion": {
            "settable": false,
            "requiresReboot": false,
            "value": "0223",
            "maxLength": 16
          }
        },
        {
          "embeddedId": "outdoorUnit",
          "managementPointType": "outdoorUnit",
          "managementPointCategory": "secondary",
          "iconId": {
            "settable": true,
            "requiresReboot": false,
            "value": 5
          },
          "name": {
            "settable": true,
            "requiresReboot": false,
            "value": "Outdoor Unit",
            "maxLength": 63
          },
          "softwareVersion": {
            "settable": false,
            "requiresReboot": false,
            "value": "FFFF",
            "maxLength": 16
          }
        },
        {
          "embeddedId": "userInterface",
          "managementPointType": "userInterface",
          "managementPointCategory": "secondary",
          "dateTime": {
            "settable": false,
            "requiresReboot": false,
            "value": "2023-07-11T04:36:48"
          },
          "firmwareVersion": {
            "settable": false,
            "requiresReboot": false,
            "deprecated": "DEPRECATED",
            "value": "7.1.0",
            "maxLength": 16
          },
          "iconId": {
            "settable": true,
            "requiresReboot": false,
            "value": 6
          },
          "miconId": {
            "settable": false,
            "requiresReboot": false,
            "value": "20010E07",
            "maxLength": 16
          },
          "modelInfo": {
            "settable": false,
            "requiresReboot": false,
            "value": "EHVH08S23EJ9W",
            "maxLength": 16
          },
          "name": {
            "settable": true,
            "requiresReboot": false,
            "value": "User Interface",
            "maxLength": 63
          },
          "softwareVersion": {
            "settable": false,
            "requiresReboot": false,
            "value": "7.1.0",
            "maxLength": 16
          }
        }
      ],
      "embeddedId": "8c413ef6-0693-43c1-bf87-9e1455461114",
      "timestamp": "2023-07-11T07:07:47.13Z",
      "id": "9f8c0116-8de3-414d-a048-57cf4cc75c20"
    }
  }
}

**Comment by cleversmart** [comment]
Yes it worked for 3-4 days, then the sensor datas are lost in the recorder. The sensor "Altherma Daily Heat Tank Energy Consumption" reported me 1 kW, but the App from Daikin said 3 kW

**Comment by jwillemsen** [comment]
Please attach the json as file, much easier

**Comment by cleversmart** [comment]
[daikin_residential_altherma-4c554cfb5a662f4f3af52bfea6b91599--9b6d9a199080e9b45884844b772b69e2.json.txt](https://github.com/speleolontra/daikin_residential_altherma/files/12011873/daikin_residential_altherma-4c554cfb5a662f4f3af52bfea6b91599--9b6d9a199080e9b45884844b772b69e2.json.txt)

**Comment by jwillemsen** [comment]
Looks the data is not correct, no idea why, you have `device_json_data` but it should be `json_data`. Have you tried to restart HA, when that doesn't help, remove this integration, restart HA, install this integration again. Let me know if that works

**Comment by jwillemsen** [comment]
Have you tried to update HA and the latest version of this integration?

**Comment by jwillemsen** [comment]
Have you tried to restart HA?

**Comment by jwillemsen** [comment]
Can you retest using https://github.com/jwillemsen/daikin_residential_altherma/releases/tag/v3.0.1?

**Comment by jwillemsen** [comment]
Or in the onect app go to settings/diagnostics and add the zip file here
