### ISSUE TITLE
Just an FYI of new App/API

### ISSUE THREAD

**Issue by neildsb** [speleolontra/daikin_residential_altherma#163]
linked to https://github.com/speleolontra/daikin_residential_altherma/issues/1

I requested a road map from Daikin UK, and received - 

'I contacted the product manager and whilst we are unable to provide exact details, they advised a new app called “Daikin Cloud Service Residential” will be launched shortly and it will provide a lot of the functions you have requested below.

Unfortunately they couldn’t provide time scales on when it will be launched.'

hope this helps.?

**Comment by jwillemsen** [comment]
Thanks, hopefully they provide the functionality soon, but also make it an open API so that we can use it.

**Comment by heisenberg2980** [comment]
@neildsb have you received any update about this new app? I found this link about Daikin Cloud Service Residential but it doesn´t mention if it´s already available or not: https://www.daikin.eu/en_us/service/operate_maintenance_repairs/remote_monitoring/daikin-cloud-service-residential.html
I also found this other link to register for DAIKIN Control Cloud Services, not sure if it´s the same or something different: https://www.daikin-control.com/login
