### ISSUE TITLE
[Issue]: daily energy consumption not reported

### ISSUE THREAD

**Issue by drungly** [speleolontra/daikin_residential_altherma#165]
Daily energy consumption is reported as not being supported, but when inspecting the diagnostic logfile from Home Assistant I do see a consumption data entry. Unsure why the value is listed as not being supported. I have the BRP069A62 connected to the heat pump, and not the BRP069A61. The heat pump is the Daikin Altherma 3 R F (ehvx08s23dj6v).

[logfile_20230729.txt](https://github.com/speleolontra/daikin_residential_altherma/files/12207944/logfile_20230729.txt)
[diagnostic_log.txt](https://github.com/speleolontra/daikin_residential_altherma/files/12207949/diagnostic_log.txt)

**Comment by jwillemsen** [comment]
I see that your data is slightly different as mine, for the consumption there is a `"unit": "kWh"` added, but that shouldn't be a real problem. Maybe you can add some additional logging/tracing to the code and see what happens? My time is very limited this vacation period

**Comment by drungly** [comment]
Thanks for the response! I've tried looking around a bit, but unfortunately it's unclear to me why heating energy consumption is listed as not being supported. I was able to confirm that device.getDataEC(ATTR_ENERGY_CONSUMPTION_TANK, "heating", period) in sensor.py (line 129) is "None". I'll try to look a bit deeper, but Python isn't my strongest suit.

**Comment by crewone** [comment]
I can report the exact same issue

**Comment by petosiso** [comment]
Daily energy consumption (and many others) has stopped logging since the last HA update 2 days ago. My unit: BRP069A78. The only thing that works is the climate control .If you need more information (logs), let me know.

**Comment by jwillemsen** [comment]
Please upgrade to v2.8.1 of this integration, see https://github.com/speleolontra/daikin_residential_altherma/issues/187

**Comment by jwillemsen** [comment]
Some work in progress at https://github.com/jwillemsen/daikin_residential_altherma/tree/jwi-energyconsumption2, refactoring the energy sensors

**Comment by youdontknowmu** [comment]
Hello there and really many thanks for the great great work here !!

I seem to have the same problem, I only see 27 entities from the integration, and none are energy sensors.
I have a BRP069A62 and version 2.8.2 of your integration.

Is there anything that can be done ?

Thanks !

**Comment by jwillemsen** [comment]
See the branch in my previous comment, when I have spare time I am refactoring the code to support more models, just be patient or sponsor me to raise the priority ;-)

**Comment by jwillemsen** [comment]
Can you checkout https://github.com/speleolontra/daikin_residential_altherma/pull/198 locally and rerun with debug enabled (see readme) and attach your log and device diagnostics here

**Comment by jwillemsen** [comment]
@drungly  see my previous comment, I need an updated log to know which direction I have to move with the code

**Comment by drungly** [comment]
Here you go!

[diagnostic_log.txt](https://github.com/speleolontra/daikin_residential_altherma/files/13551271/diagnostic_log.txt)
[logfile_20231204.log](https://github.com/speleolontra/daikin_residential_altherma/files/13551272/logfile_20231204.log)

**Comment by jwillemsen** [comment]
Thanks, I will compare this with my device and rework the code to try to get your device supported, will let you know when I have something to retest

**Comment by jwillemsen** [comment]
See https://github.com/jwillemsen/daikin_residential_altherma/tree/jwi-consumptiondatalogging for a test branch that should provide energy usage, can you try this and let me know the results including log

**Comment by jwillemsen** [comment]
See https://github.com/jwillemsen/daikin_residential_altherma/releases/tag/v3.0.0 for a release including the necessary changes for this issue

**Comment by drungly** [comment]
Thanks! Tested it last night, and everything seems to be working perfectly. The leaving water temperature offset control is a nice addition! Many thanks again for your hard work, and happy holidays!
