### ISSUE TITLE
Boost tank Temperatur

### ISSUE THREAD

**Issue by Voodoomoped** [speleolontra/daikin_residential_altherma#168]
Hello all, 

I would like to know which entity to use to let an automation (based on pv excess) boost the tank temperature.

I remember an older version had this entity but now I have to switch manually in a drop down to get it do the boost. And I just don't know how to set this as automation. 

Would be very nice if someone could help me a little bit. 

Thanks, Daniel

**Comment by jwillemsen** [comment]
See https://github.com/speleolontra/daikin_residential_altherma/issues/82

**Comment by jwillemsen** [comment]
Or https://github.com/speleolontra/daikin_residential_altherma/issues/56

**Comment by Voodoomoped** [comment]
Thanks a lot!
