### ISSUE TITLE
Wrong data coming from API

### ISSUE THREAD

**Issue by liviooo** [speleolontra/daikin_residential_altherma#170]
I think the data that is coming from the Daikin API or heat pump is not 100% correct. The figures shown on the unit are not the same as the data shown in the ONECTA app and in HA.

For example, when using the 'Powerfull' mode... this should only apply to the water buffer and not for the 'leaving water'. Figures and graphs in HA return wrong data.

**Comment by jwillemsen** [comment]
Please attach the device diagnostics data and screenshots of the onecta app and ha showing the issue

**Comment by jwillemsen** [comment]
Closing, without your data and screenshots we can't analyze this further
