### ISSUE TITLE
[Issue]: how does the heatpump work (weatherdependend/leaving water temp, no room thermostat)

### ISSUE THREAD

**Issue by menzil89** [speleolontra/daikin_residential_altherma#174]
Hey guys, I am wondering how my heatpump is working - especially the weatherdependend and water leaving heating curve struggles me. Attached you will find the graph of the last 10 hrs, outside temp is around 12-13°C  (fairly constant) - as you can see the target temp is jumping around between 39° and 47°C (in night hours until 5:30am) - so I am wondering if this heating curve working correct or is there an issue? I would have expected that the heating curve is nearly as constant as outside temp??? 

![image](https://github.com/speleolontra/daikin_residential_altherma/assets/146064965/e748d3d7-6d63-4065-9615-dfd6960f8448)

**Comment by jwillemsen** [comment]
This is more something to check with your installer/daikin, this integration is only about controlling/monitoring the daikin altherma, we don't know the internal algorithm
