### ISSUE TITLE
[Issue]: When trying to turn on/of the boiler in an automation, it doesn't work.  

### ISSUE THREAD

**Issue by admkhe** [speleolontra/daikin_residential_altherma#177]
[Issue]: When trying to turn on/of the boiler in an automation, it doesn't work.  

It does work from the dashboard of HA.

Triggered manually at October 10, 2023 at 19:05:25
Turn off <unknown entity>
Stopped because an error was encountered at October 10, 2023 at 19:05:26 (runtime: 0.08 seconds)
[home-assistant_daikin_residential_altherma_2023-10-10T17-05-44.222Z.log](https://github.com/speleolontra/daikin_residential_altherma/files/12859976/home-assistant_daikin_residential_altherma_2023-10-10T17-05-44.222Z.log)

any help is appreciated.

**Comment by jwillemsen** [comment]
Have you tried to turn the boiler off through the home assistant UI, I just tried that and that works without problems.

**Comment by admkhe** [comment]
yes that works perfectly.  But I need to automate it.

It needs to be turned of between 2AM and 4AM.

My automation is extremely basic:

 
![2023-10-10_19-54-17](https://github.com/speleolontra/daikin_residential_altherma/assets/146985108/99015457-87b3-4568-9d9f-863c9d6cd85c)
