### ISSUE TITLE
[Issue]: Add support for additional leavingWaterTemperature offset (advanced setting the onecta app)

### ISSUE THREAD

**Issue by sraka1** [speleolontra/daikin_residential_altherma#179]
Gateway: BRP069A62
controlMode: leavingWaterTemperature

```
          "temperatureControl": {
            "ref": "#temperatureControl",
            "settable": true,
            "value": {
              "operationModes": {
                "heating": {
                  "setpoints": {
                    "leavingWaterTemperature": {
                      "maxValue": 55,
                      "minValue": 25,
                      "stepValue": 1,
                      "settable": false,
                      "value": 45
                    },
                    "leavingWaterOffset": {
                      "maxValue": 10,
                      "minValue": -10,
                      "stepValue": 1,
                      "settable": true,
                      "value": -4
                    }
                  }
                }
              }
            }
          },
```

https://github.com/speleolontra/daikin_residential_altherma/blob/master/custom_components/daikin_residential_altherma/climate.py#L103

```
            # tempSettable is False
            if device.getData(ATTR_TARGET_LEAVINGWATER_OFFSET) is not None:
                tempSettable = device.getData(ATTR_TARGET_LEAVINGWATER_OFFSET)["settable"]
                # tempSettable is set to True
            if device.getData(ATTR_TARGET_LEAVINGWATER_TEMPERATURE) is not None:
                tempSettable = device.getData(ATTR_TARGET_LEAVINGWATER_TEMPERATURE)["settable"]
                # tempSettable is set to False again
        # This if does not execute, despite LEAVING_WATER_OFFSET being settable
        if tempSettable:
            self._supported_features = SUPPORT_TARGET_TEMPERATURE
```

The same issue exists for
```
max_temp
min_temp
target_temperature
target_temperature_step
```

`current_temperature` is a bit trickier, because it would be nice to see both the actual leaving water temperature AND the currently set offset.

I think it would be nice to have maybe 2 panels with this data (one with the actual leaving water temperature with the actual min and max, but not settable and one with the offset with -10 min and +10 max and settable!) - I'm not that familiar with HA's infrastructure and how that would be done.  Would appreciate at least some guidance, then I could perhaps tackle this myself in a PR. cc @jwillemsen 

It is also interesting that the leaving water offset is not shown as a sensor, despite it clearly being available. I haven't debugged the issue there yet.
```
2023-10-23 10:09:19.508 INFO (MainThread) [custom_components.daikin_residential_altherma.sensor] Device 'Altherma' NOT supports 'leavingWaterOffset'
```

P.S.: I added some extra logging lines when debugging the issue above

[daikin_residential_altherma-24ce5eb0fce07b4c3af128b7d8e4b0a1--0cccec009d4350716d5d3e4f863b31e4.json.redacted.txt](https://github.com/speleolontra/daikin_residential_altherma/files/13067911/daikin_residential_altherma-24ce5eb0fce07b4c3af128b7d8e4b0a1--0cccec009d4350716d5d3e4f863b31e4.json.redacted.txt)

[home-assistant_2023-10-23T08-10-13.348Z.log](https://github.com/speleolontra/daikin_residential_altherma/files/13067915/home-assistant_2023-10-23T08-10-13.348Z.log)

**Comment by sraka1** [comment]
Perhaps we'd need to create two ClimateEntity instances (well, DaikinClimate) in such a case? One for the actual leaving water temp and one for the offset?

**Comment by jwillemsen** [comment]
Same as #172. Did only notice recently that also on my device I have two values, one under advanced.

**Comment by sraka1** [comment]
I guess it's similar, however the control mode in my case is `leavingWaterTemperature`, not `roomTemperature` or `externalRoomTemperature` as it is in the other issue.

What do you mean by two values - in the Onecta app?

**Comment by jwillemsen** [comment]
That I can change the leavingWaterOffset in the advanced settings even for my device which I control using the roomTemperature. Not sure about the best way to support this, will need some more time to think about this.

Can you try

```
tempSettable = tempSettable or device.getData(ATTR_TARGET_LEAVINGWATER_TEMPERATURE)["settable"]
```

**Comment by edautz** [comment]
Would be very nice to implement this because my heating curve is not linear. I would be able with this enhancement to correct the leaving water temperature automatically with the offset.

**Comment by jwillemsen** [comment]
First I want to fix #194 coming week, this is second on the current todo list for this integration

**Comment by jwillemsen** [comment]
https://github.com/speleolontra/daikin_residential_altherma/pull/205 has now support for this, still working on cleanup and adding support for regular Daikin AC units, could you test this in a second HA setup?

**Comment by jwillemsen** [comment]
Can you retest with https://github.com/speleolontra/daikin_residential_altherma/pull/205, this refactors all code and resolves your issue. 

Be aware that all entity IDs have changed, so check your automations and energy dashboard!

**Comment by jwillemsen** [comment]
See https://github.com/jwillemsen/daikin_residential_altherma/releases/tag/v3.0.0 for a release including the necessary changes for this issue

**Comment by jwillemsen** [comment]
@sraka1 @edautz Can you retest with https://github.com/jwillemsen/daikin_residential_altherma/releases/tag/v3.0.1 and let me know if that works.

**Comment by scrivoluce** [comment]
@jwillemsen it works like charms! Thanks for your work, setting leaving water temperature for heating was a long awaited feature!

**Comment by jwillemsen** [comment]
Thanks for the confirmation @scrivoluce! Sponsoring is always welcome, this was way more work as initially thought ;-)

**Comment by scrivoluce** [comment]
I can barely imagine..!
With this kind of interface (BRP069A78 in my case) can we imagine to have a local integration instead going trough cloud?

**Comment by jwillemsen** [comment]
@scrivoluce As far as I know Daikin disabled the local access years ago, hopefully @Daikin-Europe does make this possible in the future

**Comment by edautz** [comment]
Installed it by hand. Seems to work OK. Thanks for your great work.

One remark: If I look at the downloades repos by HACS. It reports V2.8.2 of @speleolontra.

**Comment by edautz** [comment]
Question: I see an additional button. Climate Control On Off mode. What does this button do?

**Comment by jwillemsen** [comment]
One of the bool on off switches, just on/off directly
