### ISSUE TITLE
Add text sensor for controlMode

### ISSUE THREAD

**Issue by jwillemsen** [speleolontra/daikin_residential_altherma#18]
Should export the controlMode to HA

```
                "controlMode": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": "roomTemperature",
                    "values": [
                        "leavingWaterTemperature",
                        "externalRoomTemperature",
                        "roomTemperature"
                    ]
                },
```

**Comment by speleolontra** [comment]
Hi, I'm trying to add this sensor.
But it seems that are accepted only specific SENSOR_TYPES.
I created new SENSOR_TYPES_INFO wit None value (as generic sensor https://www.home-assistant.io/integrations/sensor/#device-class)

![immagine](https://user-images.githubusercontent.com/10747617/151722926-c291ddef-f2c5-4eea-a0e3-cf3a4b046696.png)
![immagine](https://user-images.githubusercontent.com/10747617/151722880-84230c74-f37c-496d-90ee-5d2fd8fe0715.png)

 but with no luck.

![immagine](https://user-images.githubusercontent.com/10747617/151722689-833839fd-b8a3-43d5-9af9-6b4ec2f6e030.png)

Any ideas or example of generic sensors use?
Thanks

**Comment by speleolontra** [comment]
Yeah!
Solved!!

![immagine](https://user-images.githubusercontent.com/10747617/151724262-411ba056-9d50-47a1-a2ea-92b795afe822.png)

this is correct declaration:
![immagine](https://user-images.githubusercontent.com/10747617/151724356-1220812c-bee9-4bf5-9e8d-b13ebf677bb9.png)
![immagine](https://user-images.githubusercontent.com/10747617/151724301-77b2f4ac-2b7d-420e-b335-9835d52a822e.png)

and specific Class...
![immagine](https://user-images.githubusercontent.com/10747617/151724393-8f64acaa-50a4-413c-9dea-33199eb90f80.png)
![immagine](https://user-images.githubusercontent.com/10747617/151724426-c3293848-3e61-4601-9a7b-e85daeea4c4d.png)

**Comment by speleolontra** [comment]
Solved in coming soon commit...
Take me few days for complete testing.
Bye

**Comment by jwillemsen** [comment]
Works!
