### ISSUE TITLE
[Issue]: Invalid config in configuration.yaml

### ISSUE THREAD

**Issue by AdamWyrzykowski** [speleolontra/daikin_residential_altherma#182]
![2023-10-26 02_54_47-Narzędzia deweloperskie – Home Assistant — Mozilla Firefox](https://github.com/speleolontra/daikin_residential_altherma/assets/119930240/ea974f6b-c08d-4179-bc5f-19910d2557f9)
When I follow the instruction, I have this error when validating configuration.yaml

**Comment by jwillemsen** [comment]
What have you added exactly to the file? Try to add single quotes around the strings

**Comment by AdamWyrzykowski** [comment]
single quotes did not any help 
![image](https://github.com/speleolontra/daikin_residential_altherma/assets/119930240/e900d200-d9cc-4e33-8397-06986105ccbb)

**Comment by jwillemsen** [comment]
Try to remove `[]`

**Comment by AdamWyrzykowski** [comment]
thanks Johnny, this made configration.yaml valid 
would be good to correct on main page 
![image](https://github.com/speleolontra/daikin_residential_altherma/assets/119930240/c4c7a772-ea46-467e-8bfe-2e8c13dc431e)
By the way, I have this integration done some weeks ago, and my config was commented out. I've done it correctly, but have not noticed any new device created, why?
![image](https://github.com/speleolontra/daikin_residential_altherma/assets/119930240/6121d0eb-2b76-42b2-a8d1-81f73c6caf0f)

**Comment by jwillemsen** [comment]
See https://github.com/speleolontra/daikin_residential_altherma/pull/183

**Comment by jwillemsen** [comment]
For a lacking device (which you do see in the onecta app) please open a new issue

**Comment by AdamWyrzykowski** [comment]
Yes, I know new topic = new issue. But honestly, I don't see any changes in what I see before and now. 
And before I already have this: 
![image](https://github.com/speleolontra/daikin_residential_altherma/assets/119930240/a303fe79-cb44-49df-b46c-2e56495f0614)
![image](https://github.com/speleolontra/daikin_residential_altherma/assets/119930240/2c6a130d-aa6c-4bef-a1b8-e61bdf5e3a6a)
![image](https://github.com/speleolontra/daikin_residential_altherma/assets/119930240/dff2b9b6-10b8-4749-8364-c60c33dd3812)
If I already had everything before, then I put in question sense of adding those lines in configuration.yaml 
I don't remember, but maybe I gave my credentials within this integration to Daikin website somewhere. I can't recall it.

**Comment by jwillemsen** [comment]
This looks good

**Comment by AdamWyrzykowski** [comment]
Then what for are those lines in configuration.yaml ? Isn't it redundant?

**Comment by jwillemsen** [comment]
Looks redundant for your setup when you have entered them in the UI
