### ISSUE TITLE
Entities are not updated anymore after recent HA Core Update to 11.2

### ISSUE THREAD

**Issue by Thomk-63** [speleolontra/daikin_residential_altherma#191]
After HA core update to 11.2 entities for water heater temperature or room temperature from thermostat are frozen and will not be updated any longer. After a restart the values are updated once, but then stay frozen infinitely. I have a Daikin Altherma 3 H MT ECH2O and a LAN Adapter BRP069A78.

**Comment by jwillemsen** [comment]
Have you upgraded this integration to the latest release, see #187

**Comment by Thomk-63** [comment]
No, I missed that! Thanks for the quick help! I updated now and hope it will work now.

**Comment by Thomk-63** [comment]
Problem solved by updating to the latest release.
