### ISSUE TITLE
[Issue]: Sensor data not being updated anymore

### ISSUE THREAD

**Issue by dannystommen** [speleolontra/daikin_residential_altherma#192]
Since last weekend or so, the sensor data is nog being updated anymore at all. Only when I restart Home Assistant, it's refreshed once, and then stops again. For example, last sensor data I can see now, is from yesterday.
It used to work perfectly fine in beginning. 

Any idea what might be causing this? Or how to troubleshoot this?

Diagnostics logs:
[daikin_residential_altherma-4f7fafb36cf54239ace288cc46aa3159--94819e408f762680b987a7267d99a0af.json](https://github.com/speleolontra/daikin_residential_altherma/files/13349206/daikin_residential_altherma-4f7fafb36cf54239ace288cc46aa3159--94819e408f762680b987a7267d99a0af.json)

Thanks,
Danny

**Comment by jwillemsen** [comment]
Please also attach the home assistant log, maybe there is an error in it?

**Comment by dannystommen** [comment]
I did see some errors, including something with an invalid token and something to need to login again? Unfornuately, I did not save this error before clearing the logs. I figured out clearing the logs before restarting HA would give some cleaner logs. 

The only 2 errors which occur now are the following:
[home-assistant_2023-11-14T18-22-25.384Z.log](https://github.com/speleolontra/daikin_residential_altherma/files/13353936/home-assistant_2023-11-14T18-22-25.384Z.log)

I'll keep an eye on the logs where the login/token error pop ups again.

In the meanwhile: is there some way to re-login again somehow? To see if this solves the issue?

**Comment by jwillemsen** [comment]
Have you upgraded to the latest release of this integration, see #187

**Comment by dannystommen** [comment]
I actually upgraded 5 minutes before your last reply (currenly 18 minutes) ago. I see the sensor data is updated 17 minutes ago for the last time. But I know it's not realtime, so I might have to wait a while.
The good news though is that the servers logs disappear now after I needed to restart HA after the update. So lets wait an hour or so to see if sensor data is actually updated now.

**Comment by henri98** [comment]
I can confirm this. With version `v2.8.2` and HA version `2023.11.2`

**Comment by dannystommen** [comment]
Updating the integration solved the issue voor me.
