### ISSUE TITLE
[Enhancement] : Display if the system is actually heating at the moment

### ISSUE THREAD

**Issue by youdontknowmu** [speleolontra/daikin_residential_altherma#197]
Hi there,

I don't know if it's the right place to suggest an enhancement, but would it be possible to have a sensor that says when the heating has started and stopped ?

This way it would be possible to see how many times a day and precisely how much time did it heat or refreshed the water ?

For now we have the heat mode, the target temperature, but nothing to show if the system actuelly has heated (except with power consumption)

Thanks a lot in advance for any answer !

**Comment by jwillemsen** [comment]
This is not possible, daikin doesn't export that information from their code, see the device diagnostics for all raw data they export. You could maybe use the leaving water temperature to see if it is heating, I am going install a separate power meter before the altherma which I am going to use for this
