### ISSUE TITLE
[Issue]: Changing the Operation mode via Automation.

### ISSUE THREAD

**Issue by joergzambo** [speleolontra/daikin_residential_altherma#199]
Hi!
I try to activate my water heater with an automation (I’d like to turn it on at a specific time of the day or when energy prices are low) but Simply the Action “Turn ON” and “Turn OFF” is not working with my BRP069A78.
I am only able to test the automation when changing the operation mode, but changing it to "Powerful" or simply to "on" or "off" is not working.

When the Water Heater is "on", I am able to set a new temperature (also via automation).

**Comment by jwillemsen** [comment]
See https://github.com/speleolontra/daikin_residential_altherma/issues/122, when that doesn't work please attach your logs

**Comment by joergzambo** [comment]
HI!

I tested the suggested solution, it works perfectly for a few days now. Thank you for your help and work!



 

Von: Johnny Willemsen ***@***.***> 
Gesendet: Donnerstag, 30. November 2023 08:42
An: speleolontra/daikin_residential_altherma ***@***.***>
Cc: joergzambo ***@***.***>; Author ***@***.***>
Betreff: Re: [speleolontra/daikin_residential_altherma] [Issue]: Changing the Operation mode via Automation. (Issue #199)

 

See #122 <https://github.com/speleolontra/daikin_residential_altherma/issues/122> , when that doesn't work please attach your logs
