### ISSUE TITLE
Read madoka wired thermostat values

### ISSUE THREAD

**Issue by zauan** [speleolontra/daikin_residential_altherma#2]
Hi there,

Great work on the integration. would it be possible to also pull data from the madoka thermostat ( for example current temperature )?

The temperature from madoka is seen in the native android app

**Comment by zauan** [comment]
I've made some modification to make the climate control to work properly.

You can find the changes at https://github.com/zauan/daikin_residential_altherma/commit/d63bd33c1a0105e56f5a7fbc7689dfc5309e5b0e

just let me know if you want me to create a pull request. From what I saw in your code, you've disabled this features for some reason :)

**Comment by arn1s-m** [comment]
I guess because if you don't have the remote it returns no values and no use. Is it actually worth it (madoka)? Somehow the hard-wiring requirement is keeping me away from getting it.

**Comment by zauan** [comment]
For me it works. I disliked the idea of a hardwire, however, I installed the heat pump in a new building and it was easy for me to wire the madoka thermostat.

In the end, with the modifications i've made to this integration I can fully use all the features from Hassio climate control:

![image](https://user-images.githubusercontent.com/5928748/144581447-af6a6ec4-b2fa-429b-9d7e-af20402eea93.png)

If this will get merged in master I will probably work on the hot water control as I see that this is not included in the climate control

**Comment by speleolontra** [comment]
Hi Zauan,
i see your edits...
When i started this adventure (modify custom integration for Daikin air conditioning), I had no experience.
But one of first thingh that I undertood is that I dont have a target temperature in my JSON.
In fact my plant has 2 thermostat wifi (one per floor) that commands heat pump with a relè..

Without a target temp, I used Leaving water temp to display in climate control.
![immagine](https://user-images.githubusercontent.com/10747617/145108185-ff60aad1-d2ed-44b4-8892-0452e05c81ff.png)

Because another user has modified my code, my idea was to try to transfer values from const.py file to configuration.yaml, and manage null values to prevent errors...
It's possible in your opinion?
Any user could configure their own integration for their system by reading their own response json.
Thanks Lontra
Lontra

**Comment by MicheleMercuri** [comment]
Hi this is the image 
> PS:
> 
> > The temperature from madoka is seen in the native android app
> 
> Could you post an image of your app with temp of madoka? is Daikin Residential Controller App?

Hi, here there is what you asked. Underlined in yellow is madoka temperature. 
![Screenshot_20220109_003251](https://user-images.githubusercontent.com/97225788/148663512-ca9d0e6f-a78d-44ef-a443-aa61d69fd676.jpg)

**Comment by speleolontra** [comment]
OK, 
it seems that is optional value...

In fact is not present in my interface...
![immagine](https://user-images.githubusercontent.com/10747617/148691892-1f891f68-2bbd-4798-ae89-ae567dffa1f4.png)

I can only set the offset from climatic curve.
At the moment I didn't find a solution for transfer constants to configuration file, that is a possible solution to mantain only one integration.
If you have an idea...

Lontra

**Comment by jwillemsen** [comment]
I have also a modoka thermostat, set on 22, as far as I can see it is set under temperatureControl, roomTemperature

[daikin_data.json.txt](https://github.com/speleolontra/daikin_residential_altherma/files/7924994/daikin_data.json.txt)

**Comment by jwillemsen** [comment]
Looks not all users do have a roomTemperature, maybe the controlMode can be useful and check if there is a roomTemperature below operationModes. Will try to implement such a thing later this week

**Comment by MicheleMercuri** [comment]
I many thanks 4 you excellent work, Can you implement water temperature that heat pump send to radiators/fancoils? I will see that value on heat pump display.
regards.

**Comment by jwillemsen** [comment]
Please attach the daikin_data.json file that this integration downloads into your HA config directory? I will compare it to my Altherma data and see what I can easily expose.

**Comment by MicheleMercuri** [comment]
ok attached to this post. regards. 
[daikin_data.json.txt](https://github.com/speleolontra/daikin_residential_altherma/files/7936906/daikin_data.json.txt)

**Comment by speleolontra** [comment]
@MicheleMercuri 
I think yes, is "leavingWaterTemperature".
is not visible yet in your sensors?
![immagine](https://user-images.githubusercontent.com/10747617/151073603-ec8cd223-1f04-4b79-942b-1c152dd3b044.png)

**Comment by jwillemsen** [comment]
Took me longer as I though, forget a `@property@` that caused some strange errors. See https://github.com/speleolontra/daikin_residential_altherma/pull/13/files for my PR, when there is a roomTemperature in the returned JSON that is now shown and the target temperature can be set

**Comment by MicheleMercuri** [comment]
> @MicheleMercuri I think yes, is "leavingWaterTemperature". is not visible yet in your sensors? ![immagine](https://user-images.githubusercontent.com/10747617/151073603-ec8cd223-1f04-4b79-942b-1c152dd3b044.png)

No, isn't visible. I think due to heat pump settings, when I set Altherma to use madoka sensor that value is disappeared from mobile app and it is visible only on heat pump display.

**Comment by jwillemsen** [comment]
@MicheleMercuri could you attach the daikin_data.json when you use the madoka sensor and the value is disappeared from the mobile app, let us see if they provide it from their cloud, when the data is not there also home assistant can't show it.

**Comment by MicheleMercuri** [comment]
> @MicheleMercuri could you attach the daikin_data.json when you use the madoka sensor and the value is disappeared from the mobile app, let us see if they provide it from their cloud, when the data is not there also home assistant can't show it.

It's here https://github.com/speleolontra/daikin_residential_altherma/files/7936906/daikin_data.json.txt

**Comment by jwillemsen** [comment]
leavingWaterTemperature does seem to be part of sensoryData, maybe wait until my changes are merged @MicheleMercuri and update to the latest master version and try again?

**Comment by MicheleMercuri** [comment]
> leavingWaterTemperature does seem to be part of sensoryData, maybe wait until my changes are merged @MicheleMercuri and update to the latest master version and try again?

Ok I will try as soon as new update is published

**Comment by jwillemsen** [comment]
Can you retest, this should work now

**Comment by MicheleMercuri** [comment]
> Can you retest, this should work now

Works perfectly excellent works 👍 many thanks. 
Regards.
![Screenshot_20220129_215124](https://user-images.githubusercontent.com/97225788/151677356-dc67875b-3df4-44a9-b2c7-afb6b20e67e6.jpg)

**Comment by jwillemsen** [comment]
@zauan, can you retest with master and close this issue when it works?

**Comment by zauan** [comment]
Hi guys! Sorry for disappearing :) ... fully moved to the new house. I've just tested and it works perfectly. 

I will close this ticket and remove my repository so we can have this in one place
