### ISSUE TITLE
[Issue]: Missing (last) datapoint each day resulting in wrong report of power consumption

### ISSUE THREAD

**Issue by mathias-goebel** [speleolontra/daikin_residential_altherma#201]
here is what HA is throwing into influxdb:
![grafik](https://github.com/speleolontra/daikin_residential_altherma/assets/2813649/ef3e48ce-c2aa-40de-88e2-5807e5cd4a2e) 
<details><summary>Flux Query</summary>
<p>
```
from(bucket: "homeassistant")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "kWh")
  |> filter(fn: (r) => r["friendly_name"] == "Altherma Daily Heat Tank Energy Consumption" or r["friendly_name"] == "Altherma Daily Heat Energy Consumption" or r["friendly_name"] == "Altherma Daily Cool Energy Consumption")
  |> filter(fn: (r) => r["_field"] == "value")
  |> aggregateWindow(every: 1d, fn: max, createEmpty: false)
  |> filter(fn: (r) => r["_value"] > 0)
  |> timeShift(duration: -1h1s)
``` 
</p>
</details> 

and without the aggregation for every day it looks like this:
![grafik](https://github.com/speleolontra/daikin_residential_altherma/assets/2813649/16a5642b-4faa-4ce4-8f0b-f81f2ff3a8a6)

instead the app is reporting (total view, week report):
![Screenshot_20231204-215750](https://github.com/speleolontra/daikin_residential_altherma/assets/2813649/2d72435f-48bf-4a9f-bd8c-211447d72281)

Comparsion:
| Day | Influx (total) | Onecta |
|--------|--------|--------|
| Dec 4 | 16 | 16 |
| Dec 3 | 18 | 19 |
| Dec 2 | 22 | 24 |
| Dec 1 | 16 | 18 |
| Nov 30 | 15 | 17 | 
| Nov 29 | 21 | 21 | 
| Nov 28 | 15 | 16 | 
| Nov 27 | 15 | 17 | 

those are the hard facts, i guess. i suspect that a single datapoint is missing at the end of each day, because the values sometimes match, but missing just one or two kWh when not matching. i am happy to provide further data. i just now set HA log to debug.
Thank you, folks!

> edit: removed logfiles since not needed

**Comment by jwillemsen** [comment]
The problem is very likely that at the end of the day the daily value is reset to zero, have you tried to monitor the yearly heat consumption, the energy dashboard can use that value also without problems, that only has the small issue that the last kWh of a day are maybe reported on the next day, but the total is correct

**Comment by mathias-goebel** [comment]
ahh, i see. first tests indicate that with yearly values i get correct results leaving me in fear of the new years eve! :-)
for weekly values the same error as for daily values occurs for sunday, Dec 3. And it is likely to occur on all sundays.

for those about to flux:
````sql
from(bucket: "homeassistant")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "kWh")
  |> filter(fn: (r) => r["friendly_name"] == "Altherma Yearly Heat Tank Energy Consumption" or r["friendly_name"] == "Altherma Yearly Heat Energy Consumption" or r["friendly_name"] == "Altherma Yearly Cool Energy Consumption")
  |> filter(fn: (r) => r["_field"] == "value")
  |> aggregateWindow(every: 1d, fn: max, createEmpty: true)
  |> difference()
  |> filter(fn: (r) => r["_value"] > 0)
  |> timeShift(duration: -1h1s)
````

i can just suspect that the update interval is just missing the very last value per day (pulling from API, i guess) before the reset. since the resulting error for daily value is quite large, i would recommend an information/documentation on this placed rather prominent.
also i am wondering why there is a timespan for all these results. the reset for example in my small sample is between 00:08am and 00:53am making it more complicate windowing/chuncking the time series data here.

thank you @jwillemsen

**Comment by jwillemsen** [comment]
The delay is very likely caused by the delay of the daikin cloud and the polling frequency of HA. Feel free to open a pull request to extend the documentation ;-).
