### ISSUE TITLE
[Issue]: failed reload of integration

### ISSUE THREAD

**Issue by BramDeBock** [speleolontra/daikin_residential_altherma#202]
After updating to the latest version I'm unable to reload the integration in HA. Below the log details:

```
Logger: homeassistant.config_entries
Source: config_entries.py:399
First occurred: 8:27:18 PM (2 occurrences)
Last logged: 9:25:44 PM

Error setting up entry Daikin for daikin_residential_altherma
Traceback (most recent call last):
  File "/config/custom_components/daikin_residential_altherma/daikin_api.py", line 472, in retrieveAccessToken
    self.tokenSet = await self._doAccessTokenRequest(daikinunified_url)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential_altherma/daikin_api.py", line 242, in _doAccessTokenRequest
    if params["code"] is not None:
       ~~~~~~^^^^^^^^
KeyError: 'code'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/daikin_residential_altherma/daikin_api.py", line 176, in refreshAccessToken
    await self.retrieveAccessToken(data[CONF_EMAIL], data[CONF_PASSWORD])
  File "/config/custom_components/daikin_residential_altherma/daikin_api.py", line 474, in retrieveAccessToken
    raise Exception("Failed to retrieve access token: %s", e)
Exception: ('Failed to retrieve access token: %s', KeyError('code'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 399, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential_altherma/__init__.py", line 85, in async_setup_entry
    await daikin_api.getCloudDeviceDetails()
  File "/config/custom_components/daikin_residential_altherma/daikin_api.py", line 483, in getCloudDeviceDetails
    json_puredata = await self.doBearerRequest("/v1/gateway-devices")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential_altherma/daikin_api.py", line 118, in doBearerRequest
    await self.refreshAccessToken()
  File "/config/custom_components/daikin_residential_altherma/daikin_api.py", line 182, in refreshAccessToken
    raise Exception(
Exception: Token refresh was not successful! Status: 400
```

**Comment by jwillemsen** [comment]
Have you tried to restart HA a few times, could be an issue at the side of daikin, see also https://github.com/rospogrigio/daikin_residential#known-issues-and-troubleshooting

**Comment by BramDeBock** [comment]
Yes I have - that's when I started experiencing issues with it.

**Comment by jwillemsen** [comment]
I had yesterday problems with the onecta app, maybe something on the daikin side? That part of the code didn't change at all, not sure what is happening.

**Comment by jwillemsen** [comment]
Maybe you can enable debug logging (see readme), hopefully that tells us more

**Comment by jwillemsen** [comment]
Please attach your log and device diagnostics, I am running 2023.12.0 without problems

**Comment by chrfin** [comment]
Here the main part of the device diagnostics, debug log see above:

```
{
 "home_assistant": {
   "installation_type": "Home Assistant OS",
   "version": "2023.12.1",
   "dev": false,
   "hassio": true,
   "virtualenv": false,
   "python_version": "3.11.6",
   "docker": true,
   "arch": "aarch64",
   "timezone": "Europe/Vienna",
   "os_name": "Linux",
   "os_version": "6.1.58-haos-raspi",
   "supervisor": "2023.11.6",
   "host_os": "Home Assistant OS 11.2",
   "docker_version": "24.0.7",
   "chassis": "embedded",
   "run_as_root": true
 },
 "custom_components": {
   "hacs": {
     "version": "1.33.0",
     "requirements": [
       "aiogithubapi>=22.10.1"
     ]
   },
   "daikin_residential_altherma": {
     "version": "2.8.2",
     "requirements": [
       "oic==1.6.0"
     ]
   },
   "daikin_residential": {
     "version": "2.3.1",
     "requirements": [
       "oic==1.6.0"
     ]
   },
   "hikconnect": {
     "version": "2.2.0",
     "requirements": [
       "hikconnect==1.2.0"
     ]
   }
 }
}
```

**Comment by BramDeBock** [comment]
Hello,

Core - 2023.12.1
Supervisor - 2023.11.6
Operating System - 11.2
Frontend - 20231208.2

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.12.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Brussels",
    "os_name": "Linux",
    "os_version": "6.1.63-haos",
    "supervisor": "2023.11.6",
    "host_os": "Home Assistant OS 11.2",
    "docker_version": "24.0.7",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.33.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "daikin_residential_altherma": {
      "version": "2.8.2",
      "requirements": [
        "oic==1.6.0"
      ]
    }
_ _ _ _ _ _ _ _ _ _ _ _ _ _

Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 8:15:26 AM (1 occurrences)
Last logged: 8:15:26 AM

Error setting up entry Daikin for daikin_residential_altherma
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential_altherma/__init__.py", line 85, in async_setup_entry
    await daikin_api.getCloudDeviceDetails()
  File "/config/custom_components/daikin_residential_altherma/daikin_api.py", line 483, in getCloudDeviceDetails
    json_puredata = await self.doBearerRequest("/v1/gateway-devices")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential_altherma/daikin_api.py", line 118, in doBearerRequest
    await self.refreshAccessToken()
  File "/config/custom_components/daikin_residential_altherma/daikin_api.py", line 176, in refreshAccessToken
    await self.retrieveAccessToken(data[CONF_EMAIL], data[CONF_PASSWORD])
  File "/config/custom_components/daikin_residential_altherma/daikin_api.py", line 444, in retrieveAccessToken
    response = await self.hass.async_add_executor_job(func)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError: Global task timeout
________________________________
Van: Christoph Fink ***@***.***>
Verzonden: zaterdag 9 december 2023 9:21
Aan: speleolontra/daikin_residential_altherma ***@***.***>
CC: Bdb ***@***.***>; Author ***@***.***>
Onderwerp: Re: [speleolontra/daikin_residential_altherma] [Issue]: failed reload of integration (Issue #202)


Here the main part of the device diagnostics, debug log see above:

{
 "home_assistant": {
   "installation_type": "Home Assistant OS",
   "version": "2023.12.1",
   "dev": false,
   "hassio": true,
   "virtualenv": false,
   "python_version": "3.11.6",
   "docker": true,
   "arch": "aarch64",
   "timezone": "Europe/Vienna",
   "os_name": "Linux",
   "os_version": "6.1.58-haos-raspi",
   "supervisor": "2023.11.6",
   "host_os": "Home Assistant OS 11.2",
   "docker_version": "24.0.7",
   "chassis": "embedded",
   "run_as_root": true
 },
 "custom_components": {
   "hacs": {
     "version": "1.33.0",
     "requirements": [
       "aiogithubapi>=22.10.1"
     ]
   },
   "daikin_residential_altherma": {
     "version": "2.8.2",
     "requirements": [
       "oic==1.6.0"
     ]
   },
   "daikin_residential": {
     "version": "2.3.1",
     "requirements": [
       "oic==1.6.0"
     ]
   },
   "hikconnect": {
     "version": "2.2.0",
     "requirements": [
       "hikconnect==1.2.0"
     ]
   }
 }
}

**Comment by BramDeBock** [comment]
I deleted the integration entry to see if I could re-add it. 
It does not accept my credentials with the error message: "Failed to retrieve access token set."

**Comment by chrfin** [comment]
@jwillemsen Anything else we can do to help fix this issue? Maybe try the new version in PR #205?

BTW: For me the problem started when I tried to use "[Daikin Altherma](https://github.com/tadasdanielius/daikin_altherma)" in parallel as I want to use local connection via my BRP069A61.

**Comment by jwillemsen** [comment]
No idea what is happening, I have no problems with my main but also my test HA setup. Maybe @Daikin-Europe has an idea?

**Comment by chrfin** [comment]
Ok, thanks for the quick update. I'll try to debug it on my side again...

**Comment by jwillemsen** [comment]
Maybe some conflict between the two integrations? Have you tried to remove the other one?

**Comment by chrfin** [comment]
That was my first thought and no, removing the other integration did not help. I even restored a full backup which was created before I installed the other integration without success.

Maybe there are some artefacts left behind by the other integration? I'll try to search in that direction...

@BramDeBock Did you also do anything in that direction when the problem started?

**Comment by jwillemsen** [comment]
Maybe some token is stored on disk which is used by both?

**Comment by jwillemsen** [comment]
Some other users report problems when using ipv6, maybe see if you have ipv6 enabled?

**Comment by chrfin** [comment]
Nope - disabling IPv6 did not change anything...

**Comment by jwillemsen** [comment]
Can you try https://github.com/jwillemsen/daikin_residential_altherma/releases/tag/v3.0.1 and enable debug logging, this new version has a lot of fixes and logging changes, please attach the full log here

**Comment by BramDeBock** [comment]
Hello, I have removed the entire integration and restarted.
 /folder 3.0.1 that you suggested has been put into custom_components directly as it does not seem available in HACS yet.
/HA restarted
/Tried to log in via the wizard, but that's been going in circles for about 30 min so does not seem to be working.

________________________________
Van: Johnny Willemsen ***@***.***>
Verzonden: woensdag 20 december 2023 13:33
Aan: speleolontra/daikin_residential_altherma ***@***.***>
CC: Bdb ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [speleolontra/daikin_residential_altherma] [Issue]: failed reload of integration (Issue #202)


Can you try https://github.com/jwillemsen/daikin_residential_altherma/releases/tag/v3.0.1 and enable debug logging, this new version has a lot of fixes and logging changes, please attach the full log here

**Comment by jwillemsen** [comment]
Please enable debug logging (see readme) and attach the log here

**Comment by BramDeBock** [comment]
Hi Johnny,

Cannot enable the debug logging as the integration does not load unfortunately. I tried setting it to ipv4 as well but that does not help me either.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by chrfin** [comment]
I'll try again today, but yesterday I also got a reboot-loop when the extension was downloaded, but it was not even configured yet.

**Comment by jwillemsen** [comment]
Within your HA configuration directory (where your `configuration.yaml` is) you should have a `custom_components/daikin_residential_altherma` subdirectory with the source files like `climate.py`, `switch.py` and all other files from `https://github.com/jwillemsen/daikin_residential_altherma/tree/master/custom_components/daikin_residential_altherma`

**Comment by BramDeBock** [comment]
Hello, my Google Calendar integration was showing the same symptoms and someone there also mentioned it's most likely related to ipv6 issues. The suggestion there was to restart your router... it solved my issue for both this integration and the Google Calendar one - both are up and running!
________________________________
Van: Johnny Willemsen ***@***.***>
Verzonden: donderdag 21 december 2023 8:41
Aan: speleolontra/daikin_residential_altherma ***@***.***>
CC: Bdb ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [speleolontra/daikin_residential_altherma] [Issue]: failed reload of integration (Issue #202)


Within your HA configuration directory (where your configuration.yaml is) you should have a custom_components/daikin_residential_altherma subdirectory with the source files like climate.py, switch.py and all other files from https://github.com/jwillemsen/daikin_residential_altherma/tree/master/custom_components/daikin_residential_altherma

**Comment by jwillemsen** [comment]
Thanks for the feedback @BramDeBock !

**Comment by chrfin** [comment]
I could successfully install v3.2 but same error when initializing:

> Error setting up entry Daikin for daikin\_residential\_altherma  
> Traceback (most recent call last):  
>  File "/usr/src/homeassistant/homeassistant/config\_entries.py", line 402, in async\_setup  
>    result = await component.async\_setup\_entry(hass, self)  
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
>  File "/config/custom\_components/daikin\_residential\_altherma/\_\_init\_\_.py", line 83, in async\_setup\_entry  
>    devices = await daikin\_api.getCloudDevices()  
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
>  File "/config/custom\_components/daikin\_residential\_altherma/daikin\_api.py", line 490, in getCloudDevices  
>    device = Appliance(dev\_data, self)  
>             ^^^^^^^^^^^^^^^^^^^^^^^^^  
>  File "/config/custom\_components/daikin\_residential\_altherma/daikin\_base.py", line 14, in \_\_init\_\_  
>    super().\_\_init\_\_(jsonData, apiInstance)  
>  File "/config/custom\_components/daikin\_residential\_altherma/device.py", line 26, in \_\_init\_\_  
>    if self.daikin\_data\["managementPoints"\] is not None:  
>       ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^  
> KeyError: 'managementPoints'  
>

**Comment by jwillemsen** [comment]
Please attach the full device diagnostics and logs @chrfin

**Comment by jwillemsen** [comment]
@chrfin, can you try https://github.com/jwillemsen/daikin_residential_altherma/releases/tag/v3.2.2

**Comment by chrfin** [comment]
I found the problem.

I have also a BRP069A61 connected to my Altherma to do some local control without cloud, but I linked it to my ONECTA-account.

When I now load the `gateway-devices`\-json (copied the token from debug-log and used Postman) I get this device back with the following content:

>  {  
>         "\_id": "my-id",  
>         "id": "my-id",  
>         "type": "heating",  
>         "deviceModel": "Altherma",  
>         "isCloudConnectionUp": {  
>             "settable": **false**,  
>             "value": **false**  
>         },  
>         "embeddedId": "efdbefa5-ac16-45f1-8299-32b0e4fb74c9",  
>         "timestamp": "2023-12-22T08:10:51.055Z"  
>     }

\=> there is no `managementPoints`\-entry for that device -> `KeyError: 'managementPoints'` 

I removed the BRP069A61 from my ONECTA-account and now it seems to work.

**Comment by jwillemsen** [comment]
The v3.2.2 release adds a check for `managementPoints`, so that should also fixed this

**Comment by chrfin** [comment]
Readded the BRP069A61 to my account and with v3.2.2 it seems to initialize, but HA is "reboot-looping" again.

I'll try removing and re-adding the extension like before to see if that helps...

**Comment by jwillemsen** [comment]
Ok, found some more places, will create a v3.2.3 ;-)

**Comment by chrfin** [comment]
Ok, thanks a lot, I'll deactivated the extension for now and will try again with v3.2.3 :-)

**Comment by jwillemsen** [comment]
Ok @chrfin There is a v3.2.5 with several fixes, hopefully I have fixed all places now

**Comment by chrfin** [comment]
Seems to be working. Anything else I find I will post in the new repo.

Thanks for your great work!
