### ISSUE TITLE
[Issue]: Diaply Water Heater as Card not as entity

### ISSUE THREAD

**Issue by zigamiha** [speleolontra/daikin_residential_altherma#206]
Hi first  of all great job in the plugin. It there a possibility that Water settings would show in Card display like for the heating?

**Comment by jwillemsen** [comment]
Maybe something to check in a regular HA forum, this doesn't look specific to this integration

**Comment by jwillemsen** [comment]
I don't have experience with this, could you check this in a regular HA forum and add any outcome here?
