### ISSUE TITLE
[Issue/Question]: Google OAuth support

### ISSUE THREAD

**Issue by Webreaper** [speleolontra/daikin_residential_altherma#207]
Hi, I've just had an Altherma system installed, and am setting this up in Home Assistant. 

I (possibly stupidly) used Google to create the Onecta account, rather than a traditional user/pass setup. Is there any way to use Google OAuth with this integration, or do I need to somehow either convert my Google account with Daikin, or start again from scratch with a non-Google account?

**Comment by jwillemsen** [comment]
I have no idea, I have only used email/password.

**Comment by Webreaper** [comment]
Thanks, I sorted it in the end by updating to a different email address and then resetting the password.
