### ISSUE TITLE
we have no thermostaat with the newst ha beta 

### ISSUE THREAD

**Issue by Homeassistjoenka** [speleolontra/daikin_residential_altherma#208]

**Comment by Homeassistjoenka** [comment]
![Schermafbeelding 2023-12-28 193327](https://github.com/speleolontra/daikin_residential_altherma/assets/113582714/fe036405-5cd1-4098-a439-dc2cac5abaaa)

**Comment by jwillemsen** [comment]
Please attach your ha log with debugging enabled for this integration and the device diagnostics

**Comment by Homeassistjoenka** [comment]
[message (12).txt](https://github.com/speleolontra/daikin_residential_altherma/files/13789262/message.12.txt)
this?

**Comment by Homeassistjoenka** [comment]
[home-assistant_2023-12-28T20-28-54.474Z.log](https://github.com/speleolontra/daikin_residential_altherma/files/13789310/home-assistant_2023-12-28T20-28-54.474Z.log)

**Comment by jwillemsen** [comment]
I don't see a real error related to the altherma, but I do see other `DeviceConnectionError` in the log, maybe a problem with the latest beta itself?

**Comment by Homeassistjoenka** [comment]
you think that the problem in the beta itself is?

**Comment by jwillemsen** [comment]
Not sure, haven't tested it, maybe try https://github.com/jwillemsen/daikin_residential_altherma/releases/tag/v3.2.11, not sure whether that works with the latest beta

**Comment by jwillemsen** [comment]
Maybe try the latest at https://github.com/jwillemsen/daikin_residential_altherma/releases/tag/v3.2.12

**Comment by jwillemsen** [comment]
Related to https://github.com/home-assistant/core/issues/106522

**Comment by Homeassistjoenka** [comment]
with beta 2 works all the thermostaat, thank for your helping
