### ISSUE TITLE
Tank heater not supported

### ISSUE THREAD

**Issue by Robywood3** [speleolontra/daikin_residential_altherma#214]
Why the tank heater of altherma 3 is not anymore supporter?

Thx in advance!

**Comment by jwillemsen** [comment]
This looks to be a problem in the 2024.1.0 release of HA, as part of https://github.com/jwillemsen/daikin_residential_altherma I have removed all usage of deprecated constants

**Comment by jwillemsen** [comment]
Same as #213

**Comment by fico9999** [comment]
I have the same issue...

![image](https://github.com/speleolontra/daikin_residential_altherma/assets/123003241/a0b6cfcc-93a7-4aa9-9c99-dec2f7a9e73b)

**Comment by fico9999** [comment]
Installed v3.3.0 and my problem has been solved.
I have to reconfigure all my Altherma dashboards because most of the entities changed names.
Why was this done?

**Comment by jwillemsen** [comment]
Because there was much more data exported by Daikin as provided by this integration and there seems to be more and more variants with different fields I took a different approach with my fork, it just looks at the data from Daikin and exports that to HA, it takes all names as provided by Daikin. This made the code much smaller and easier to maintain, I will add a note about the history to the readme

**Comment by jwillemsen** [comment]
You can just change the name, internally a unique id is used.

**Comment by ortigosano** [comment]
> This looks to be a problem in the 2024.1.0 release of HA, as part of https://github.com/jwillemsen/daikin_residential_altherma I have removed all usage of deprecated constants, you could wait on 2024.1.1 to see if that fixes it or install my forked version (not available yet on HACS)

Thanks for sharing your integration!! 
Could be possible to add your forked version to HACS as well? 
Thanks

**Comment by jwillemsen** [comment]
https://github.com/hacs/default/pull/2234

**Comment by ortigosano** [comment]
release 2024.1.1 jsut released and it works again! thanks!

**Comment by jwillemsen** [comment]
Fixed by https://github.com/home-assistant/core/pull/107091
