### ISSUE TITLE
[Issue]:Water Tank Temp control  

### ISSUE THREAD

**Issue by burden42** [speleolontra/daikin_residential_altherma#216]
in Onecta app it is possible to set the  temp of the water tank , not found that control in your integration  , and as there is no useful schedule for water in the app  , or the controller , the ability to adjust the hot water temp in this would be a massive step foreword 
![WhatsApp Image 2024-01-07 at 16 24 16](https://github.com/speleolontra/daikin_residential_altherma/assets/155173389/065dd4e3-a8ad-4115-9806-744cc3a925d3)

**Comment by jwillemsen** [comment]
There should be a water heater entity provided by this integration, but HomeAssistant 2024.1.0 is broken, you need at least 2024.1.1. You could also use https://github.com/jwillemsen/daikin_residential_altherma

**Comment by burden42** [comment]
ta

**Comment by burden42** [comment]
update as sugested fixed issue
