### ISSUE TITLE
[Issue]: Unable to configure integration on HA 2024.1.2

### ISSUE THREAD

**Issue by abouquet** [speleolontra/daikin_residential_altherma#218]
When autoconfiguration is executing, I get the following message

![image](https://github.com/speleolontra/daikin_residential_altherma/assets/2518542/7b493521-8b1a-492b-bc9d-e70cb6b7f54b)

### Logs

```
Error occurred loading flow for integration daikin_residential_altherma: cannot import name 'SensorDeviceClass' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
13:36:43 – (ERREUR) config_entries.py - message survenu pour la première fois à 13:30:32 et apparu 3 fois.
Setup failed for custom integration 'daikin_residential_altherma': Unable to import component: cannot import name 'SensorDeviceClass' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
13:30:08 – (ERREUR) setup.py
```

HA Version : https://www.home-assistant.io/blog/2024/01/03/release-20241/#release-202412---january-6

**Comment by jwillemsen** [comment]
Looks similar to https://github.com/speleolontra/daikin_residential_altherma/issues/215

**Comment by abouquet** [comment]
Should I try your fork ? It seems to be ahead

**Comment by jwillemsen** [comment]
Yes, you can try it, it works for me without problems

**Comment by abouquet** [comment]
> Yes, you can try it, it works for me without problems

Indeed, that works 👌 

Thanks !
