### ISSUE TITLE
[Issue]: Setting the powerfulMode (WaterHeater) from an HA Automation

### ISSUE THREAD

**Issue by my-SmarthomeGmx** [speleolontra/daikin_residential_altherma#220]
Thanks a lot for your work on this integration!

I have a issue that I cant set the powerful mode (for the water heater) from an HA Automation. When I choose the "device" (in the automation action) it does not offer me that option to change that "modus" to choose from. (Maybe there is another way which I am not aware about).

**Comment by jwillemsen** [comment]
See https://github.com/speleolontra/daikin_residential_altherma/issues/130
