### ISSUE TITLE
[Issue]: Energy consumption in the Onecta app does not correspond to the energy consumption shown in HA

### ISSUE THREAD

**Issue by tengiezwolle** [speleolontra/daikin_residential_altherma#221]
Energy consumption in the Onecta app does not correspond to the energy consumption shown in Home Assistant. I get the feeling that the energy consumption is not updated to Home Assistant often enough. 

### Energy consumption Day
<img src="https://github.com/speleolontra/daikin_residential_altherma/assets/113035060/3a74b859-aeb3-4515-b90e-dea3634e644b" width=50% height=50%>

In this screenshot 'Totaal gisteren (Total yesterday)' at 16,0 kWh does not correspond with the reported energy usage for yesterday in Home Assistant, which is reported to be 13kWh. See screenshot below:

![KnipselDAG](https://github.com/speleolontra/daikin_residential_altherma/assets/113035060/994f5d8d-0b8b-4617-9dfc-7e4b89378d35)

<br><br>
### Energy consumption Month
<img src="https://github.com/speleolontra/daikin_residential_altherma/assets/113035060/5b2948e7-efc8-4fa0-8a58-9a330bfd41a7" width=50% height=50%>

In this screenshot 'Deze week (This week)' at 20,0 kWh does not correspond with the reported energy usage for yesterday in Home Assistant, which is reported to be 19kWh. 
Also 'Totaal vorige week (Total last week)' at 154,0 kWh does not correspond with the reported energy usage for yesterday in Home Assistant, which is reported to be 136kWh. 
See screenshots below:
![image](https://github.com/speleolontra/daikin_residential_altherma/assets/113035060/968ea4d7-df8b-40aa-9d45-a92f36269499)
![image](https://github.com/speleolontra/daikin_residential_altherma/assets/113035060/4330ecf2-3840-4152-a0da-0238026b922b)

<br><br>
### Energy consumption Year
<img src="https://github.com/speleolontra/daikin_residential_altherma/assets/113035060/06dc4d4f-6519-4076-b987-133be8d3d458" width=50% height=50%>

In this screenshot 'Dit jaar (This year)' at 249,0 kWh does not correspond with the reported energy usage for yesterday in Home Assistant, which is reported to be 221kWh. 
Also 'Totaal vorig jaar (Total last year)' at 414,0 kWh does not correspond with the reported energy usage for yesterday in Home Assistant, which is reported to be 335kWh. 
See screenshots below:
![image](https://github.com/speleolontra/daikin_residential_altherma/assets/113035060/7b155859-5d6f-4066-a715-1f742d90d770)
![image](https://github.com/speleolontra/daikin_residential_altherma/assets/113035060/96a3d982-e326-42c6-8d2f-e22b3b431045)

<br><br>
### Diagnostics: 
[daikin_residential_altherma-da09b92802794f3d5d0c852ffb0414ef--144e3cac817132f448d35557230fe91a.json.txt](https://github.com/speleolontra/daikin_residential_altherma/files/13948488/daikin_residential_altherma-da09b92802794f3d5d0c852ffb0414ef--144e3cac817132f448d35557230fe91a.json.txt)

**Comment by jwillemsen** [comment]
I compared yesterday my numbers and they do match, but I am using https://github.com/jwillemsen/daikin_residential_altherma. It looks the HA integration shows the data as it is in the json, for example there 3 months with energy usage, 108/229/221 but onecta shows 249, which is not in the json.

**Comment by mitjaahlin** [comment]
I can also confirm that energy stats are working using  [this custom integration]( https://github.com/jwillemsen/daikin_residential_altherma.)

**Comment by tengiezwolle** [comment]
Thanks for your replies. I have installed the mentioned custom integration and will be monitoring to see if the energy usages will be correct.

**Comment by T0MMY24** [comment]
Yes. Data shown in de Onecta app correspond with data shown in HA! Using [this custom integration](https://github.com/jwillemsen/daikin_residential_altherma) solved my issue.
