### ISSUE TITLE
automation and water heater [Issue]: 

### ISSUE THREAD

**Issue by burden42** [speleolontra/daikin_residential_altherma#223]
it might be just my stupidity but ....

trying to set up an automation that looks at the current 1/2 hour electric rate and then changes  the mode and temperature of the water tank . 

have been unable too,
 can do the required functions via a schedule but this is not an dynamic automation . the water heater does not appear as a device but as a service .
the room thermostat does appear as a device and can be adjusted via an automation  

id: '1704724898454'
alias: plungePrice hot water to 60
description: when cost of electicly is below 0 turn on  hot water
trigger: []
condition: []
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - device_id: 20e9434aba283e37702135e2cab18c0f
    domain: water_heater
    entity_id: 8577200abf73e8135ddd28297e49e798
    type: turn_on
  - service: water_heater.set_operation_mode
    data:
      operation_mode: performance
  - service: water_heater.set_temperature
    target:
      area_id: home
      device_id: 20e9434aba283e37702135e2cab18c0f
      entity_id: water_heater.altherma
    data:
      temperature: 60
  - service: water_heater.set_operation_mode
    target:
      area_id: home
      device_id: 20e9434aba283e37702135e2cab18c0f
      entity_id: water_heater.altherma
    data:
      operation_mode: heat pump
  - service: water_heater.set_temperature
    target:
      area_id: home
      device_id: 20e9434aba283e37702135e2cab18c0f
      entity_id: water_heater.altherma
    data:
      temperature: 31
      operation_mode: heat pump
mode: single

trace timeline 

Triggered manually at 20 January 2024 at 21:14:23
Delay for 10 seconds
10 seconds later
Turn on <unknown entity>
Stopped because an error was encountered at 20 January 2024 at 21:14:33 (runtime: 10.06 seconds)

**Comment by jwillemsen** [comment]
See https://github.com/jwillemsen/daikin_residential_altherma/wiki

**Comment by jwillemsen** [comment]
Did the wiki help?

**Comment by burden42** [comment]
yes thankyou 

i had the form of the words very slightly wrong  , interestingly i could not drop in the Yaml directly , had to go via the visual editor using the wiki text as the guide
