### ISSUE TITLE
Daikin Residential Controller for Altherma : The integration is already configured.

### ISSUE THREAD

**Issue by jenspaulus** [speleolontra/daikin_residential_altherma#229]
Hi,

My Onecta app is up and running.
When I want to login in the daikin altherma integration I get the error "The integration is already configured".
My  main domotica system (Niko Home control II) is integrated in home assistant and is connected with the Daikin heat pump as well.
Is it possible that this is causing the problem.

I have the following type of heatpump
ERGA06EVH Daikin
Daikin Altherma 3 R 6kw R32 Buitenunit
SCOP 4,85

I have no idea how to solve this login problem.

**Comment by jwillemsen** [comment]
This integration is end of life, try https://github.com/jwillemsen/daikin_onecta

**Comment by jenspaulus** [comment]
thanks, I will do!

**Comment by jwillemsen** [comment]
Does it work with the other integration?

**Comment by jenspaulus** [comment]
Hi,

I just installed your integration.
I was hoping to be able to set automations to heat up the water when solars are over producing.

These things are not possible with the integration ?
What else can I do more with this integration? I can only see configurations and that's it.
________________________________
Van: Johnny Willemsen ***@***.***>
Verzonden: vrijdag 1 maart 2024 16:57
Aan: speleolontra/daikin_residential_altherma ***@***.***>
CC: jenspaulus ***@***.***>; Author ***@***.***>
Onderwerp: Re: [speleolontra/daikin_residential_altherma] Daikin Residential Controller for Altherma : The integration is already configured. (Issue #229)


This integration is end of life, try https://github.com/jwillemsen/daikin_onecta

**Comment by jwillemsen** [comment]
See https://github.com/jwillemsen/daikin_onecta/wiki, based on your device/settings you can control the climate, water_heater, and select entities provided by this integration
