### ISSUE TITLE
Failed to retrieve access token set

### ISSUE THREAD

**Issue by TheStigh** [speleolontra/daikin_residential_altherma#25]
Hi,

When entering the user/pass from 'Integration' I get 

![image](https://user-images.githubusercontent.com/43895442/152023484-3b061027-c73f-42bd-81b9-471de0243dda.png)

...and this in the log:

```
 Logger: custom_components.daikin_residential_altherma.config_flow
Source: custom_components/daikin_residential_altherma/config_flow.py:59
Integration: daikin_residential_altherma (documentation, issues)
First occurred: 6:49:48 PM (2 occurrences)
Last logged: 6:58:39 PM
Failed to retrieve Access Token: ('Login failed: %s', Exception('Unknown Login error: Login Failed Captcha Required'))
```

Seems they now require Captcha???

**Comment by MichalDoom** [comment]
I had the same problem when I used google login.After register account with private email (not social network) and move home to this account, login is working without issue.

**Comment by speleolontra** [comment]
Hi TheStigh,
temporarily i can't verifi on my test environment because my Altherma will be offline for a few days more.
I have a few questions:
- is the first installation for you or a message appeared unexpectedly from a certain moment on?
- have you also configured the configuration.yaml file?

Thanks!

**Comment by TheStigh** [comment]
> I had the same problem when I used google login.After register account with private email (not social network) and move home to this account, login is working without issue.

@MichalDoom 

Hum, okie... I could try that. Though, the unit is in my summer house and I left there earlier today - I guess I can't test anything until I'm back, or is it simply to CREATE a different account, do the integration, then move back to the google account?

**Comment by TheStigh** [comment]
> Hi TheStigh, temporarily i can't verifi on my test environment because my Altherma will be offline for a few days more. I have a few questions:
> 
>     * is the first installation for you or a message appeared unexpectedly from a certain moment on?
> 
>     * have you also configured the configuration.yaml file?
> 
> 
> Thanks!

Hi speleolontra,

- This is the first installation
- No, I didn't add anything in `configuration.yaml`, I assumed I shouldn't?

**Comment by speleolontra** [comment]
Hi TheStigh,
happy you are solved login problem, I'm using Gmail too. I ill close the issue.

> My model are the Daikin Synergi 3 with the WiFi adapter BRP069C4x.
Sorry but this integration is for Altherma Heat Pump. Daikin Synergi 3 is for air conditioning? 

If yes, can you please open a new issues and load your returned JSON?
Thanks

**Comment by pro2call-nl** [comment]
i'm using my own domain which was working till i changed the password. i removed the daikin device and i want to add another and its giving me this error.
