### ISSUE TITLE
Altherma Yearly Heat Energy Consuption not present

### ISSUE THREAD

**Issue by MichalDoom** [speleolontra/daikin_residential_altherma#27]
Hello
i have problem to get Yearly statistics from Altherma 3.
Direct on device display it is visible. But in Daikin residental application and HA is still 0.
For Tank it is available.

Do you know help?
Thank You

![image](https://user-images.githubusercontent.com/95631905/152540300-1facb5af-89c0-47b2-81fe-394aceaf3204.png)

**Comment by jwillemsen** [comment]
Can you check the logs of HA to see if there is an error. Please attach your daikin_data.json file to this issue, that contains the raw data as returned by daikin. Do you see the same numbers with the daikin app on your phone?

**Comment by MichalDoom** [comment]
[
    {
       
        "deviceModel": "Altherma",
      
      
        "isCloudConnectionUp": {
            "settable": false,
            "value": true
        },
        "lastUpdateReceived": "2022-02-04T13:58:18.183Z",
        "managementPoints": [
            {
                "embeddedId": "gateway",
                "firmwareVersion": {
                    "maxLength": 8,
                    "settable": false,
                    "value": "3.2.1"
                },
                "iconId": {
                    "requiresReboot": false,
                    "settable": true,
                    "value": 3
                },
                "ipAddress": {
                    "maxLength": 15,
                    "settable": false,
                    "value": "192.168.3.130"
                },
                "macAddress": {
                    "maxLength": 17,
                    "settable": false,
                    "value": "48:e7:da:9c:7f:4a"
                },
                "managementPointCategory": "secondary",
                "managementPointType": "gateway",
                "modelInfo": {
                    "maxLength": 9,
                    "settable": false,
                    "value": "BRP069A78"
                },
                "name": {
                    "maxLength": 63,
                    "requiresReboot": false,
                    "settable": true,
                    "value": "Gateway"
                },
                "serialNumber": {
                    "maxLength": 16,
                    "settable": false,
                    "value": "0071783"
                },
                "ssid": {
                    "maxLength": 9,
                    "requiresReboot": false,
                    "settable": false,
                    "value": "daikin-ap"
                },
                "wifiConnectionSSID": {
                    "maxLength": 32,
                    "requiresReboot": false,
                    "settable": false,
                    "value": "Doom"
                },
                "wifiConnectionStrength": {
                    "maxValue": 0,
                    "minValue": -90,
                    "requiresReboot": false,
                    "settable": false,
                    "stepValue": 1,
                    "value": -80
                }
            },
            {
                "consumptionData": {
                    "ref": "#consumptionData",
                    "requiresReboot": false,
                    "settable": false,
                    "value": {
                        "electrical": {
                            "cooling": {
                                "d": [
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null
                                ],
                                "m": [
                                    null,
                                    0,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    0,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null
                                ],
                                "w": [
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    0,
                                    0,
                                    0,
                                    null,
                                    null
                                ]
                            },
                            "heating": {
                                "d": [
                                    4,
                                    3,
                                    5,
                                    4,
                                    4,
                                    2,
                                    3,
                                    2,
                                    3,
                                    2,
                                    3,
                                    1,
                                    3,
                                    3,
                                    2,
                                    2,
                                    2,
                                    2,
                                    2,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null
                                ],
                                "m": [
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null
                                ],
                                "w": [
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    36,
                                    16,
                                    null,
                                    null
                                ]
                            }
                        }
                    }
                },
                "controlMode": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": "leavingWaterTemperature",
                    "values": [
                        "leavingWaterTemperature",
                        "externalRoomTemperature",
                        "roomTemperature"
                    ]
                },
                "embeddedId": "climateControlMainZone",
                "errorCode": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": ""
                },
                "holidayMode": {
                    "ref": "#holidayMode",
                    "requiresReboot": false,
                    "settable": true,
                    "value": {
                        "enabled": false,
                        "endDate": "2017-01-01",
                        "startDate": "2017-01-01"
                    }
                },
                "iconId": {
                    "requiresReboot": false,
                    "settable": true,
                    "value": 8
                },
                "isHolidayModeActive": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "isInEmergencyState": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "isInErrorState": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "isInInstallerState": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "isInWarningState": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "managementPointCategory": "primary",
                "managementPointSubType": "mainZone",
                "managementPointType": "climateControl",
                "name": {
                    "maxLength": 63,
                    "requiresReboot": false,
                    "settable": true,
                    "value": ""
                },
                "onOffMode": {
                    "requiresReboot": false,
                    "settable": true,
                    "value": "on",
                    "values": [
                        "off",
                        "on"
                    ]
                },
                "operationMode": {
                    "requiresReboot": false,
                    "settable": true,
                    "value": "heating",
                    "values": [
                        "heating",
                        "cooling",
                        "auto"
                    ]
                },
                "sensoryData": {
                    "ref": "#sensoryData",
                    "settable": false,
                    "value": {
                        "leavingWaterTemperature": {
                            "maxValue": 127,
                            "minValue": -127,
                            "requiresReboot": false,
                            "settable": false,
                            "stepValue": 1,
                            "value": 40
                        },
                        "outdoorTemperature": {
                            "maxValue": 127,
                            "minValue": -127,
                            "requiresReboot": false,
                            "settable": false,
                            "stepValue": 1,
                            "value": 8
                        }
                    }
                },
                "setpointMode": {
                    "requiresReboot": true,
                    "settable": false,
                    "value": "weatherDependent",
                    "values": [
                        "fixed",
                        "weatherDependentHeatingFixedCooling",
                        "weatherDependent"
                    ]
                },
                "temperatureControl": {
                    "ref": "#temperatureControl",
                    "settable": true,
                    "value": {
                        "operationModes": {
                            "auto": {
                                "setpoints": {
                                    "leavingWaterOffset": {
                                        "maxValue": 10,
                                        "minValue": -10,
                                        "requiresReboot": false,
                                        "settable": true,
                                        "stepValue": 1,
                                        "value": -2
                                    }
                                }
                            },
                            "cooling": {
                                "setpoints": {
                                    "leavingWaterOffset": {
                                        "maxValue": 10,
                                        "minValue": -10,
                                        "requiresReboot": false,
                                        "settable": true,
                                        "stepValue": 1,
                                        "value": 0
                                    }
                                }
                            },
                            "heating": {
                                "setpoints": {
                                    "leavingWaterOffset": {
                                        "maxValue": 10,
                                        "minValue": -10,
                                        "requiresReboot": false,
                                        "settable": true,
                                        "stepValue": 1,
                                        "value": -2
                                    }
                                }
                            }
                        }
                    }
                }
            },
            {
                "consumptionData": {
                    "ref": "#consumptionData",
                    "requiresReboot": false,
                    "settable": false,
                    "value": {
                        "electrical": {
                            "heating": {
                                "d": [
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    2,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    2,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null
                                ],
                                "m": [
                                    null,
                                    1,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    8,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null
                                ],
                                "w": [
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    4,
                                    4,
                                    0,
                                    null,
                                    null
                                ]
                            }
                        }
                    }
                },
                "embeddedId": "domesticHotWaterTank",
                "errorCode": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": ""
                },
                "heatupMode": {
                    "requiresReboot": true,
                    "settable": false,
                    "value": "reheatOnly",
                    "values": [
                        "reheatOnly",
                        "reheatSchedule",
                        "scheduleOnly"
                    ]
                },
                "iconId": {
                    "requiresReboot": false,
                    "settable": true,
                    "value": 9
                },
                "isHolidayModeActive": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "isInEmergencyState": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "isInErrorState": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "isInInstallerState": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "isInWarningState": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "isPowerfulModeActive": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "managementPointCategory": "primary",
                "managementPointType": "domesticHotWaterTank",
                "name": {
                    "maxLength": 63,
                    "requiresReboot": false,
                    "settable": true,
                    "value": ""
                },
                "onOffMode": {
                    "requiresReboot": false,
                    "settable": true,
                    "value": "on",
                    "values": [
                        "off",
                        "on"
                    ]
                },
                "operationMode": {
                    "settable": false,
                    "value": "heating",
                    "values": [
                        "heating"
                    ]
                },
                "powerfulMode": {
                    "requiresReboot": false,
                    "settable": true,
                    "value": "off",
                    "values": [
                        "off",
                        "on"
                    ]
                },
                "sensoryData": {
                    "ref": "#sensoryData",
                    "settable": false,
                    "value": {
                        "tankTemperature": {
                            "maxValue": 127,
                            "minValue": -127,
                            "requiresReboot": false,
                            "settable": false,
                            "stepValue": 1,
                            "value": 43
                        }
                    }
                },
                "setpointMode": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": "fixed",
                    "values": [
                        "fixed",
                        "weatherDependent"
                    ]
                },
                "temperatureControl": {
                    "ref": "#temperatureControl",
                    "settable": true,
                    "value": {
                        "operationModes": {
                            "heating": {
                                "setpoints": {
                                    "domesticHotWaterTemperature": {
                                        "maxValue": 60,
                                        "minValue": 30,
                                        "requiresReboot": false,
                                        "settable": true,
                                        "stepValue": 1,
                                        "value": 48
                                    }
                                }
                            }
                        }
                    }
                }
            },
            {
                "eepromVersion": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": "3608726-13C"
                },
                "embeddedId": "indoorUnitHydro",
                "iconId": {
                    "requiresReboot": false,
                    "settable": true,
                    "value": 4
                },
                "managementPointCategory": "secondary",
                "managementPointType": "indoorUnitHydro",
                "modelInfo": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": "EHBX08EF9W"
                },
                "name": {
                    "maxLength": 63,
                    "requiresReboot": false,
                    "settable": true,
                    "value": "Indoor Hydro Unit"
                },
                "softwareVersion": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": "0222"
                }
            },
            {
                "embeddedId": "outdoorUnit",
                "iconId": {
                    "requiresReboot": false,
                    "settable": true,
                    "value": 5
                },
                "managementPointCategory": "secondary",
                "managementPointType": "outdoorUnit",
                "modelInfo": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": ""
                },
                "name": {
                    "maxLength": 63,
                    "requiresReboot": false,
                    "settable": true,
                    "value": "Outdoor Unit"
                },
                "softwareVersion": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": "FFFF"
                }
            },
            {
                "dateTime": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": "2022-02-04T07:43:57"
                },
                "embeddedId": "userInterface",
                "firmwareVersion": {
                    "deprecated": "DEPRECATED",
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": "6.6.0"
                },
                "iconId": {
                    "requiresReboot": false,
                    "settable": true,
                    "value": 6
                },
                "managementPointCategory": "secondary",
                "managementPointType": "userInterface",
                "miconId": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": "21008A02"
                },
                "modelInfo": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": "EHBX08EF9W"
                },
                "name": {
                    "maxLength": 63,
                    "requiresReboot": false,
                    "settable": true,
                    "value": "User Interface"
                },
                "softwareVersion": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": "6.6.0"
                }
            }
        ],
        "timestamp": "2022-02-04T13:58:18.183Z",
        "type": "heating-wlan"
    }
]

**Comment by jwillemsen** [comment]
It looks the monthly data is not in the json at all, please check the daikin app, when it is also not there please open an issue to Daikin themselves, when they don't provide the data this integration can't show it

**Comment by speleolontra** [comment]
I have compared with my json, and i noticed that have a SW version 6.6.0 and I 6.5.0, and an othe entry software version 0222 and I 0221.
Maybe a bug introduced by new update? hopefully not.
@jwillemsen what values have you?

**Comment by jwillemsen** [comment]
I am at 6.3.0 and 0221. I did recently got a firmware update pushed for the wlan adapter through the residential controller app

**Comment by jwillemsen** [comment]
@MichalDoom do you still have only null values?

**Comment by jwillemsen** [comment]
Closing, doesn't see this issue, please reopen when you still lack the data
