### ISSUE TITLE
Add support for errorCode

### ISSUE THREAD

**Issue by jwillemsen** [speleolontra/daikin_residential_altherma#28]
When the device has a problem there is an errorCode set, at this moment I have a AH-00 meaning it hasn't been able to run the desinfection run (heating the water to 60C). Available for the altherma and the hot water tank seperately

```
                "errorCode": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": "AH-00"
                },
```

**Comment by speleolontra** [comment]
Hi,
I think that isn't a problem, it's similar to other info flags...
I'm awaiting to have my heat pump online again to test the master branch with recent implementation and to do also this new Info Sensor.
Bye

**Comment by jwillemsen** [comment]
Works, now shows `HA-00` for tank and altherma on my unit (desinfection not been able to run)
