### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by haz-69** [speleolontra/daikin_residential_altherma#3]
I have installed and entered correct username and password, nothing shows up :(

I have my Daikin Altherma EHVZ08S18DA9W(G) in the Daikin Residential Controller App fully working and even linked to Google Home , but it is not showing up in this integration. Further i have a Daikin ALtherma LAN-Adapter BRP069A62 & a BRC 1HHDAW Human Comfort Interface and a EKRTWA Room thermostat
[](ur
![1](https://user-images.githubusercontent.com/74374387/144705261-b5f3bc41-eb65-4ae5-b97a-d584733496c0.JPG)
![2](https://user-images.githubusercontent.com/74374387/144705262-941f9427-633c-4516-90a6-62f49ba28902.JPG)
![Skärmavbild 2021-12-04 kl  10 55 37](https://user-images.githubusercontent.com/74374387/144705324-fa3088c7-40ed-4d1a-8589-eda3a303c8a4.png)
l)

**Comment by speleolontra** [comment]
Solved with this:
https://github.com/BigFoot2020/daikin_residential_brp069a62
