### ISSUE TITLE
temperature offset

### ISSUE THREAD

**Issue by MichalDoom** [speleolontra/daikin_residential_altherma#36]
Hello,
i have not room thermostat,temperature is controlled by equitherm regulation.From this reason i dont setup heat temperature,but just setup offset +- 10.
In Daikin app it is working but in Ha not.
is possible to change the control from temperature to offset?
thanks for help.

![Screenshot_2022-02-18-20-17-13-819_com daikineurope online controller](https://user-images.githubusercontent.com/95631905/154747836-318edf36-60e8-441c-86db-08446a562f02.jpg)

![Screenshot_2022-02-18-20-16-56-135_io homeassistant companion android](https://user-images.githubusercontent.com/95631905/154747871-b6c96cf5-d5dd-4be9-bb4f-abe6506668d6.jpg)

**Comment by jwillemsen** [comment]
This is currently not yet available within this integration, can you attach your daikin_data.json as reference of what the data is exactly for your daikin installation? See https://github.com/speleolontra/daikin_residential_altherma/issues/24 for a similar issue

**Comment by zauan** [comment]
Off-topic here. @[MichalDoom](https://github.com/MichalDoom) can you please share how did you make the consumption graph?

**Comment by speleolontra** [comment]
@MichalDoom I'm working on your request.
I don't know if its possible, due to climate entity that is part of HA, but in my local debug copy I as able to see a new sensor for the offset...

**Comment by MichalDoom** [comment]
> Off-topic here. @[MichalDoom](https://github.com/MichalDoom) can you please share how did you make the consumption graph?

type: statistics-graph
entities:
  - sensor.altherma_daily_heat_energy_consumption
  - sensor.altherma_daily_heat_tank_energy_consumption
title: Spotreba
chart_type: bar
stat_types:
  - sum
period: day
days_to_show: 365

**Comment by MichalDoom** [comment]
> @MichalDoom I'm working on your request. I don't know if its possible, due to climate entity that is part of HA, but in my local debug copy I as able to see a new sensor for the offset...




@speleolontra  i think this is the part of settings.Now i have offset setup to the same value.

 "temperatureControl": {
                    "ref": "#temperatureControl",
                    "settable": true,
                    "value": {
                        "operationModes": {
                            "auto": {
                                "setpoints": {
                                    "leavingWaterOffset": {
                                        "maxValue": 10,
                                        "minValue": -10,
                                        "requiresReboot": false,
                                        "settable": true,
                                        "stepValue": 1,
                                        "value": -4
                                    }

**Comment by speleolontra** [comment]
yes, I know...
I'm close the solution...

**Comment by speleolontra** [comment]
hi @MichalDoom ,
I've released a new branch https://github.com/speleolontra/daikin_residential_altherma/tree/Climate-with-leavingWaterOffset
Test if it's ok for your Altherma.
![immagine](https://user-images.githubusercontent.com/10747617/155766988-2cc9cfba-7516-4c49-8877-5a5392ccc498.png)
Bye

**Comment by MichalDoom** [comment]
hello,thank you very much for it.I updated the integration,but i dont know how to make control panel as You send me.Can You describe how to make it?Dne 25. 2. 2022 19:18 napsal uživatel speleolontra ***@***.***>:
hi @MichalDoom ,
I've released a new branch https://github.com/speleolontra/daikin_residential_altherma/tree/Climate-with-leavingWaterOffset
Test if it's ok for your Altherma.

Bye

**Comment by speleolontra** [comment]
Hi @MichalDoom have you applied the branch in link? not the master...

**Comment by MichalDoom** [comment]
it offer me update to version f28ab49.After update nothing changed .Dne 26. 2. 2022 23:35 napsal uživatel speleolontra ***@***.***>:
Hi @MichalDoom have you applied the branch in link? not the master...

**Comment by speleolontra** [comment]
Hi, @MichalDoom, f28ab49 is the master. I've merged the branch with the master, now you should see the offset temperature in the climate control.
I'm waiting of your confirmation.
Bye!

**Comment by MichalDoom** [comment]
Hi,

Now is work perfect! Thank You very much. My wife is very satisfied that can control offset when she is cold 😊

How Can I buy a beer to You?

 

Thanks very much again.

**Comment by speleolontra** [comment]
>How Can I buy a beer to You?
ha ha, as if I had already done it.

I would also like to know where you are writing from and have a virtual map of users who are using the integration.
You can write your experience here...
https://community.home-assistant.io/t/daikin-heat-pump-altherma-integration/202760/65

Thank you very much.
Lontra

**Comment by stskrp** [comment]
Hello,
Was it merged into master?
Asking because using leawingWaterOffset mode, but climate shows as "unavailable". It was working ok in roomThermostat mode

**Comment by speleolontra** [comment]
can you try to reinstall custom integration?
I don't know why but hacs don't alert for a ne release available.

**Comment by stskrp** [comment]
I'm on the latest version.
It looks like even when leavingWaterOffset mode is selected, it still reports room temperature, and in code it gets roomTemperature -> makes decision that roomTemperature mode selected.
I was able to fix it for my case by changing conditions in if statements, checking also control_mode example:
```
 @property
    def max_temp(self):
        """Return the maximum temperature we are allowed to set."""
        operationMode = self.getValue(ATTR_OPERATION_MODE)
        if operationMode not in ["auto", "cooling", "heating"]:
            return DEFAULT_MAX_TEMP

        # Only with a separate room temperature we have a
        # max value we can use
        if (
            self.support_room_temperature
            and self.control_mode != "leavingWaterTemperature" #ADDED THIS AND CONDITION
        ):
            return float(self.getData(ATTR_TARGET_ROOM_TEMPERATURE)["maxValue"])

        if self.support_leaving_water_offset:
            return float(self.getData(ATTR_LEAVINGWATER_OFFSET)["maxValue"])

        return DEFAULT_MAX_TEMP
```
I believe this solution is not best, but it covers my case
