### ISSUE TITLE
Device 'None' is filtered out?

### ISSUE THREAD

**Issue by haz-69** [speleolontra/daikin_residential_altherma#4]
[](url
![3](https://user-images.githubusercontent.com/74374387/144708402-16593647-4032-4978-9f7c-a0277eafb7e8.JPG)
)

**Comment by speleolontra** [comment]
Try this...
https://github.com/BigFoot2020/daikin_residential_brp069a62
Bye

**Comment by haz-69** [comment]
Thanx! Works perfectly!
