### ISSUE TITLE
energy dasboard

### ISSUE THREAD

**Issue by MichalDoom** [speleolontra/daikin_residential_altherma#42]
Hello
my question is not direct about this addon but has consequences.
Do You use energy dasboard for count consuption of daikin heat pump?I have problem that data in energy dont correspond with data from daikin sensors and the price is not counted correct.
Have You similiar expirience?Or do you know how to tune it to be ok? Thanks for help.

**Comment by jwillemsen** [comment]
I am also using the energy dashboard and it does seem to match. What are you using for the count consumption, I am using the yearly values, maybe an update is done shortly after midnight and the value for 2200-2400 is assigned to the next day?

**Comment by jwillemsen** [comment]
Does this imply that #27 is not valid anymore?

**Comment by MichalDoom** [comment]
Hello,
i am using day values. I had problem that from power on my daikin heatpump the value of Yearly consumption was not working.It was start after one month of using ( also in Daikin residental app) .It is reason why I cathing data day by day. If I want to use Yearly values,i need somehow tune the value manually - add about 900Kw and also the price.But i dont know how :(

**Comment by MichalDoom** [comment]
> Does this imply that #27 is not valid anymore?

this is not valid.It start work after week.

**Comment by jwillemsen** [comment]
Is this working now, if so, please close this issue

**Comment by jwillemsen** [comment]
Closing, should work, if not, please reopen with the diagnostics data attached
