### ISSUE TITLE
Can login but no devices are created

### ISSUE THREAD

**Issue by Shogun1978** [speleolontra/daikin_residential_altherma#46]
I installed the integration as described, entered my login and password. The integration seems to connect but doesn't create any device or entities. Am I doing something wrong? I attached the downloaded diagnostics, seems like data was pulled. But no devices show up.

[diagnostic.json.txt](https://github.com/speleolontra/daikin_residential_altherma/files/8402060/diagnostic.json.txt)

**Comment by Shogun1978** [comment]
Little update: I got my device working with the https://github.com/BigFoot2020/daikin_residential_brp069a62 integration. Funny: my app says, that I have a BRP069A61...

**Comment by jwillemsen** [comment]
Ok, added a link to the README.md for the other integrations, can you close this issue now it works?
