### ISSUE TITLE
Last update all temperature sensors don't work anymore

### ISSUE THREAD

**Issue by MicheleMercuri** [speleolontra/daikin_residential_altherma#48]
With last update all temperature sensors don't work anymore. 
![Screenshot_20220408_023449](https://user-images.githubusercontent.com/97225788/162340722-1ea34523-630a-4731-9de5-f8a62559506f.jpg)

**Comment by arn1s-m** [comment]
I suggest restarting HA, usually fixes majority of problems

**Comment by MicheleMercuri** [comment]
> I suggest restarting HA, usually fixes majority of problems

Restarted but same problems. All sensors out.

**Comment by MicheleMercuri** [comment]
Solved unistalled integration and installed again.

**Comment by MicheleMercuri** [comment]
Logger: homeassistant.components.sensor
Source: helpers/entity_registry.py:383
Integration: Sensore (documentation, issues)
First occurred: 14:35:35 (2 occurrences)
Last logged: 14:35:35

Error adding entities for domain sensor with platform daikin_residential_altherma
Error while setting up daikin_residential_altherma platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 383, in async_get_or_create
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

**Comment by jwillemsen** [comment]
See the same error here

**Comment by MicheleMercuri** [comment]
thanks [jwillemsen](https://github.com/jwillemsen) so what i can do to solve this problem? downgrade ha version?

**Comment by jwillemsen** [comment]
Very likely related to https://github.com/home-assistant/core/pull/69015

**Comment by jwillemsen** [comment]
Can you try https://github.com/speleolontra/daikin_residential_altherma/pull/49 @MicheleMercuri?

**Comment by MicheleMercuri** [comment]
> Can you try #49 @MicheleMercuri?

Ok just tested and i's works again. many thanks [jwillemsen](https://github.com/jwillemsen) 
this pic is `sensor.altherma_room_temperature`
![Cattura](https://user-images.githubusercontent.com/97225788/162584934-04e52b4e-8826-4627-89e3-468f312a20f8.JPG)

**Comment by jwillemsen** [comment]
Yes, works also for me again with my change

**Comment by MicheleMercuri** [comment]
👍 thanks for all.

**Comment by nagyidai88** [comment]
I have the same problem. Could someone explain in detauls what should I modify to working again?

**Comment by jwillemsen** [comment]
I created https://github.com/speleolontra/daikin_residential_altherma/pull/49 as fix but this isn't merged to master, you could checkout my PR locally and use that for the moment (see https://docs.github.com/en/github-ae@latest/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/checking-out-pull-requests-locally)

**Comment by jwillemsen** [comment]
Closing, should be fixed now
