### ISSUE TITLE
Problem not see devices of entiteiten 

### ISSUE THREAD

**Issue by homeyjoenka** [speleolontra/daikin_residential_altherma#51]
hello I have this installed but I can also log in with my cloud login and the integration is added in home assistant only he does not see any devices what could I have done wrong?
![9C0B3F50-9A96-41B2-BFBE-DCF4C634DAD2](https://user-images.githubusercontent.com/61145850/163190116-95f68b36-185e-40be-a4dd-0c107e412d45.jpeg)
![6C1CDFBF-CC29-49F8-B43D-4AFF9F2916BF](https://user-images.githubusercontent.com/61145850/163190134-4abcb476-3c76-4af1-a278-86c51ee8a8a9.jpeg)
![991EEDD2-7B5D-4F47-860C-07884A8DC1BF](https://user-images.githubusercontent.com/61145850/163190141-54b23dab-d79c-495a-be15-5e08d4fbae21.jpeg)

#

**Comment by speleolontra** [comment]
Hi, 
For a Altherma 3 using a BRP069A61 or BRP069A62 adapter you can use the [daikin_residential_brp069a62](https://github.com/BigFoot2020/daikin_residential_brp069a62) integration.
Let me know if you resolve.
Bye!

**Comment by homeyjoenka** [comment]
Hi 
Ist work i am so happy Thank you so
Much grate work

**Comment by homeyjoenka** [comment]
Hi 
Can we dat change we see now the leaving water setpoint in the thermostaat circle but we Will the inside temperature can that?
![DBAB15E4-515B-4A99-9989-E3C47242DF63](https://user-images.githubusercontent.com/61145850/163249503-f7e5eaa6-76b0-4631-b08d-6c62c995392b.jpeg)

**Comment by speleolontra** [comment]
Hi, 
I think that your heat pump don't measure internal temperature, neither the desired temperature.

In any case, you must open an issue here... 
https://github.com/BigFoot2020/daikin_residential_brp069a62/issues
Thanks...
