### ISSUE TITLE
Daikin airco 

### ISSUE THREAD

**Issue by homeyjoenka** [speleolontra/daikin_residential_altherma#52]
![55D7344E-E3D5-43ED-8815-07FB27A077E0](https://user-images.githubusercontent.com/61145850/163340382-2a35ad3b-05bb-4609-88bf-da697719889b.jpeg)
Hi I don't know if this is right place
but is for the daikin air conditioning with wifi module see image also an integration or link for i can't find anywhere on github for install on hacs

**Comment by jwillemsen** [comment]
For the `normal` daikin airconditioning see https://github.com/rospogrigio/daikin_residential
