### ISSUE TITLE
Energy Consumption Data

### ISSUE THREAD

**Issue by onix62** [speleolontra/daikin_residential_altherma#53]
How can I read out Energy Consumption Data?

**Comment by jwillemsen** [comment]
When you add this integration to HA you should see several `sensor.altherma_*_energy_consumption` entities

**Comment by onix62** [comment]
I think, I cannot use daikin_residential_altherma
with my heatpump EGSAX06DA9W (BRP069A61)

**Comment by jwillemsen** [comment]
I think this one is not for this integration, see https://github.com/BigFoot2020/daikin_residential_brp069a62
