### ISSUE TITLE
Not updating

### ISSUE THREAD

**Issue by andreasfrosig** [speleolontra/daikin_residential_altherma#54]
Hi nice to have the option for the controller, thank you! 
Unfortunately I only get data once after each reload of the integration, after which all entities stays in that state.
Does anyone else experience this?

**Comment by jwillemsen** [comment]
Could you check the error log?

**Comment by andreasfrosig** [comment]
Of cause i assume it is this one: 
`Logger: homeassistant.components.climate
Source: custom_components/daikin_residential_altherma/daikin_base.py:371
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 9:23:27 PM (4 occurrences)
Last logged: 9:25:30 PM

Error adding entities for domain climate with platform daikin_residential_altherma
Error while setting up daikin_residential_altherma platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 518, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 246, in capability_attributes
    if self.target_temperature_step:
  File "/config/custom_components/daikin_residential_altherma/climate.py", line 189, in target_temperature_step
    stepVal = self._device.target_temperature_step
  File "/config/custom_components/daikin_residential_altherma/daikin_base.py", line 371, in target_temperature_step
    return float(self.getData(ATTR_TARGET_TEMPERATURE)["stepValue"])
TypeError: 'NoneType' object is not subscriptable`

**Comment by jwillemsen** [comment]
Could you download and attach the diagnostics of this integration? Remove all keys/data which should be private before uploading

**Comment by andreasfrosig** [comment]
Sure :) 
[config_entry-daikin_residential_altherma-3c66b1dc0e9c431e3ac00b702a93d9cc.json.txt](https://github.com/speleolontra/daikin_residential_altherma/files/8733904/config_entry-daikin_residential_altherma-3c66b1dc0e9c431e3ac00b702a93d9cc.json.txt)

**Comment by andreasfrosig** [comment]
When I look more into the entities, some of them are actually updated, the sensor.altherma_leaving_water_temperature is, but the sensor.altherma_tank_temperature does not seem to be updated, but it might be because they simple very rarely change.
I have updated the heat pump, and will see if things look different tomorrow :)

**Comment by jwillemsen** [comment]
Tank temperature changes very slowly, you have to use a lot of hot water before it drops.

**Comment by andreasfrosig** [comment]
I see that now. 
It had been stuck at initial values after each restart, but after updating the unit it seems to work now. 
Sorry for wasting your time!
