### ISSUE TITLE
No icon

### ISSUE THREAD

**Issue by EvertJob** [speleolontra/daikin_residential_altherma#55]
Hi,

On the intergration page there is no icon for the Daikin add-on. In the HA brands there is a Diakin logo available: https://github.com/home-assistant/brands/tree/master/custom_integrations/daikin_altherma

Is it possible to fix this? Looks nicer 😃

**Comment by jwillemsen** [comment]
Fixed by https://github.com/home-assistant/brands/pull/3608

**Comment by EvertJob** [comment]
Thanks, looks nice!
