### ISSUE TITLE
hot water setpoint temperature?

### ISSUE THREAD

**Issue by colseven** [speleolontra/daikin_residential_altherma#57]
this is a really great project! Since I have a solar system, I would of course like to store the excess energy in the hot water tank, so it would be very important if you could set the hot water setpoint temperature.

would be really great if this would be integrated.

**Comment by jwillemsen** [comment]
See https://github.com/speleolontra/daikin_residential_altherma/issues/14 for an idea I have, not sure when I get some spare time to try this

**Comment by jwillemsen** [comment]
See #85

**Comment by jwillemsen** [comment]
See https://github.com/home-assistant/architecture/issues/353 for an issue/code how to set the step value, not used yet in #85

**Comment by jwillemsen** [comment]
Updated my PR #85, feel free to pull my branch and test

**Comment by jwillemsen** [comment]
I have merged my PR to master, this should be possible with the master version of this integration.
