### ISSUE TITLE
"Invalid Add-on repository!"

### ISSUE THREAD

**Issue by teocannata** [speleolontra/daikin_residential_altherma#58]
Trying to add repository to HACS I get "invalid add-on repository"...maybe is missing something required in new versions?

This is my installation:
Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

Thank you!
Matteo

**Comment by jwillemsen** [comment]
What is the exact URL you try to add?

**Comment by teocannata** [comment]
Tried both
`https://github.com/speleolontra/daikin_residential_altherma.git`
and without extension
`https://github.com/speleolontra/daikin_residential_altherma`

**Comment by teocannata** [comment]
I think I found what is missing, I compared this repo with others and a **repository.yaml** or **repository.json** file is missing here containing _name,url,maintainer._
By the way under HACS was able to add the repository going under Integrations instead of Custom Components.
