### ISSUE TITLE
Way to know altherma is working ?

### ISSUE THREAD

**Issue by cedricf25** [speleolontra/daikin_residential_altherma#66]
Hello,

Thanks for this beautiful integration !

Is there a way to know if altherma compressor is working or sleeping ?
Thanks :)

Cedric

**Comment by jwillemsen** [comment]
Not as far as I know, you can download the diagnostics under the devices settings of this integration and see if there is anything in the XML but currently Daikin only exports part of the data from the Altherma, hopefully at some point they export much more of their internal state, would make it much easier to monitor the Altherma
