### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by cipriancaba** [speleolontra/daikin_residential_altherma#67]
The integration stopped working with an altherma 3 heat pump a couple of days ago. Problem seems to be at refreshing the token. Location is Romania

Tried re-adding this from scratch, but no luck. I am currently using the Onecta app on my mobile phone and the user and passwords that I set there

Am I doing something wrong or is this a limitation from Daikin's cloud ?

**Comment by cipriancaba** [comment]
I noticed that the integration connects directly to the cognito pool, but Onecta app now seems to take you to id.daikin.eu where you need to login, they do a weird proxy redirect, and only then you get access to the app. 

This is the full url of the login `https://id.daikin.eu/b2c-oidc/eu.html`

**Comment by Gollam** [comment]
We have an Altherma 3 in Hungary. I just found this integration now, and I installed it. It seemed to work fine, configuration was ok, login was successful, entities were added. But the entities did not update for more than an hour now. How often should it update?

**Comment by cipriancaba** [comment]
@Gollam you using the onecta app user?

**Comment by Gollam** [comment]
Yes.

**Comment by Gollam** [comment]
@speleolontra it turned out that it was working for me after all. But I did not open this issue, @cipriancaba had the problem with it.

**Comment by cipriancaba** [comment]
Issue was resolved. I had to uninstall and reinstall everything and it started working
