### ISSUE TITLE
Interface update 6.9.0

### ISSUE THREAD

**Issue by cedricf25** [speleolontra/daikin_residential_altherma#70]
Hello,

Be careful before installing version 6.9.0 instead of 6.8.0 !
Now the API is updated every 15 mins instead of near real time :(
Even Onecta app have a delay about 15 mins

Have you the same problem ?

Edit: A new option appeared in Installer menu "daikin home control". But no effect with API

**Comment by speleolontra** [comment]
Hi @cedricf25 I'm a beta tester of Onecta, but I don't have upgraded firmware yet to 6.9.
Have you noticed if data in Ha is updated every 15 minutes and no more in real time?
would be very bad news

**Comment by cedricf25** [comment]
Ha AND Onecta are updated every 15 minutes.... on the other hand, the orders are almost instantaneous

**Comment by speleolontra** [comment]
hi @cedricf25,
I've poor time to dedicate to this project, but in your experience, you suggest to update to 6.9.0 or not.
What type of problem you see with 15 minutes update if Home Assistant command are in real time?

Also, can you send a picture of Installer menu "daikin home control"?
Thanks

**Comment by colseven** [comment]
I have 6.9.0 interface firmware and FFFF Firmware outdoor unit, update every minute.

**Comment by colseven** [comment]
![E6A932F8-41B9-4514-8534-F269E2BE2127](https://user-images.githubusercontent.com/63189272/201023288-4487bcb8-959b-464a-8856-22eeb278898b.png)
