### ISSUE TITLE
Althermal heating turing on and off status delay

### ISSUE THREAD

**Issue by Fedrosa** [speleolontra/daikin_residential_altherma#72]
Hello, i have an issue with turning on and off and also the temperature control i noticed that there is a delay of fetching the current status, for example when i turn on the heating it takes around 1 minute to take affect in home assistant  while when i turn on the heating from home assistant i can see immediately without delay the change in daikin application, so i assume that there is an issue with fetching the current status (delay)  I have attached a video with the issue

https://user-images.githubusercontent.com/48185668/199322860-84bfd4a2-d6f2-4e50-981c-f77c57dc97c9.mp4

**Comment by speleolontra** [comment]
Hi @Fedrosa ,
I've similar delay of 10-15 seconds, not one minutes.
I'm using:
- Home Assistant 2022.8.7
- Heat Pump firmware 6.8.0
- but integration isn't the last update
Maybe can be useful

**Comment by colseven** [comment]
Same here 10 seconds.

**Comment by jwillemsen** [comment]
This is a polling integration, so there could be a delay.
