### ISSUE TITLE
Error at Login Terminal

### ISSUE THREAD

**Issue by amongusfungus** [speleolontra/daikin_residential_altherma#74]
Hi and many thanks for the Project!
I think that I've installed everything right but still get the error message "Failed to retrieve access token set." It's when o enter the mail an password for Daikin cloud.
Anyone an idea? 

Many thanks an kind regards

**Comment by speleolontra** [comment]
Have you tried to reinstall integration?
Also be sure to restart Home Assistant after install.
Let me known if you resolve.

**Comment by amongusfungus** [comment]
Hi,I deleted now my Browsercookies and now it seems to work, thanks! Do you've have an idea why I can't see energy consumption data? Not in HA and also not in ONECTA? 

Thanks

**Comment by speleolontra** [comment]
Hi, HA reads a JSON
that you can download from diagnostic on device
![immagine](https://user-images.githubusercontent.com/10747617/204014492-968c2209-1eb3-4225-81ad-5897c36e51a5.png)

You ill see "consumptionData" (historic) sections and their value.
Normally data are same as Onecta.
However, if you need realtime consumption I think that you need an external sensor.
I measure energy balance with Shelly3em, where I dedicated a measure of Heat Pump Consumption.

Lontra
