### ISSUE TITLE
Change the weather dependant curve and more info of pump, compressor & flow

### ISSUE THREAD

**Issue by ttnguyen111** [speleolontra/daikin_residential_altherma#77]
Hi there,
Is there any way I can change the temp of my weather dependant curve via this? For now, I can see that I can turn on/off the unit, water and tank boost.
Also can I have data of the pump (on or off, compressor (on & off ), compressor temp (*C) and the flow rate (e.g. 10l/second).
I'm not sure whether the data is there already (so just add more in mapping) or there is no such data at all.
Many thanks,
Tat-Thanh (Frank)

**Comment by jwillemsen** [comment]
Ask daikin to export it ;-). That data is not made available by daikin, see the diagnostics data of this integration to see what we get

**Comment by ttnguyen111** [comment]
hi there, 
Do you think we may have more data (& control) of the pump if we have the Lan interface (BSP069A61 or A62)? 
I know there are other packages which you can interact with the unit via BRP069A61 or A62.
Also where can I find the diagnostic data please?
Many thanks,

**Comment by jwillemsen** [comment]
Diagnostics is visible under settings/devices, see the three dots in the lower right corner of the daikin residential controller for altherma
