### ISSUE TITLE
Unable to turn on/off heating space

### ISSUE THREAD

**Issue by ttnguyen111** [speleolontra/daikin_residential_altherma#78]
Hi,
I am unable to send on/off command to the heating unit anymore (I still can with the water tank (Altherma tank)).
The Altherma in dashboard is shown as Unavailable and when I clicked in, it shows:

This entity is no longer being provided by the daikin_residential_altherma integration. If the entity is no longer in use, delete it in settings.

I noticed it just happened about 2 hours ago. Just wondering whether this something from my end or from Daikin cloud? Also how to solve it as I rely on it to turn on/off my heating.

Many thanks,
Frank

**Comment by speleolontra** [comment]
Hi Franco, haven't tried yet to restart home assistant?
If yes, probably it can be resolved removing integration and try to reinstall...
Let me know if you resolve...

**Comment by ttnguyen111** [comment]
Hi there,
Thank you for your speedy response.
What I did:
- restart HA
- delete the daikin folder in custom_components and 2 daikin json files outside the customer folder
- restart HA and check whether the daikin is still there. It was not so I deleted successfully.
- fresh download, unzip and place the folder in the custom_component again
- add integration & re-key in the log in details
- I still see the data history (room temperature, outside temperature etc.) so I am not sure whether I have reinstalled properly.

Now the Altherma has gone. When I looked at Automation/When something is triggered, there are only 6 items: turn on/off/toggle the Alterma boost (water) and Altherma Tank (water).

Please let me know what else I can do now.

Many thanks,
Frank

**Comment by speleolontra** [comment]
What's your platform?
Have you tried to ad custom integration using Hacs?
Can you download diagnostico data from integration?

**Comment by ttnguyen111** [comment]
I run HA on a Mac (no virtual machine, the whole mac is dedicated for HA).
I am unable to install HACS on HA (since I have no Adds-on & SSH).
The app worked absolutely fine about 4 hours ago and all of a sudden, the on/off com
[daikin_residential_altherma-b1ec10024cef1cda65de1e21082fcf7a-None-2aea3ec0dcf1e561a59200875f47f899.json-2.txt](https://github.com/speleolontra/daikin_residential_altherma/files/10262871/daikin_residential_altherma-b1ec10024cef1cda65de1e21082fcf7a-None-2aea3ec0dcf1e561a59200875f47f899.json-2.txt)
mand gone.
Please find the diagnostic data attached (I replaced all IDs with XXX)

**Comment by speleolontra** [comment]
Any errors in HA logs?

**Comment by ttnguyen111** [comment]
not that I am aware of, no.
Btw, I changed my heating control from (1) Leaving Water Temperature to (3) Room Thermostat and now the Altherma is back! I am able to turn on/off the heating now.
It is very strange since I had had the (1) Leaving Water Temperature ran for about 3-4 days already. I want to control when to turn on/off the heating unit based on the outside temperature hence I need to use your app (your app is great btw)

**Comment by jwillemsen** [comment]
Closing, doesn't seem to be an issue anymore reading back the replies
