### ISSUE TITLE
Change the target temperature in automation

### ISSUE THREAD

**Issue by ttnguyen111** [speleolontra/daikin_residential_altherma#79]
Hi,

I can increase/decrease the Target Temperature in Altherma climate.altherma by clicting or dragging the icon.

My question: is there any way I can trigger those actions (increase/decrease) automatically? In other words, how can I do that in Automation since there are only 8 actions available.

Many thanks,
Frank

**Comment by teocannata** [comment]
I created an automation using `climate.set_temperature` service as action and selecting altherma entity 😊
Matteo

**Comment by jwillemsen** [comment]
Should be possible, see the remark of @teocannata
