### ISSUE TITLE
Not able to connect to Daikin BRP069A78 WLAN card (configuration menu options greyed out except AP mode)

### ISSUE THREAD

**Issue by FredG2** [speleolontra/daikin_residential_altherma#83]
Dear all,

All configuration options (see below) in the "Wireless Network" menu for the Daikin BRP069A78 WLAN SD-Card in the display of my hot water tank are greyed out, except for "Mode" [D.1] with the sub-option "AP".

[D] Wireless gateway
[D.1] Mode
[D.2] Reboot
[D.3] WPS
[D.4] Remove from cloud
[D.5] Home network connection
[D.6] Cloud connection

As a result, I have not yet managed to include the WLAN card in my home network.

A connection via the Onecta app does not work either. The Onecta connection wheel is spinning forever when I try to connect to it as an "AP". Since I can't include the card in my home network the Onecta App does not show the device as part of my home network.

The card radiates a WLAN "daikin-ap" and I was able to connect to it with a notebook using the network key: "D5ApAG5R2J2tnFRA5My7Y28rP95mv65" which I found on the Internet. Not even a network key is on my card. I also managed to connect my Apple Iphone to the WLAN "daikin-ap" but I can not get any further and have the Onecta App also connect to it and even if it would connect the WLAN "daikin-ap" does not have any Internet access since it is not part of my home network.

After connecting to my notebook, the IP connection has the following data:

Wireless LAN Adapter WiFi:

   Connection specific DNS suffix:
   Description. . . . . . . . . . . : Intel(R) Centrino(R) Advanced-N 6235
   physical address . . . . . . . . : C4-85-08-41-6E-AF
   DHCP enabled. . . . . . . . . . : Yes
   Auto configuration enabled. . . : Yes
   Link-local IPv6 address . : fe80::10f:b198:365b:6551%21(Preferred)
   IPv4 Address (Auto Configuration): 169.254.160.21(Preferred)
   subnet mask . . . . . . . . . . : 255.255.0.0
   default gateway . . . . . . . . . : 192.168.10.1
   DHCPv6 IAID . . . . . . . . . . . : 264537352
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-18-23-62-82-C4-85-08-41-6E-AF
   DNS server . . . . . . . . . . . : 0.0.0.0
   NetBIOS over TCP/IP . . . . . . . : Enabled

But none of that helps me, because I can't get a connection to the WLAN "daikin-ap" access point either from my AVM Fritzbox 4040 floor router or from the BinTec main router.

Is the card broken?
Does the firmware of the hot water tank need an update?
Is somethink wrong with the software version of the WLAN card?

Thanks very much for any hints,

Best regards,

FredG2

**Comment by jwillemsen** [comment]
Looks something for which you should contact your installer, first step is to get the Altherma connected so that you can see it in the Onecta app. Things to check is whether your normal network has a 2.4Ghz setup, and not some special characters in the name/password

**Comment by FredG2** [comment]
Hello Johnny,thanks for your andere. My home network is indeed running on 2,4 Ghz. I have meanwhile double checked it and even disabled the 5 Ghz antennas. The SSID of my home network does not contain any special characters. The security is WPA2 AES or CCMP respectively.The password however is containing special characters „..!?..“ Do you say not even the password of my home network can contain special characters?Many thanks in advance!Regards,FredAm 22.02.2023 um 16:39 schrieb Johnny Willemsen ***@***.***>:﻿
Looks something for which you should contact your installer, first step is to get the Altherma connected so that you can see it in the Onecta app. Things to check is whether your normal network has a 2.4Ghz setup, and not some special characters in the name/password

**Comment by jwillemsen** [comment]
Not sure which restrictions the wifi adapter has, please contact your installer to have it setup

**Comment by FredG2** [comment]
Hello Johnny,I called the Daikin support and they said I should ask the installer to send me a new card.Only if this is not working either the Daikin Support would come to my house.Regards FredAm 22.02.2023 um 20:31 schrieb Johnny Willemsen ***@***.***>:﻿
Not sure which restrictions the wifi adapter has, please contact your installer to have it setup
