### ISSUE TITLE
Fallback code for BigFoot2020

### ISSUE THREAD

**Issue by jwillemsen** [speleolontra/daikin_residential_altherma#9]
In several files there is code which does something special when None is returned, there is a comment "BigFoot2020" related to those lines, do those need to be kept, at least with my daikin units I do get values with these calls

**Comment by speleolontra** [comment]
Thanks jwillemsen, you are great! 
Unfortunately, I'm not very familiar with git hub and will be a little slow on the uptake of your suggestions, but I promise to find some time to spend on it.

do you recommend that I compare my files with your branches?
Thanks a lot

**Comment by jwillemsen** [comment]
I will try to make some PRs, did you add the BigFoot2020 code? I will check your daikin_data.json with mine when making changes.

**Comment by speleolontra** [comment]
Hi @jwillemsen ,
now, we have 5 rows with BigFoot2020 comment.
![immagine](https://user-images.githubusercontent.com/10747617/152873107-ac6e441d-609b-4f02-a8dc-d6aa11d02cc8.png)
It's right?
I can close the issue?
Thanx

**Comment by jwillemsen** [comment]
Do we need that fallback code, any daikin_data.json I have seen before does have these fields and doesn't need the fallback code

**Comment by jwillemsen** [comment]
We don't need this anymore, see https://github.com/speleolontra/daikin_residential_altherma/pull/85/commits/a6ade4bd24c88a58ca8f7022682d51feade538f4 for the cleanup

**Comment by jwillemsen** [comment]
Code has been removed
