### ISSUE TITLE
Issue with climate.py

### ISSUE THREAD

**Issue by palecs** [speleolontra/daikin_residential_altherma#93]
Hello @jwillemsen because of integration of tank and more updates I have issue like this:

```
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 629, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 264, in capability_attributes
    self.hass, self.min_temp, self.temperature_unit, self.precision
  File "/config/custom_components/daikin_residential_altherma/climate.py", line 187, in min_temp
    return self._device.min_temp
  File "/config/custom_components/daikin_residential_altherma/daikin_base.py", line 286, in min_temp
    return float(self.getData(ATTR_TARGET_ROOM_TEMPERATURE)["minValue"])
TypeError: 'NoneType' object is not subscriptable`
```

**Issue is that in daikin_base.py is logic like this:**
1. check if you have thermostat if yes return value
2. if you dont have thermostat return value of leaving_water_offset

Issue in this logic is, that if you/I have thermostat and you are not regulating temperature based on this, but using it only as temperature display and you are regulating temperature based on leaving_water_offset you will never get climate.py working. So maybe switch, or check how is the regulation done and then choose value. It is also maxValue, and other multiple parts in code where is 1st check of thermostat and return of value. 

If I manually edit it and change only order of if, climate.py is running. 

Thank you.

**Comment by jwillemsen** [comment]
Can you attach the diagnostics of your device @palecs and also share your manual edits so that I can see what you changed?

**Comment by jwillemsen** [comment]
@palecs, can you try https://github.com/jwillemsen/daikin_residential_altherma/tree/jwi-controlmode?

**Comment by jwillemsen** [comment]
I have done another push, probably not 100% fixed yet, but the correct change looks to be to check the `controlMode` and determine on that which fields to use, can you pull my branch another time?

**Comment by jwillemsen** [comment]
Check the log after a restart, could be that there is an error, I control here my device on a thermostat

**Comment by palecs** [comment]
Hello @jwillemsen  after merge and etc. Everything is starting. Showing. But by setting the leaving water offset I get this error:

```
This error originated from a custom integration.

Logger: custom_components.daikin_residential_altherma.device
Source: custom_components/daikin_residential_altherma/device.py:410
Integration: Daikin Residential Controller for Altherma (documentation, issues)
First occurred: 12:23:52 (1 occurrences)
Last logged: 12:23:52

FAILED to validate set_data params: Type of value (<class 'float'>) is not the expected type (<class 'int'>)
```

**Comment by jwillemsen** [comment]
Please try again, currently cleaning up more and more, testing my branch locally also (but I have just room temp)

**Comment by palecs** [comment]
Hello @jwillemsen here is another bug. but we are approaching. Some situation from widget I tried change the temperature.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/daikin_residential_altherma/daikin_base.py:230
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 13:33:59 (1 occurrences)
Last logged: 13:33:59

[2632179328] name 'ATTR_TARGET_LEAVINGWATER_OFFSET' is not defined
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 720, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 613, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/daikin_residential_altherma/climate.py", line 260, in async_set_temperature
    await self._device.async_set_temperature(kwargs[ATTR_TEMPERATURE])
  File "/config/custom_components/daikin_residential_altherma/daikin_base.py", line 230, in async_set_temperature
    return await self.setValue(ATTR_TARGET_LEAVINGWATER_OFFSET, value)
NameError: name 'ATTR_TARGET_LEAVINGWATER_OFFSET' is not defined
```

Thank you.

**Comment by jwillemsen** [comment]
Please tray again @palecs

**Comment by jwillemsen** [comment]
I have merged the changes made until now to master, can you pull master without any of your local changes and let me know what works and what not? Please attach the device diagnostics and the errors you got, that helps to fix the last issues quickly

**Comment by palecs** [comment]
Hi please find attached error:

```
This error originated from a custom integration.

Logger: custom_components.daikin_residential_altherma.device
Source: custom_components/daikin_residential_altherma/device.py:389
Integration: Daikin Residential Controller for Altherma (documentation, issues)
First occurred: 17:27:50 (1 occurrences)
Last logged: 17:27:50

FAILED to validate set_data params: Type of value (<class 'float'>) is not the expected type (<class 'int'>)
```

diag log here:
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.2.5",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "armv7l",
    "timezone": "Europe/Bratislava",
    "os_name": "Linux",
    "os_version": "5.15.84-v7l",
    "supervisor": "2023.01.1",
    "host_os": "Home Assistant OS 9.5",
    "docker_version": "20.10.22",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.30.1",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "daikin_residential_altherma": {
      "version": "2.1.0",
      "requirements": [
        "oic==1.4.0"
      ]
    },
    "eldes_alarm": {
      "version": "1.0.0",
      "requirements": []
    },
    "huawei_solar": {
      "version": "1.2.4",
      "requirements": [
        "huawei-solar==2.2.4"
      ]
    }
  },
  "integration_manifest": {
    "domain": "daikin_residential_altherma",
    "name": "Daikin Residential Controller for Altherma",
    "version": "2.1.0",
    "documentation": "https://github.com/speleolontra/daikin_residential_altherma",
    "dependencies": [],
    "codeowners": [
      "@speleolontra",
      "@jwillemsen"
    ],
    "issue_tracker": "https://github.com/speleolontra/daikin_residential_altherma/issues",
    "requirements": [
      "oic==1.4.0"
    ],
    "iot_class": "cloud_polling",
    "config_flow": true,
    "is_built_in": false
  },
  "data": {
    "tokenset": {
      "email": "xxxx",
      "password": "xxxx",
      "tokenset": {
        "access_token": "eyJraWQiOiJ4cGtRMUhsOEppQkFvbWtpekk3d2MwQzh2ekZONEM1aTRya0hoRnBZSzJzPSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI2NjA2ZjAzMS02N2FkLTQyZGQtOTg0Zi01NWYxYzQ5ZDNiMGQiLCJjb2duaXRvOmdyb3VwcyI6WyJldS13ZXN0LTFfU0xJOXFKcGM3X0NEQyJdLCJpc3MiOiJodHRwczpcL1wvY29nbml0by1pZHAuZXUtd2VzdC0xLmFtYXpvbmF3cy5jb21cL2V1LXdlc3QtMV9TTEk5cUpwYzciLCJ2ZXJzaW9uIjoyLCJjbGllbnRfaWQiOiI3cmszOTYwMmYwZHM4bGswaDA3NnZ2aWpuYiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoib3BlbmlkIiwiYXV0aF90aW1lIjoxNjc3MTY5NTkwLCJleHAiOjE2NzcxNzMxOTAsImlhdCI6MTY3NzE2OTU5MCwianRpIjoiNzk3ZDVlYzItZjNhNi00YzI0LTlmYmQtNWIzMzBjOTEwYWRmIiwidXNlcm5hbWUiOiJDRENfMzE4NjkzZmQxNTRiNGE1YjkyZTcxZmU3NzJjNjE2ZmQifQ.OIfYGUN3UQoOFqzfGiAlel5wmp4Nc2dxk5xQiIWKHNOAXWELKB-6BH-FH7EAsETHOIBwHYoDfcovuD2FGj4EA6JVh0nhVXgf2NfzILez2KHPI2oTG4iEQAJFUkWzB5An6SE5wpudzz872D0lcBKYMvtdjC4JSUaW2HphLlQ-pDL6-oWc8fEAYtnER3hPqItjNRGn_zswDJ2DA826sApJ_1JR9a2TfF0iQQoaW1opaJ1xDjTnYgAAczy7j9-PErFyF7vfL2s4h0TCi92oLYjIH3XPe8Sv1Txg_vJO5L0i8ayHzJIpb50Q8GwKfD1lUukPfZwyTZ76SD7DoHxoks0oqg",
        "refresh_token": "eyJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2R0NNIiwiYWxnIjoiUlNBLU9BRVAifQ.g6t_wO-VM6vyGg16U-lhf-J61xcueKBlDWwY6AdiKZP-78e1erd-SFwaHSUPqHjS91jmEtWGocOOtH9Y-XvO7Z2EDC6n2DRyPEL72sSeEeKsDxy_NKVHCPH9H7kLX71kyJwfteikyDg2JPVMbBjsaqnpVG3tStyP1JV_xGDw1QQrK_O7m9eD_k_oXUz7kOcpSORmc5AU-YaTVBVA25Edh118cFNdt9sLh3MBK-A4FsJS5h2sTkk9KZmJdGGvifdA1ZRFci8F47yYxTCTxqin0kJ3hGGW1FnGpLrdk1LpS27uwsg-La9tz1dc5n7dgg-CNMDjdBDCJ4olHVefhJUxLg.vdKRqEf97LLr-nwi.Da9_ucPGm8aeRfHq8uUXh4hbkkRpuZk6m6rWK8Ig5r4hVw65BDJgZfgcU8JgNfBmylCmGe7Padv_fLB9hzTWpZoGkhfvueMqY9FUNiDCPMqYNBSFBv9W_LfJ7Zto29LvfnsxdBoXKdA6kws7oc2EpBVJqEkdBmWOMYVeqVLrQOPDdJQaEZtEu2gkR0FFMRh8ZUJ6PEDtdgHDM8LAwVYwWVilMClziWamxhKu4J48XmuOg3KD0gcifhg7gGaHbfiCXeZ__2ITtSRzT4DNoceTYewaDkt6oQe3Sl-m_ewsvVZz7Wc1nXPUR2KTi9gy24CC5MBDLvOEG8PqvUVPTV3RfreDz9IDvVncM5hpqjl8Kaihez9fU6i7CmjuiJ7rPBZRjqYZEQw1w26I6LKLA6GIESnYqGH1XaLo9l__gb3n-echW2CKEA420_6eQUF4GqMa6pvhtQIybG7aRAvrgKqy3BQ7aO-pTQ3g06KcgX9l_URG2Qqx4UzifpEeBAGsPy6ZHTYwwCjnZkjbxfCsxT6oRvBPIoV2ftTiZI4L07nuk_qTT3TF-vH39Ydby7w7_nCOUSOUD54tbYAl9jALAi1baUWiU6PBZT6BH4QNPtLFRLPV_8gtestRFAt7X--d9Ec5q9whg1JLnc4OpNGRZP2e2IaVLgOMQwOmqQQPOqd2r3vjtGKWkLQBIBn8bvix1PqMI99QF9PtTbfDUpidGzpeFKjZfoPAfZjUgUdAxkPbJ39c2SIXxRzp17jFFsKcbgLDR0JdiD_-ZZ0PjzDAnl1pd97Djo7uERpffI_WQWfQV_pBlh9_OUJjojAzRDcVcJF-k08Vr33Htvb2PANdRXB77IT2XKzFac-1JGCN15CZsJZVQFINIqiibq-P8RDCFsU7L7kIzJHk0CDCh9zHGydPM4BbpqkMlDcaw1PZ_vFGYW3JRNP-Qi5nb0dwNhPAGdKTeX6F2VPyfC_WqK8yH0G_wg3xIxppuJxFR3gPVzLrImhtCNs8weISDLfiGuFSGyCs869XBx8epPtUx_cJxW-c93-Qa5wqekdv1CGelVPwDcY07HdiK0W-mi5y0fgar6gXcJ-W59iclNrZt5SaSXoAM0-pKroi7tXsVnDs2v5MGCPEMsZcZKZkeN3ZL09vNoxAUtpB6U1Z21cnCspa59FvRpCgohYCkgC4xh2A3KhaRBo-jbCAaGF02DlrvwSecR9r69SZLy0ABbtFZA.kOT0t4972tB6xqGzMFD-DA",
        "expires_in": 3600,
        "token_type": "Bearer"
      }
    },
    "json_data": [
      {
        "_id": "88987bd9-a7aa-4ca7-a65f-754ffd0fda08",
        "deviceModel": "Altherma",
        "type": "heating-wlan",
        "isCloudConnectionUp": {
          "settable": false,
          "value": true
        },
        "managementPoints": [
          {
            "embeddedId": "gateway",
            "managementPointType": "gateway",
            "managementPointCategory": "secondary",
            "firmwareVersion": {
              "settable": false,
              "value": "3.2.4",
              "maxLength": 8
            },
            "ipAddress": {
              "settable": false,
              "value": "192.168.4.201",
              "maxLength": 15
            },
            "iconId": {
              "settable": true,
              "requiresReboot": false,
              "value": 3
            },
            "isFirmwareUpdateSupported": {
              "settable": false,
              "requiresReboot": false,
              "value": true
            },
            "macAddress": {
              "settable": false,
              "value": "00:e9:3a:4b:16:50",
              "maxLength": 17
            },
            "modelInfo": {
              "settable": false,
              "value": "BRP069A78",
              "maxLength": 9
            },
            "name": {
              "settable": true,
              "requiresReboot": false,
              "value": "Gateway",
              "maxLength": 63
            },
            "ssid": {
              "settable": false,
              "requiresReboot": false,
              "value": "daikin-ap",
              "maxLength": 9
            },
            "serialNumber": {
              "settable": false,
              "value": "0019465",
              "maxLength": 16
            },
            "wifiConnectionSSID": {
              "settable": false,
              "requiresReboot": false,
              "value": "zIoT",
              "maxLength": 32
            },
            "wifiConnectionStrength": {
              "settable": false,
              "requiresReboot": false,
              "value": -36,
              "maxValue": 0,
              "minValue": -90,
              "stepValue": 1
            }
          },
          {
            "embeddedId": "climateControlMainZone",
            "managementPointType": "climateControl",
            "managementPointCategory": "primary",
            "managementPointSubType": "mainZone",
            "consumptionData": {
              "settable": false,
              "requiresReboot": false,
              "ref": "#consumptionData",
              "value": {
                "electrical": {
                  "heating": {
                    "d": [
                      1,
                      1,
                      1,
                      0,
                      2,
                      0,
                      1,
                      1,
                      0,
                      1,
                      1,
                      1,
                      1,
                      1,
                      1,
                      1,
                      0,
                      0,
                      1,
                      1,
                      null,
                      null,
                      null,
                      null
                    ],
                    "w": [
                      11,
                      13,
                      19,
                      21,
                      15,
                      6,
                      0,
                      18,
                      9,
                      10,
                      6,
                      null,
                      null,
                      null
                    ],
                    "m": [
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      817,
                      329,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null
                    ]
                  },
                  "cooling": {
                    "d": [
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      null,
                      null,
                      null,
                      null
                    ],
                    "w": [
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      0,
                      null,
                      null,
                      null
                    ],
                    "m": [
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      0,
                      0,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null
                    ]
                  }
                }
              }
            },
            "controlMode": {
              "settable": false,
              "requiresReboot": false,
              "value": "leavingWaterTemperature",
              "values": [
                "leavingWaterTemperature",
                "externalRoomTemperature",
                "roomTemperature"
              ]
            },
            "errorCode": {
              "settable": false,
              "requiresReboot": false,
              "value": "-00",
              "maxLength": 16
            },
            "holidayMode": {
              "settable": true,
              "requiresReboot": false,
              "ref": "#holidayMode",
              "value": {
                "enabled": false,
                "startDate": "2023-02-19",
                "endDate": "2023-02-21"
              }
            },
            "iconId": {
              "settable": true,
              "requiresReboot": false,
              "value": 8
            },
            "isHolidayModeActive": {
              "settable": false,
              "requiresReboot": false,
              "value": false
            },
            "isInEmergencyState": {
              "settable": false,
              "requiresReboot": false,
              "value": false
            },
            "isInErrorState": {
              "settable": false,
              "requiresReboot": false,
              "value": false
            },
            "isInInstallerState": {
              "settable": false,
              "requiresReboot": false,
              "value": false
            },
            "isInWarningState": {
              "settable": false,
              "requiresReboot": false,
              "value": false
            },
            "name": {
              "settable": true,
              "requiresReboot": false,
              "value": "",
              "maxLength": 63
            },
            "onOffMode": {
              "settable": true,
              "requiresReboot": false,
              "value": "on",
              "values": [
                "off",
                "on"
              ]
            },
            "operationMode": {
              "settable": true,
              "requiresReboot": false,
              "value": "heating",
              "values": [
                "heating",
                "cooling",
                "auto"
              ]
            },
            "sensoryData": {
              "settable": false,
              "ref": "#sensoryData",
              "value": {
                "roomTemperature": {
                  "settable": false,
                  "requiresReboot": false,
                  "value": 24.1,
                  "maxValue": 127,
                  "minValue": -127,
                  "stepValue": 0.1
                },
                "outdoorTemperature": {
                  "settable": false,
                  "requiresReboot": false,
                  "value": 11,
                  "maxValue": 127,
                  "minValue": -127,
                  "stepValue": 1
                },
                "leavingWaterTemperature": {
                  "settable": false,
                  "requiresReboot": false,
                  "value": 24,
                  "maxValue": 127,
                  "minValue": -127,
                  "stepValue": 1
                }
              }
            },
            "setpointMode": {
              "settable": false,
              "requiresReboot": true,
              "value": "weatherDependent",
              "values": [
                "fixed",
                "weatherDependentHeatingFixedCooling",
                "weatherDependent"
              ]
            },
            "temperatureControl": {
              "settable": true,
              "ref": "#temperatureControl",
              "value": {
                "operationModes": {
                  "auto": {
                    "setpoints": {
                      "leavingWaterOffset": {
                        "settable": true,
                        "requiresReboot": false,
                        "value": -10,
                        "maxValue": 10,
                        "minValue": -10,
                        "stepValue": 1
                      }
                    }
                  },
                  "heating": {
                    "setpoints": {
                      "leavingWaterOffset": {
                        "settable": true,
                        "requiresReboot": false,
                        "value": -10,
                        "maxValue": 10,
                        "minValue": -10,
                        "stepValue": 1
                      }
                    }
                  },
                  "cooling": {
                    "setpoints": {
                      "leavingWaterOffset": {
                        "settable": true,
                        "requiresReboot": false,
                        "value": 0,
                        "maxValue": 10,
                        "minValue": -10,
                        "stepValue": 1
                      }
                    }
                  }
                }
              }
            }
          },
          {
            "embeddedId": "domesticHotWaterTank",
            "managementPointType": "domesticHotWaterTank",
            "managementPointCategory": "primary",
            "consumptionData": {
              "settable": false,
              "requiresReboot": false,
              "ref": "#consumptionData",
              "value": {
                "electrical": {
                  "heating": {
                    "d": [
                      0,
                      0,
                      0,
                      1,
                      0,
                      0,
                      0,
                      0,
                      0,
                      2,
                      0,
                      0,
                      0,
                      0,
                      0,
                      2,
                      0,
                      0,
                      0,
                      0,
                      null,
                      null,
                      null,
                      null
                    ],
                    "w": [
                      5,
                      3,
                      4,
                      3,
                      5,
                      3,
                      0,
                      1,
                      1,
                      3,
                      2,
                      null,
                      null,
                      null
                    ],
                    "m": [
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      84,
                      76,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null,
                      null
                    ]
                  }
                }
              }
            },
            "errorCode": {
              "settable": false,
              "requiresReboot": false,
              "value": "-00",
              "maxLength": 16
            },
            "iconId": {
              "settable": true,
              "requiresReboot": false,
              "value": 9
            },
            "isHolidayModeActive": {
              "settable": false,
              "requiresReboot": false,
              "value": false
            },
            "isInEmergencyState": {
              "settable": false,
              "requiresReboot": false,
              "value": false
            },
            "isInErrorState": {
              "settable": false,
              "requiresReboot": false,
              "value": false
            },
            "isInInstallerState": {
              "settable": false,
              "requiresReboot": false,
              "value": false
            },
            "isInWarningState": {
              "settable": false,
              "requiresReboot": false,
              "value": false
            },
            "isPowerfulModeActive": {
              "settable": false,
              "requiresReboot": false,
              "value": false
            },
            "name": {
              "settable": true,
              "requiresReboot": false,
              "value": "",
              "maxLength": 63
            },
            "onOffMode": {
              "settable": true,
              "requiresReboot": false,
              "value": "on",
              "values": [
                "off",
                "on"
              ]
            },
            "operationMode": {
              "settable": false,
              "value": "heating",
              "values": [
                "heating"
              ]
            },
            "powerfulMode": {
              "settable": true,
              "requiresReboot": false,
              "value": "off",
              "values": [
                "off",
                "on"
              ]
            },
            "schedule": {
              "settable": true,
              "ref": "#schedule",
              "value": {
                "currentMode": {
                  "settable": false,
                  "value": "heating",
                  "values": [
                    "heating"
                  ]
                },
                "modes": {
                  "heating": {
                    "enabled": {
                      "settable": false,
                      "requiresReboot": false,
                      "value": true
                    },
                    "currentSchedule": {
                      "settable": true,
                      "requiresReboot": false,
                      "value": "scheduleHeatingMode1",
                      "values": [
                        "scheduleHeatingMode1"
                      ]
                    },
                    "meta": {
                      "minIntervalBetweenActions": "00:10:00",
                      "maxSchedules": 1,
                      "maxActionsPerActionPeriod": 4,
                      "consecutiveActionsAllowed": true,
                      "actionTypes": {
                        "domesticHotWaterTemperature": {
                          "settable": false,
                          "values": [
                            "eco",
                            "comfort",
                            "turn_off"
                          ]
                        }
                      }
                    },
                    "schedules": {
                      "scheduleHeatingMode1": {
                        "settable": true,
                        "name": {
                          "settable": true,
                          "requiresReboot": false,
                          "value": "User defined"
                        },
                        "meta": {
                          "isReadOnly": false,
                          "actionPeriods": [
                            "monday",
                            "tuesday",
                            "wednesday",
                            "thursday",
                            "friday",
                            "saturday",
                            "sunday"
                          ]
                        },
                        "actions": {
                          "monday": {
                            "05:50:00": {
                              "domesticHotWaterTemperature": "comfort"
                            },
                            "07:00:00": {
                              "domesticHotWaterTemperature": "turn_off"
                            },
                            "17:30:00": {
                              "domesticHotWaterTemperature": "comfort"
                            },
                            "21:00:00": {
                              "domesticHotWaterTemperature": "turn_off"
                            }
                          },
                          "tuesday": {
                            "05:50:00": {
                              "domesticHotWaterTemperature": "comfort"
                            },
                            "07:00:00": {
                              "domesticHotWaterTemperature": "turn_off"
                            },
                            "17:30:00": {
                              "domesticHotWaterTemperature": "comfort"
                            },
                            "21:00:00": {
                              "domesticHotWaterTemperature": "turn_off"
                            }
                          },
                          "wednesday": {
                            "05:50:00": {
                              "domesticHotWaterTemperature": "comfort"
                            },
                            "07:00:00": {
                              "domesticHotWaterTemperature": "turn_off"
                            },
                            "17:30:00": {
                              "domesticHotWaterTemperature": "comfort"
                            },
                            "21:00:00": {
                              "domesticHotWaterTemperature": "turn_off"
                            }
                          },
                          "thursday": {
                            "05:50:00": {
                              "domesticHotWaterTemperature": "comfort"
                            },
                            "07:00:00": {
                              "domesticHotWaterTemperature": "turn_off"
                            },
                            "17:30:00": {
                              "domesticHotWaterTemperature": "comfort"
                            },
                            "21:00:00": {
                              "domesticHotWaterTemperature": "turn_off"
                            }
                          },
                          "friday": {
                            "05:50:00": {
                              "domesticHotWaterTemperature": "comfort"
                            },
                            "07:00:00": {
                              "domesticHotWaterTemperature": "turn_off"
                            },
                            "17:30:00": {
                              "domesticHotWaterTemperature": "comfort"
                            },
                            "21:00:00": {
                              "domesticHotWaterTemperature": "turn_off"
                            }
                          },
                          "saturday": {
                            "05:50:00": {
                              "domesticHotWaterTemperature": "comfort"
                            },
                            "07:30:00": {
                              "domesticHotWaterTemperature": "eco"
                            },
                            "17:00:00": {
                              "domesticHotWaterTemperature": "comfort"
                            },
                            "21:00:00": {
                              "domesticHotWaterTemperature": "turn_off"
                            }
                          },
                          "sunday": {
                            "05:50:00": {
                              "domesticHotWaterTemperature": "comfort"
                            },
                            "07:30:00": {
                              "domesticHotWaterTemperature": "eco"
                            },
                            "17:00:00": {
                              "domesticHotWaterTemperature": "comfort"
                            },
                            "21:00:00": {
                              "domesticHotWaterTemperature": "turn_off"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            },
            "sensoryData": {
              "settable": false,
              "ref": "#sensoryData",
              "value": {
                "tankTemperature": {
                  "settable": false,
                  "requiresReboot": false,
                  "value": 35,
                  "maxValue": 127,
                  "minValue": -127,
                  "stepValue": 1
                }
              }
            },
            "setpointMode": {
              "settable": false,
              "requiresReboot": false,
              "value": "fixed",
              "values": [
                "fixed",
                "weatherDependent"
              ]
            },
            "temperatureControl": {
              "settable": true,
              "ref": "#temperatureControl",
              "value": {
                "operationModes": {
                  "heating": {
                    "setpoints": {
                      "domesticHotWaterTemperature": {
                        "settable": false,
                        "requiresReboot": false,
                        "value": 43,
                        "maxValue": 55,
                        "minValue": 30,
                        "stepValue": 1
                      }
                    }
                  }
                }
              }
            }
          },
          {
            "embeddedId": "indoorUnitHydro",
            "managementPointType": "indoorUnitHydro",
            "managementPointCategory": "secondary",
            "eepromVersion": {
              "settable": false,
              "requiresReboot": false,
              "value": "3608726-74",
              "maxLength": 16
            },
            "iconId": {
              "settable": true,
              "requiresReboot": false,
              "value": 4
            },
            "modelInfo": {
              "settable": false,
              "requiresReboot": false,
              "value": "EHVX08S23EJ9W",
              "maxLength": 16
            },
            "name": {
              "settable": true,
              "requiresReboot": false,
              "value": "Indoor Hydro Unit",
              "maxLength": 63
            },
            "softwareVersion": {
              "settable": false,
              "requiresReboot": false,
              "value": "0221",
              "maxLength": 16
            }
          },
          {
            "embeddedId": "outdoorUnit",
            "managementPointType": "outdoorUnit",
            "managementPointCategory": "secondary",
            "iconId": {
              "settable": true,
              "requiresReboot": false,
              "value": 5
            },
            "modelInfo": {
              "settable": false,
              "requiresReboot": false,
              "value": "",
              "maxLength": 16
            },
            "name": {
              "settable": true,
              "requiresReboot": false,
              "value": "Outdoor Unit",
              "maxLength": 63
            },
            "softwareVersion": {
              "settable": false,
              "requiresReboot": false,
              "value": "FFFF",
              "maxLength": 16
            }
          },
          {
            "embeddedId": "userInterface",
            "managementPointType": "userInterface",
            "managementPointCategory": "secondary",
            "dateTime": {
              "settable": false,
              "requiresReboot": false,
              "value": "2023-02-23T10:54:56"
            },
            "firmwareVersion": {
              "settable": false,
              "requiresReboot": false,
              "deprecated": "DEPRECATED",
              "value": "6.3.0",
              "maxLength": 16
            },
            "iconId": {
              "settable": true,
              "requiresReboot": false,
              "value": 6
            },
            "miconId": {
              "settable": false,
              "requiresReboot": false,
              "value": "20010E02",
              "maxLength": 16
            },
            "name": {
              "settable": true,
              "requiresReboot": false,
              "value": "User Interface",
              "maxLength": 63
            },
            "softwareVersion": {
              "settable": false,
              "requiresReboot": false,
              "value": "6.3.0",
              "maxLength": 16
            }
          }
        ],
        "embeddedId": "6bfe37aa-43e0-4c23-93de-67cb2e34834a",
        "timestamp": "2023-02-23T16:28:18.497Z",
        "id": "88987bd9-a7aa-4ca7-a65f-754ffd0fda08",
        "lastUpdateReceived": "2023-02-23T16:28:18.497Z"
      }
    ]
  }
}

Thank you.

**Comment by jwillemsen** [comment]
For the future, you can also attach a file to an issue, makes the comments much smaller. For the error logs, I don't see the full stack trace, maybe you need to enable logging, see the readme.md for more details. I think #95 would fix the int error, please try again

**Comment by palecs** [comment]
Hello, my bad and sorry for pasting long logs not as attachement. For now I see everything working. I dont see ability to power on/off altherma, or boost, or tank. Is it planned or Im something missing? Or it is dynamically loaded now, after a lot of improvements. Thank you.

**Comment by jwillemsen** [comment]
Power on/off altherma should be possible using the thermostat card, below the temperature you should see the possible modes, including off. For the tank, when you select the new altherma water heater you should see an operation selection, values heat pump (on), performance (boost), and off.

**Comment by palecs** [comment]
Hello. Issue is that im not having on/off switches. From todays updates I dont remember exactly which one, but it was lost. Im also missing in entities anything related to boost, or switch. It is untached and you can see it here. Thank you.

![image](https://user-images.githubusercontent.com/8471855/220981172-52a6b985-e97e-4951-a03d-949855959b73.png)

**Comment by jwillemsen** [comment]
Try to click both 'Alterma' under controls, see the screen that opens, there should be an operation combo box

**Comment by palecs** [comment]
Hi yes clicking on it makes open operation mode open and also temperatures. I guess performance is boost mode on heater. So I will make my own controls utilizing these options. Thank you.

**Comment by jwillemsen** [comment]
Yes, the home assistant water tank has now a state performance, that is something coming from another integration I used to update this one

**Comment by jwillemsen** [comment]
STATE_PERFORMANCE is coming from HA itself, see https://github.com/home-assistant/core/blob/6112793b195af9ef4ac50bb7ecb3421c695eace4/homeassistant/components/water_heater/reproduce_state.py#L44
