### ISSUE TITLE
Suggestion - versioning

### ISSUE THREAD

**Issue by palecs** [speleolontra/daikin_residential_altherma#99]
Hello if we are going through few milestones isnt it time to start versioning. HACS is complaining that master branch is older then version 1.0, but version 1.0 is way older. thank you.

**Comment by jwillemsen** [comment]
At some point I want to make a new release, first want to get some more feedback from users and maybe do some more cleanup

**Comment by palecs** [comment]
Ok thank you for your response. Feel free to close this issue, or leave it as reminder. thank you for great job.
